"""The intake reference is a specification, so it must fail rather than mislead.

It is generated by parsing frontend source. A regex that stops matching would
normally produce a document with an empty section, which reads as "this field set
does not exist" rather than "the parser broke". Every extractor therefore raises,
and these tests check that it does.

The rest of the file pins the two properties that make the document trustworthy:
the field list is introspected from the model rather than transcribed, and the
distinction between a field the producer fills in and one that is merely mappable
is preserved.
"""
from __future__ import annotations

import html as _html
import re
from typing import Literal, get_args, get_origin

import pytest

from app.modules.reports.schemas import CreateReportRequest
from app.modules.reports.pdf_service import strip_em_dashes
from scripts import generate_intake_reference as gen


_FRONTEND_PRESENT = gen._WIZARD.exists() and gen._MAPPING.exists()
_needs_frontend = pytest.mark.skipif(
    not _FRONTEND_PRESENT, reason="frontend checkout not present"
)


# ── extractors fail loudly ───────────────────────────────────────────────────


class TestExtractorsRaiseRatherThanReturnEmpty:
    def test_a_missing_constant_raises(self):
        with pytest.raises(gen.ExtractionError):
            gen.string_array("NO_SUCH_CONSTANT", "const OTHER = ['a'];")

    def test_a_constant_present_but_empty_raises(self):
        with pytest.raises(gen.ExtractionError):
            gen.string_array("EMPTY_OPTIONS", "const EMPTY_OPTIONS = [];")

    def test_a_missing_value_label_list_raises(self):
        with pytest.raises(gen.ExtractionError):
            gen.value_label_array("MISSING", "const OTHER = [];")

    def test_a_missing_select_raises(self):
        with pytest.raises(gen.ExtractionError):
            gen.select_options("Nonexistent Label", "<div/>")

    def test_missing_steps_raise(self):
        with pytest.raises(gen.ExtractionError):
            gen.wizard_steps("no steps here")

    def test_missing_upload_constraints_raise(self):
        with pytest.raises(gen.ExtractionError):
            gen.upload_constraints("no constraints here")

    def test_missing_step_gating_raises(self):
        with pytest.raises(gen.ExtractionError):
            gen.step_gating("no gating here")

    def test_missing_submitted_metadata_raises(self):
        with pytest.raises(gen.ExtractionError):
            gen.wizard_populated_keys("no metadata object here")


# ── the model is the authority for the field set ─────────────────────────────


class TestFieldIntrospection:
    def test_every_model_field_is_described(self):
        described = {f["name"] for f in gen.backend_fields()}
        assert described == set(CreateReportRequest.model_fields)

    def test_required_flags_match_the_model(self):
        for field in gen.backend_fields():
            expected = CreateReportRequest.model_fields[field["name"]].is_required()
            assert field["required"] is expected, field["name"]

    @pytest.mark.parametrize(
        "field_name",
        ["format", "budget_currency", "production_priority", "report_type",
         "co_production_interest", "audience_skew", "co_production_status"],
    )
    def test_enumerated_fields_list_every_permitted_value(self, field_name):
        """The permitted values must come from the Literal, not a copy of it."""
        annotation = CreateReportRequest.model_fields[field_name].annotation
        expected: list[str] = []

        def collect(node):
            if get_origin(node) is Literal:
                expected.extend(str(v) for v in get_args(node))
                return
            for arg in get_args(node):
                collect(arg)

        collect(annotation)
        described = next(
            f["options"] for f in gen.backend_fields() if f["name"] == field_name
        )
        assert described is not None, f"{field_name} lost its options"
        assert set(described) == set(expected)

    def test_a_free_text_field_reports_no_options(self):
        described = next(
            f for f in gen.backend_fields() if f["name"] == "script_title"
        )
        assert described["options"] is None

    def test_type_rendering_is_readable(self):
        by_name = {f["name"]: f["type"] for f in gen.backend_fields()}
        assert by_name["script_title"] == "text"
        assert by_name["genre"] == "list of text"
        assert by_name["budget_amount"] == "number"
        assert by_name["crew_size"] == "whole number, or omitted"
        assert by_name["b2b_consent"] == "true or false"


# ── collected versus merely mappable ────────────────────────────────────────


@_needs_frontend
class TestCollectionClassification:
    @pytest.fixture(scope="class")
    def doc(self):
        return strip_em_dashes(gen.build_html())

    @pytest.fixture(scope="class")
    def text(self, doc):
        """Entity-decoded view, for asserting on prose the generator escaped."""
        return _html.unescape(doc)

    def test_report_type_is_shown_as_caller_supplied(self, text):
        """The wizard passes it positionally, so it is neither collected from the
        form nor absent. Calling it uncollected would be wrong."""
        assert "report_type" in gen.CALLER_SUPPLIED
        assert "set to paid by the wizard's submit handler" in text

    def test_mapped_but_unset_fields_are_marked_as_such(self, doc):
        """location_strategy, email and language are handled by the mapper and
        never set by the wizard. Showing them as collected would overstate the
        form, showing them as absent would hide that the mapper supports them."""
        source = gen._wizard_source()
        populated = gen.wizard_populated_keys(source)
        mapping = dict(gen.field_mapping())
        for api_field in ("location_strategy", "email", "language"):
            wizard_key = mapping.get(api_field)
            assert wizard_key is not None, f"{api_field} lost its mapping"
            assert wizard_key not in populated, (
                f"{api_field} is now set by the wizard; the document's "
                f"classification needs revisiting"
            )
        assert "mapped, never set by the wizard" in doc

    def test_the_wizard_populates_the_fields_a_producer_fills_in(self):
        populated = gen.wizard_populated_keys(gen._wizard_source())
        for expected in ("title", "genre", "budgetAmount", "format", "country",
                         "crewSize", "targetAudience", "completionDate",
                         "representationGender", "biConsent"):
            assert expected in populated, expected

    def test_episode_fields_are_flagged_as_uncollected(self, doc):
        """They exist to verify the UK high end television threshold and the form
        does not ask for them. That gap belongs in the document."""
        assert "total_episodes" in doc
        assert "high end television threshold" in doc


# ── the document itself ──────────────────────────────────────────────────────


@_needs_frontend
class TestDocument:
    @pytest.fixture(scope="class")
    def doc(self):
        return strip_em_dashes(gen.build_html())

    def test_no_em_dash_survives(self, doc):
        assert "—" not in doc
        assert "&mdash;" not in doc

    def test_headings_carry_no_em_dash(self, doc):
        for heading in re.findall(r"<h[1-4][^>]*>(.*?)</h[1-4]>", doc, re.S):
            assert "—" not in heading

    def test_the_watermark_and_logo_are_present(self, doc):
        assert "Property of DeoMedia and Prodculator" in doc
        assert "data:image/jpeg;base64," in doc

    def test_no_external_asset_is_referenced(self, doc):
        """The document must render offline and inside a PDF."""
        assert 'src="http' not in doc
        assert "<link" not in doc

    def test_every_wizard_step_appears(self, doc):
        text = _html.unescape(doc)
        for _, title, _ in gen.wizard_steps(gen._wizard_source()):
            assert title in text

    def test_the_upload_limit_is_stated(self, doc):
        constraints = gen.upload_constraints(gen._wizard_source())
        assert f"{constraints['max_mb']} MB" in doc
        for mime in constraints["mime_types"]:
            assert mime in doc

    def test_every_option_list_is_rendered(self, doc):
        doc = _html.unescape(doc)
        source = gen._wizard_source()
        for const in ("GENRE_OPTIONS", "FORMAT_OPTIONS", "CAMERA_OPTIONS",
                      "USA_STATES", "CANADA_PROVINCES", "AUSTRALIA_STATES"):
            values = gen.string_array(const, source)
            missing = [v for v in values if v not in doc]
            assert not missing, f"{const} values missing from the document: {missing}"

    def test_the_divergence_check_actually_compares(self, doc):
        """The section must state a verdict, not merely list the two sets."""
        assert ("Every offered value is accepted" in doc
                or "The form offers values the API rejects" in doc)

    def test_the_document_is_substantial(self, doc):
        assert len(doc) > 40_000


@_needs_frontend
def test_form_and_api_option_lists_agree():
    """A value the form offers that the API rejects is a submission failure.

    This is the check the document reports on, asserted here so a divergence
    fails the build rather than only appearing in a document nobody reruns.
    """
    source = gen._wizard_source()
    fields = {f["name"]: (f["options"] or []) for f in gen.backend_fields()}

    offered_formats = gen.string_array("FORMAT_OPTIONS", source)
    rejected = [f for f in offered_formats if f not in fields["format"]]
    assert not rejected, f"the form offers formats the API rejects: {rejected}"

    offered_currency = [v for v, _ in gen.value_label_array("CURRENCY_OPTIONS", source)]
    rejected = [c for c in offered_currency if c not in fields["budget_currency"]]
    assert not rejected, f"the form offers currencies the API rejects: {rejected}"

    offered_priority = [v for v, _ in gen.value_label_array("PRIORITY_OPTIONS", source)]
    rejected = [p for p in offered_priority if p not in fields["production_priority"]]
    assert not rejected, f"the form offers priorities the API rejects: {rejected}"
