"""Default scrape sources, seeded into the scrape_sources table on first run.

Covers 18 territories: US, CA, GB, IE, FR, DE, ES, IT, CZ, HU, AU, NZ, ZA, NG, MT, IS + multi-country.

source_authority values:
  "government_incentive"  — official film commission / government
  "union_agreement"       — ratified or published union/guild CBA or rate card (confidence 75–100)
  "legal_minimum"         — binding statutory / convention collective (confidence 75–90)
  "film_commission_guide" — film commission production guide (confidence 60–74)
  "industry_survey"       — industry body survey data (confidence 45–59)
  "service_company"       — crew agency / service company published rates (confidence 30–44)
  "national_statistics"   — national statistics bureau — indicative, NOT film-specific (confidence 15–30)
  "film_specific"         — film-industry-specific benchmark (non-union)
"""

DEFAULT_SOURCES: list[dict] = [
    # ── Incentives ────────────────────────────────────────────────────────────
    # Aggregators (multi-country)
    {
        "resource_type": "incentives",
        "url": "https://vitrina.ai/blog/film-production-tax-incentives-by-country",
        "label": "Vitrina.ai Global Incentives Tracker",
        "territory": None,
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "government_incentive",
    },
    {
        "resource_type": "incentives",
        "url": "https://www.olffi.com/",
        "label": "Olffi Film Financing Database",
        "territory": None,
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "government_incentive",
    },
    # United Kingdom — incentives
    {
        "resource_type": "incentives",
        "url": "https://www.bfi.org.uk/apply-british-certification-tax-relief",
        "label": "BFI UK Film Tax Relief",
        "territory": "United Kingdom",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "government_incentive",
    },
    {
        "resource_type": "incentives",
        "url": "https://www.gov.uk/government/publications/uk-independent-film-tax-credit",
        "label": "GOV.UK IFTC Policy Note",
        "territory": "United Kingdom",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "government_incentive",
    },
    {
        "resource_type": "incentives",
        "url": "https://ep.com/blog/uk-independent-film-tax-credit-approved-key-updates-for-producers/",
        "label": "Entertainment Partners IFTC Guide",
        "territory": "United Kingdom",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "government_incentive",
    },
    {
        "resource_type": "incentives",
        "url": "https://britishfilmcommission.org.uk/plan-your-production/accessing-uk-tax-reliefs/",
        "label": "British Film Commission Tax Reliefs",
        "territory": "United Kingdom",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "government_incentive",
    },
    # Canada
    {
        "resource_type": "incentives",
        "url": "https://www.canada.ca/en/canadian-heritage/services/funding/cavco-tax-credits/canadian-film-video-production.html",
        "label": "CAVCO Canadian Film Tax Credits",
        "territory": "Canada",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "government_incentive",
    },
    # Australia
    {
        "resource_type": "incentives",
        "url": "https://www.screenaustralia.gov.au/funding-and-support/producer-offset",
        "label": "Screen Australia Producer Offset",
        "territory": "Australia",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "government_incentive",
    },
    {
        "resource_type": "incentives",
        "url": "https://www.ausfilm.com.au/incentives/",
        "label": "Ausfilm Incentives",
        "territory": "Australia",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "government_incentive",
    },
    # Malta
    {
        "resource_type": "incentives",
        "url": "https://www.maltafilmcommission.com/incentives/",
        "label": "Malta Film Commission Incentives",
        "territory": "Malta",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "government_incentive",
    },
    {
        "resource_type": "incentives",
        "url": "https://screenmalta.com",
        "label": "Screen Malta Incentives Guidelines 2024",
        "territory": "Malta",
        "is_pdf": True,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "government_incentive",
    },
    # Ireland
    {
        "resource_type": "incentives",
        "url": "https://www.revenue.ie/en/personal-tax-credits-reliefs-and-exemptions/investment/film-relief/index.aspx",
        "label": "Ireland Section 481 Film Relief",
        "territory": "Ireland",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "government_incentive",
    },
    # France
    {
        "resource_type": "incentives",
        "url": "https://www.cnc.fr/web/en/tax-rebate/the-tax-rebate-for-international-productions-trip_190742",
        "label": "CNC TRIP (France)",
        "territory": "France",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "government_incentive",
    },
    {
        "resource_type": "incentives",
        "url": "https://www.filmfrance.net/en/tax-rebate/tax-rebate-for-international-productions/",
        "label": "Film France Tax Rebate",
        "territory": "France",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "government_incentive",
    },
    # Germany
    {
        "resource_type": "incentives",
        "url": "https://dfff-ffa.de/en.html",
        "label": "FFA DFFF (Germany)",
        "territory": "Germany",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "government_incentive",
    },
    # Spain
    {
        "resource_type": "incentives",
        "url": "https://spainfilmcommission.com/en/blog/spain-film-tax-rebate/",
        "label": "Spain Film Commission Tax Rebate",
        "territory": "Spain",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "government_incentive",
    },
    # Czech Republic
    {
        "resource_type": "incentives",
        "url": "https://www.filmcommission.cz/en/production-incentives/",
        "label": "Czech Film Commission Incentives",
        "territory": "Czech Republic",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "government_incentive",
    },
    # Hungary
    {
        "resource_type": "incentives",
        "url": "https://nfi.hu/en/filming-in-hungary/hungarian-film-incentive",
        "label": "NFI Hungary Film Incentive",
        "territory": "Hungary",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "government_incentive",
    },
    {
        "resource_type": "incentives",
        "url": "https://hungariantaxcredit.com",
        "label": "Hungarian Tax Credit Guide",
        "territory": "Hungary",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "government_incentive",
    },
    {
        "resource_type": "incentives",
        "url": "https://focal.ch/prodvalue",
        "label": "Focal PV Hungary Working Conditions",
        "territory": "Hungary",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "government_incentive",
    },
    # South Africa — NEW territory
    {
        "resource_type": "incentives",
        "url": "https://www.thedtic.gov.za",
        "label": "DTIC Foreign Film Incentive (South Africa)",
        "territory": "South Africa",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "government_incentive",
    },
    # Nigeria
    {
        "resource_type": "incentives",
        "url": "https://www.nfc.gov.ng",
        "label": "Nigerian Film Corporation",
        "territory": "Nigeria",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "government_incentive",
    },
    # New Zealand
    {
        "resource_type": "incentives",
        "url": "https://www.nzfilm.co.nz/incentives/new-zealand-screen-production-rebate",
        "label": "NZFC Screen Production Rebate",
        "territory": "New Zealand",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "government_incentive",
    },
    {
        "resource_type": "incentives",
        "url": "https://screenauckland.com/incentives-taxes/",
        "label": "Screen Auckland — Fringes, Incentives & Tax Guide",
        "territory": "New Zealand",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "government_incentive",
    },
    # Iceland
    {
        "resource_type": "incentives",
        "url": "https://www.icelandicfilmcentre.is/support/production-incentive/",
        "label": "Icelandic Film Centre — 35% Reimbursement Scheme",
        "territory": "Iceland",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "government_incentive",
    },
    {
        "resource_type": "incentives",
        "url": "https://filminiceland.com/incentives/",
        "label": "Film in Iceland — Production Incentive Guide",
        "territory": "Iceland",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "government_incentive",
    },
    # Italy
    {
        "resource_type": "incentives",
        "url": "https://www.anica.it/en/tax-credit/",
        "label": "ANICA Italy Tax Credit",
        "territory": "Italy",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "government_incentive",
    },
    {
        "resource_type": "incentives",
        "url": "https://www.italyfilmcommission.it/en/incentives/",
        "label": "Italy Film Commission Incentives",
        "territory": "Italy",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "government_incentive",
    },

    # ── Grants ────────────────────────────────────────────────────────────────
    {
        "resource_type": "grants",
        "url": "https://culture.ec.europa.eu/creative-europe/creative-europe-media-strand",
        "label": "Creative Europe MEDIA Programme",
        "territory": None,
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "government_incentive",
    },
    {
        "resource_type": "grants",
        "url": "https://www.coe.int/en/web/eurimages/coproduction",
        "label": "Eurimages Co-production Fund",
        "territory": None,
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "government_incentive",
    },
    {
        "resource_type": "grants",
        "url": "https://www.bfi.org.uk/get-funding-support",
        "label": "BFI Funding",
        "territory": "United Kingdom",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "government_incentive",
    },
    {
        "resource_type": "grants",
        "url": "https://www.arts.gov/grants",
        "label": "NEA Film Grants",
        "territory": "United States",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "government_incentive",
    },
    {
        "resource_type": "grants",
        "url": "https://telefilm.ca/en/we-finance-and-support/our-programs",
        "label": "Telefilm Canada Programs",
        "territory": "Canada",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "government_incentive",
    },
    {
        "resource_type": "grants",
        "url": "https://cmf-fmc.ca/our-programs/",
        "label": "Canada Media Fund",
        "territory": "Canada",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "government_incentive",
    },
    {
        "resource_type": "grants",
        "url": "https://www.screenaustralia.gov.au/funding-and-support",
        "label": "Screen Australia Funding",
        "territory": "Australia",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "government_incentive",
    },
    {
        "resource_type": "grants",
        "url": "https://artscouncilmalta.gov.mt/en/film-distribution-grants-programme/",
        "label": "Arts Council Malta Film Grants",
        "territory": "Malta",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "government_incentive",
    },
    {
        "resource_type": "grants",
        "url": "https://www.screenireland.ie/funding",
        "label": "Screen Ireland Funding",
        "territory": "Ireland",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "government_incentive",
    },
    {
        "resource_type": "grants",
        "url": "https://www.ffa.de/funding.html",
        "label": "FFA Funding Programs (Germany)",
        "territory": "Germany",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "government_incentive",
    },
    {
        "resource_type": "grants",
        "url": "https://nfi.hu/en/national-film-institute/funding",
        "label": "NFI Hungary Funding",
        "territory": "Hungary",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "government_incentive",
    },
    {
        "resource_type": "grants",
        "url": "https://www.nzfc.govt.nz/funding-and-support/",
        "label": "NZFC Funding and Support",
        "territory": "New Zealand",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "government_incentive",
    },
    {
        "resource_type": "grants",
        "url": "https://www.icelandicfilmcentre.is/support/",
        "label": "Icelandic Film Centre Grants",
        "territory": "Iceland",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "government_incentive",
    },
    {
        "resource_type": "grants",
        "url": "https://www.nfvf.co.za/grants/",
        "label": "NFVF South Africa Grants",
        "territory": "South Africa",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "government_incentive",
    },

    # ── Festivals ─────────────────────────────────────────────────────────────
    {
        "resource_type": "festivals",
        "url": "https://fiapf.org/festivals/accredited-festivals/competitive-feature-film-festivals/",
        "label": "FIAPF Accredited Festivals",
        "territory": None,
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "government_incentive",
    },
    {
        "resource_type": "festivals",
        "url": "https://www.bfi.org.uk/bfi-london-film-festival",
        "label": "BFI London Film Festival",
        "territory": "United Kingdom",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "government_incentive",
    },
    {
        "resource_type": "festivals",
        "url": "https://www.edfilmfest.org.uk/",
        "label": "Edinburgh International Film Festival",
        "territory": "United Kingdom",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "government_incentive",
    },
    {
        "resource_type": "festivals",
        "url": "https://www.sundance.org/festivals/sundance-film-festival/about/",
        "label": "Sundance Film Festival",
        "territory": "United States",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "government_incentive",
    },
    {
        "resource_type": "festivals",
        "url": "https://tribecafilm.com/",
        "label": "Tribeca Film Festival",
        "territory": "United States",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "government_incentive",
    },
    {
        "resource_type": "festivals",
        "url": "https://www.tiff.net/about",
        "label": "Toronto International Film Festival",
        "territory": "Canada",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "government_incentive",
    },
    {
        "resource_type": "festivals",
        "url": "https://viff.org/",
        "label": "Vancouver International Film Festival",
        "territory": "Canada",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "government_incentive",
    },
    {
        "resource_type": "festivals",
        "url": "https://www.festival-cannes.com/en/",
        "label": "Cannes Film Festival",
        "territory": "France",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "government_incentive",
    },
    {
        "resource_type": "festivals",
        "url": "https://www.berlinale.de/en/home.html",
        "label": "Berlin International Film Festival",
        "territory": "Germany",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "government_incentive",
    },
    {
        "resource_type": "festivals",
        "url": "https://www.sff.org.au/",
        "label": "Sydney Film Festival",
        "territory": "Australia",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "government_incentive",
    },
    {
        "resource_type": "festivals",
        "url": "https://miff.com.au/",
        "label": "Melbourne International Film Festival",
        "territory": "Australia",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "government_incentive",
    },
    {
        "resource_type": "festivals",
        "url": "https://galwayfilmfleadh.com/",
        "label": "Galway Film Fleadh",
        "territory": "Ireland",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "government_incentive",
    },
    {
        "resource_type": "festivals",
        "url": "https://www.diff.ie/",
        "label": "Dublin International Film Festival",
        "territory": "Ireland",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "government_incentive",
    },
    {
        "resource_type": "festivals",
        "url": "https://www.sansebastianfestival.com/",
        "label": "San Sebastian International Film Festival",
        "territory": "Spain",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "government_incentive",
    },
    {
        "resource_type": "festivals",
        "url": "https://sitgesfilmfestival.com/",
        "label": "Sitges Film Festival",
        "territory": "Spain",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "government_incentive",
    },
    {
        "resource_type": "festivals",
        "url": "https://www.kviff.com/en/",
        "label": "Karlovy Vary International Film Festival",
        "territory": "Czech Republic",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "government_incentive",
    },
    {
        "resource_type": "festivals",
        "url": "https://biff.hu/",
        "label": "Budapest International Film Festival",
        "territory": "Hungary",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "government_incentive",
    },
    {
        "resource_type": "festivals",
        "url": "https://vallettafilmfestival.com/",
        "label": "Valletta Film Festival",
        "territory": "Malta",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "government_incentive",
    },
    {
        "resource_type": "festivals",
        "url": "https://www.nziff.co.nz/",
        "label": "New Zealand International Film Festival",
        "territory": "New Zealand",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "government_incentive",
    },
    {
        "resource_type": "festivals",
        "url": "https://www.riff.is/",
        "label": "Reykjavik International Film Festival",
        "territory": "Iceland",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "government_incentive",
    },
    {
        "resource_type": "festivals",
        "url": "https://www.labiennale.org/en/cinema",
        "label": "Venice International Film Festival",
        "territory": "Italy",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "government_incentive",
    },
    {
        "resource_type": "festivals",
        "url": "https://www.romacinemafest.it/en/",
        "label": "Rome Film Fest",
        "territory": "Italy",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "government_incentive",
    },

    # ── Crew Costs ────────────────────────────────────────────────────────────
    # Multi-country REST API sources (structured, no AI extraction)
    # NOTE: Eurostat LCI, OECD ULC, FRED ECIWAG removed — they return index numbers
    # with day_rate=None and no role breakdown; useless for crew cost benchmarking.
    {
        "resource_type": "crew_costs",
        "url": "https://www150.statcan.gc.ca/n1/en/type/data",
        "label": "Statistics Canada Wages — National statistics, indicative, not film-specific",
        "territory": "Canada",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": True,
        "api_slug": "statcan",
        "source_authority": "national_statistics",
    },
    # USA — BLS API (structured, film-specific benchmark)
    {
        "resource_type": "crew_costs",
        "url": "https://api.bls.gov/publicAPI/v2/timeseries/data/",
        "label": "BLS Occupational Wage Survey (API)",
        "territory": "United States",
        "is_pdf": False,
        "use_bls_api": True,
        "use_rest_api": False,
        "source_authority": "film_specific",
    },
    # USA — union guild agreements
    {
        "resource_type": "crew_costs",
        "url": "https://www.sagaftra.org/production-center",
        "label": "SAG-AFTRA Theatrical Agreements 2024–26 (US) — Cast minimums by budget tier",
        "territory": "United States",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "union_agreement",
    },
    {
        "resource_type": "crew_costs",
        "url": "https://www.iatse.net/agreements",
        "label": "IATSE 2024–27 Basic & Area Standards Agreement (US) — Crew minimums",
        "territory": "United States",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "union_agreement",
    },
    {
        "resource_type": "crew_costs",
        "url": "https://www.dga.org/Contracts/",
        "label": "DGA Basic Agreement 2023–2026 (US) — Director/AD minimums",
        "territory": "United States",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "union_agreement",
    },
    {
        "resource_type": "crew_costs",
        "url": "https://www.wga.org/contracts/contracts/mba",
        "label": "WGA Minimum Basic Agreement (US) — Writer minimums",
        "territory": "United States",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "union_agreement",
    },
    # USA/UK — multi-country benchmark
    {
        "resource_type": "crew_costs",
        "url": "https://www.freelancevideocollective.com/filmmaker-resources/production-crew-rates/",
        "label": "Freelance Video Collective Crew Rates — Film industry benchmark",
        "territory": None,
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "film_specific",
    },
    # UK — union agreements + BECTU PDF rate cards
    # NOTE: CMA investigation active — UK Art Dept rates are 'recommended guidance only'
    {
        "resource_type": "crew_costs",
        "url": "https://www.pact.co.uk/resource-hub",
        "label": "PACT/Equity Cinema Film Agreement (UK) — Actor minimums (CMA note applies)",
        "territory": "United Kingdom",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "union_agreement",
    },
    {
        "resource_type": "crew_costs",
        "url": "https://www.directors.uk.com/resources",
        "label": "Directors UK Fee Tables 2024–25 (UK)",
        "territory": "United Kingdom",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "union_agreement",
    },
    {
        "resource_type": "crew_costs",
        "url": "https://bectu.org.uk/get-involved-in-the-union/ratecards/",
        "label": "BECTU Rate Cards (UK) — Film industry rate card",
        "territory": "United Kingdom",
        "is_pdf": True,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "union_agreement",
    },
    {
        "resource_type": "crew_costs",
        "url": "https://bectuartdepartment.co.uk/Rate-Card",
        "label": "BECTU Art Department Rate Card 2025-26 — Film industry rate card",
        "territory": "United Kingdom",
        "is_pdf": True,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "union_agreement",
    },
    {
        "resource_type": "crew_costs",
        "url": "https://camerabranch.org.uk/rates/",
        "label": "BECTU Camera Branch Rate Card 2025 — Film industry rate card",
        "territory": "United Kingdom",
        "is_pdf": True,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "union_agreement",
    },
    {
        "resource_type": "crew_costs",
        "url": "https://bectu.org.uk/get-involved-in-the-union/ratecards/",
        "label": "BECTU/PACT Construction Rate Card 2025-26 (UK) — Ratified CBA",
        "territory": "United Kingdom",
        "is_pdf": True,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "union_agreement",
    },
    # UK — ONS API
    {
        "resource_type": "crew_costs",
        "url": "https://api.ons.gov.uk/v1/datasets/ashe-table-7/editions/time-series/versions/2/observations",
        "label": "ONS Annual Survey of Hours and Earnings — National statistics, indicative, not film-specific",
        "territory": "United Kingdom",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": True,
        "api_slug": "ons",
        "source_authority": "national_statistics",
    },
    # Canada — union guild agreements
    {
        "resource_type": "crew_costs",
        "url": "https://www.actra.ca/agreements/ipa/",
        "label": "ACTRA IPA 2025–2027 (Canada) — Performer minimums",
        "territory": "Canada",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "union_agreement",
    },
    {
        "resource_type": "crew_costs",
        "url": "https://ubcpactra.ca/agreements/",
        "label": "UBCP/ACTRA BCMPA (Canada BC) — BC performer minimums",
        "territory": "Canada",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "union_agreement",
    },
    {
        "resource_type": "crew_costs",
        "url": "https://www.bccfu.com/agreements/",
        "label": "BCCFU 2024–2025 Crew Rates (Canada BC) — Film crew minimums",
        "territory": "Canada",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "union_agreement",
    },
    {
        "resource_type": "crew_costs",
        "url": "https://www.dgc.ca/industry/agreements/",
        "label": "DGC Standard Agreement — Directors/ADs/PMs (Canada)",
        "territory": "Canada",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "union_agreement",
    },
    # Canada — PDF rate cards
    {
        "resource_type": "crew_costs",
        "url": "https://www.iatse.com/producers/current_production_rates.aspx",
        "label": "IATSE Production Rates (Canada/US) — Film industry rate card",
        "territory": "Canada",
        "is_pdf": True,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "union_agreement",
    },
    # Australia — union agreements + statutory floor
    # NOTE: 11.5% mandatory superannuation applies on all eligible earnings
    {
        "resource_type": "crew_costs",
        "url": "https://www.meaa.org/download/mppa-rates-and-allowances-jan-1-2025/",
        "label": "MEAA MPPA Crew Rates Jan 2025 (Australia) — Ratified CBA",
        "territory": "Australia",
        "is_pdf": True,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "union_agreement",
    },
    {
        "resource_type": "crew_costs",
        "url": "https://www.meaa.org/downloads/equity-minimums-and-summaries/",
        "label": "MEAA AFFCA Cast Minimums July 2024 (Australia) — Actor minimums",
        "territory": "Australia",
        "is_pdf": True,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "union_agreement",
    },
    {
        "resource_type": "crew_costs",
        "url": "https://www.screenproducers.org.au/awards-agreements/",
        "label": "Screen Producers Australia / BRECA Award Rates — Statutory minimum floor",
        "territory": "Australia",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "legal_minimum",
    },
    {
        "resource_type": "crew_costs",
        "url": "https://www.fairwork.gov.au/pay-and-wages",
        "label": "Fair Work Commission Pay Rates (Australia) — National statistics, indicative, not film-specific",
        "territory": "Australia",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "national_statistics",
    },
    # South Africa — NEW territory
    {
        "resource_type": "crew_costs",
        "url": "https://callacrew.co.za/crew-rates",
        "label": "CallaCrew SA Crew Rates — Film industry rate card",
        "territory": "South Africa",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "film_specific",
    },
    {
        "resource_type": "crew_costs",
        "url": "https://callacrew.co.za/cpa-working-guidelines",
        "label": "CPA Working Guidelines (South Africa) — Film industry rate card",
        "territory": "South Africa",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "film_specific",
    },
    # Ireland — crew costs
    {
        "resource_type": "crew_costs",
        "url": "https://www.equity.ie/agreements/",
        "label": "Equity Ireland Minimum Agreements — Actor minimums",
        "territory": "Ireland",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "union_agreement",
    },
    {
        "resource_type": "crew_costs",
        "url": "https://www.siptu.ie/sector/film-tv/",
        "label": "SIPTU Film & TV Section Agreements (Ireland) — Crew rates",
        "territory": "Ireland",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "union_agreement",
    },
    {
        "resource_type": "crew_costs",
        "url": "https://focal.ch/prodvalue/working_conditions/ireland",
        "label": "FOCAL Working Conditions Guide — Ireland",
        "territory": "Ireland",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "film_commission_guide",
    },
    {
        "resource_type": "crew_costs",
        "url": "https://www.screenireland.ie/filming-in-ireland",
        "label": "Screen Ireland Production Guidelines — Crew benchmarks",
        "territory": "Ireland",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "film_commission_guide",
    },
    # Malta — crew costs
    {
        "resource_type": "crew_costs",
        "url": "https://pcpmalta.com/rebate.html",
        "label": "PCP Malta Production Notes — Film industry benchmark",
        "territory": "Malta",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "service_company",
    },
    {
        "resource_type": "crew_costs",
        "url": "https://focal.ch/prodvalue/working_conditions/malta",
        "label": "FOCAL Working Conditions Guide — Malta",
        "territory": "Malta",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "film_commission_guide",
    },
    {
        "resource_type": "crew_costs",
        "url": "https://www.pegasusmalta.com/production-services/",
        "label": "Pegasus Productions Malta — Local rate guidance",
        "territory": "Malta",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "service_company",
    },
    # France — legal minimums + FOCAL
    # CRITICAL: French employer social charges 42–45% — must be extracted alongside rates
    {
        "resource_type": "crew_costs",
        "url": "https://www.legifrance.gouv.fr/conv_coll/id/KALICONT000005635188/",
        "label": "Convention collective nationale — Production cinematographique (France)",
        "territory": "France",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "legal_minimum",
    },
    {
        "resource_type": "crew_costs",
        "url": "https://www.audiens.org/",
        "label": "Audiens — French intermittent social charges guide (42–45% employer)",
        "territory": "France",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "legal_minimum",
    },
    {
        "resource_type": "crew_costs",
        "url": "https://focal.ch/prodvalue/working_conditions/france",
        "label": "FOCAL Working Conditions Guide — France",
        "territory": "France",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "film_commission_guide",
    },
    # Germany — legal minimums + FOCAL
    {
        "resource_type": "crew_costs",
        "url": "https://www.verdi.de/themen/branchen/+id+film-tv",
        "label": "ver.di Film/TV Tarifvertraege (Germany) — Binding crew wage agreements",
        "territory": "Germany",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "legal_minimum",
    },
    {
        "resource_type": "crew_costs",
        "url": "https://focal.ch/prodvalue/working_conditions/germany",
        "label": "FOCAL Working Conditions Guide — Germany",
        "territory": "Germany",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "film_commission_guide",
    },
    # Spain — legal minimums + FOCAL
    # CRITICAL: Spanish employer social security ~30% — among highest in EU
    {
        "resource_type": "crew_costs",
        "url": "https://www.boe.es/buscar/act.php?id=BOE-A-2020-3544",
        "label": "Convenio colectivo audiovisual (Spain) — Binding minimum rates",
        "territory": "Spain",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "legal_minimum",
    },
    {
        "resource_type": "crew_costs",
        "url": "https://focal.ch/prodvalue/working_conditions/spain",
        "label": "FOCAL Working Conditions Guide — Spain",
        "territory": "Spain",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "film_commission_guide",
    },
    # Italy — legal minimums + FOCAL
    {
        "resource_type": "crew_costs",
        "url": "https://www.anica.it/it/contratti-collettivi/",
        "label": "ANICA CCNL Cinema/TV (Italy) — Binding collective agreement rates",
        "territory": "Italy",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "legal_minimum",
    },
    {
        "resource_type": "crew_costs",
        "url": "https://focal.ch/prodvalue/working_conditions/italy",
        "label": "FOCAL Working Conditions Guide — Italy",
        "territory": "Italy",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "film_commission_guide",
    },
    # Czech Republic — film commission + FOCAL + FITES
    {
        "resource_type": "crew_costs",
        "url": "https://www.filmcommission.cz/en/working-in-the-czech-republic/",
        "label": "Czech Film Commission Production & Crew Guide",
        "territory": "Czech Republic",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "film_commission_guide",
    },
    {
        "resource_type": "crew_costs",
        "url": "https://www.fites.cz/",
        "label": "FITES Czech Film & TV Federation — Crew union",
        "territory": "Czech Republic",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "union_agreement",
    },
    {
        "resource_type": "crew_costs",
        "url": "https://focal.ch/prodvalue/working_conditions/czech-republic",
        "label": "FOCAL Working Conditions Guide — Czech Republic",
        "territory": "Czech Republic",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "film_commission_guide",
    },
    # Hungary — FOCAL + HSA
    {
        "resource_type": "crew_costs",
        "url": "https://focal.ch/prodvalue/working_conditions/hungary",
        "label": "FOCAL Working Conditions Guide — Hungary",
        "territory": "Hungary",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "film_commission_guide",
    },
    {
        "resource_type": "crew_costs",
        "url": "https://hsa.hu/en/rates/",
        "label": "HSA Hungarian Screen Association Rate Benchmarks",
        "territory": "Hungary",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "film_commission_guide",
    },
    # South Africa — CPA guidelines + service company + industry bodies
    {
        "resource_type": "crew_costs",
        "url": "https://cpasa.tv/crew-working-guidelines/",
        "label": "CPA Crew Working Guidelines (South Africa) — Industry standard",
        "territory": "South Africa",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "film_commission_guide",
    },
    {
        "resource_type": "crew_costs",
        "url": "https://callacrew.co.za/crew-rates",
        "label": "CallaCrew SA Crew Rates — Published market rate card",
        "territory": "South Africa",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "service_company",
    },
    {
        "resource_type": "crew_costs",
        "url": "https://callacrew.co.za/cpa-working-guidelines",
        "label": "CPA Working Guidelines (South Africa) — Film industry reference",
        "territory": "South Africa",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "film_commission_guide",
    },
    {
        "resource_type": "crew_costs",
        "url": "https://www.sasfed.org/industry-data/",
        "label": "SASFED SA Screen Federation Industry Data",
        "territory": "South Africa",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "industry_survey",
    },
    {
        "resource_type": "crew_costs",
        "url": "https://www.nfvf.co.za/research/",
        "label": "NFVF Annual Industry Report (South Africa)",
        "territory": "South Africa",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "industry_survey",
    },
    # New Zealand — union/guild codes
    {
        "resource_type": "crew_costs",
        "url": "https://www.siganz.co.nz/blue-book/",
        "label": "SIGANZ Blue Book 2023 (New Zealand) — Crew code of practice",
        "territory": "New Zealand",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "union_agreement",
    },
    {
        "resource_type": "crew_costs",
        "url": "https://www.equity.org.nz/agreements/",
        "label": "SPADA/Equity NZ Individual Performance Agreement — Actor minimums",
        "territory": "New Zealand",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "union_agreement",
    },
    {
        "resource_type": "crew_costs",
        "url": "https://screenauckland.com/production-costs/",
        "label": "Screen Auckland Crew Cost Guide — NZ market benchmarks",
        "territory": "New Zealand",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "film_commission_guide",
    },
    # Iceland — actor agreement + film commission + FOCAL
    {
        "resource_type": "crew_costs",
        "url": "https://kvikmyndaframleidsla.is/",
        "label": "SIK/FIL Actor Agreement (Iceland) — Category I & II rates in ISK",
        "territory": "Iceland",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "union_agreement",
    },
    {
        "resource_type": "crew_costs",
        "url": "https://filminiceland.com/production-services/",
        "label": "Film in Iceland Production Services Guide — Crew cost benchmarks",
        "territory": "Iceland",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "film_commission_guide",
    },
    {
        "resource_type": "crew_costs",
        "url": "https://focal.ch/prodvalue/working_conditions/iceland.html",
        "label": "FOCAL Working Conditions Guide — Iceland",
        "territory": "Iceland",
        "is_pdf": False,
        "use_bls_api": False,
        "use_rest_api": False,
        "source_authority": "film_commission_guide",
    },
]

