"""grants_structured_fields

Revision ID: b2a3b4c5d6e7
Revises: b0819203a4c5
Create Date: 2026-07-10

Promotes the structured grant fields that the deterministic grants matcher
(handoff code/grants_matcher.py, PRO spec Section 07) gates and scores on
from eligibility-JSON prose lines to real columns: continent,
eligible_formats, genre_tags, budget_min/max_usd, amount_usd_approx,
grant_type, recurrence, nationality_required, co_production_required.
Populated per row (matched by title) from the canonical
grants_database.json. Additive — the eligibility lines remain.
"""
from __future__ import annotations

import json

import sqlalchemy as sa
from alembic import op

revision = "b2a3b4c5d6e7"
down_revision = "b0819203a4c5"
branch_labels = None
depends_on = None

_NEW_COLUMNS: list[tuple[str, sa.types.TypeEngine]] = [
    ("continent", sa.Text()),
    ("eligible_formats", sa.JSON()),
    ("genre_tags", sa.JSON()),
    ("budget_min_usd", sa.Float()),
    ("budget_max_usd", sa.Float()),
    ("amount_usd_approx", sa.Float()),
    ("grant_type", sa.Text()),
    ("recurrence", sa.Text()),
    ("nationality_required", sa.Boolean()),
    ("co_production_required", sa.Boolean()),
]


def upgrade() -> None:
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    if "grant_opportunities" not in inspector.get_table_names():
        return
    existing = {c["name"] for c in inspector.get_columns("grant_opportunities")}
    for name, col_type in _NEW_COLUMNS:
        if name not in existing:
            op.add_column("grant_opportunities", sa.Column(name, col_type, nullable=True))

    for row in _ROWS:
        conn.execute(
            sa.text(
                "UPDATE grant_opportunities SET "
                "continent = :continent, eligible_formats = :eligible_formats, "
                "genre_tags = :genre_tags, budget_min_usd = :budget_min_usd, "
                "budget_max_usd = :budget_max_usd, amount_usd_approx = :amount_usd_approx, "
                "grant_type = :grant_type, recurrence = :recurrence, "
                "nationality_required = :nationality_required, "
                "co_production_required = :co_production_required "
                "WHERE title = :fund_name"
            ),
            {
                **row,
                "eligible_formats": json.dumps(row["eligible_formats"]),
                "genre_tags": json.dumps(row["genre_tags"]),
            },
        )


def downgrade() -> None:
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    if "grant_opportunities" not in inspector.get_table_names():
        return
    existing = {c["name"] for c in inspector.get_columns("grant_opportunities")}
    for name, _ in _NEW_COLUMNS:
        if name in existing:
            op.drop_column("grant_opportunities", name)


_ROWS: list[dict] = json.loads(r'''
[
{"fund_name": "BFI Film Fund \u2014 Development","territory": "United Kingdom","continent": "Europe","eligible_formats": ["feature","documentary","animation"],"genre_tags": ["Drama","Thriller","Comedy","Horror","Documentary","Biopic","Period","Crime","Fantasy","Mystery","Romance","Action","Adventure","Sci-Fi","War","Family","Animation","Musical","Western","Sports"],"budget_min_usd": null,"budget_max_usd": null,"amount_usd_approx": 320000,"grant_type": "public_fund","recurrence": "rolling","nationality_required": true,"co_production_required": false},
{"fund_name": "BFI Film Fund \u2014 Production","territory": "United Kingdom","continent": "Europe","eligible_formats": ["feature","documentary","animation"],"genre_tags": ["Drama","Thriller","Comedy","Horror","Documentary","Biopic","Period","Crime","Fantasy","Mystery","Romance","Action","Adventure","Sci-Fi","War","Family","Animation","Musical"],"budget_min_usd": null,"budget_max_usd": 5000000,"amount_usd_approx": 1900000,"grant_type": "public_fund","recurrence": "rolling","nationality_required": true,"co_production_required": false},
{"fund_name": "BFI NETWORK \u2014 Short Film Fund","territory": "United Kingdom","continent": "Europe","eligible_formats": ["short","animation"],"genre_tags": ["Drama","Thriller","Comedy","Horror","Sci-Fi","Fantasy","Crime","Romance","Animation","Family"],"budget_min_usd": null,"budget_max_usd": 25000,"amount_usd_approx": 25000,"grant_type": "public_fund","recurrence": "rolling","nationality_required": true,"co_production_required": false},
{"fund_name": "Film4 Development Fund","territory": "United Kingdom","continent": "Europe","eligible_formats": ["feature"],"genre_tags": ["Drama","Thriller","Comedy","Horror","Biopic","Period","Crime","Mystery","Romance","Fantasy","Sci-Fi","War"],"budget_min_usd": null,"budget_max_usd": null,"amount_usd_approx": 255000,"grant_type": "broadcaster","recurrence": "rolling","nationality_required": false,"co_production_required": false},
{"fund_name": "Scottish Film Talent Network","territory": "United Kingdom","continent": "Europe","eligible_formats": ["short","documentary","animation"],"genre_tags": ["Drama","Thriller","Comedy","Horror","Sci-Fi","Fantasy","Crime","Documentary","Animation","Family","Romance"],"budget_min_usd": null,"budget_max_usd": 20000,"amount_usd_approx": 19000,"grant_type": "public_fund","recurrence": "rolling","nationality_required": true,"co_production_required": false},
{"fund_name": "Screen Ireland \u2014 Development Funding","territory": "Ireland","continent": "Europe","eligible_formats": ["feature","documentary","animation","tv_series"],"genre_tags": ["Drama","Thriller","Comedy","Horror","Documentary","Biopic","Period","Crime","Fantasy","Mystery","Romance","Animation","Family","Musical","Sci-Fi","War","Action","Adventure"],"budget_min_usd": null,"budget_max_usd": null,"amount_usd_approx": 220000,"grant_type": "public_fund","recurrence": "rolling","nationality_required": true,"co_production_required": false},
{"fund_name": "Screen Ireland \u2014 Sc\u00e9al Uplift (Feature Fiction)","territory": "Ireland","continent": "Europe","eligible_formats": ["feature"],"genre_tags": ["Drama","Thriller","Comedy","Horror","Biopic","Period","Crime","Fantasy","Mystery","Romance","Sci-Fi","War","Action","Adventure","Musical","Western","Sports","Family"],"budget_min_usd": null,"budget_max_usd": 3000000,"amount_usd_approx": 825000,"grant_type": "public_fund","recurrence": "annual","nationality_required": true,"co_production_required": false},
{"fund_name": "CNC Avance sur Recettes (Advance on Receipts)","territory": "France","continent": "Europe","eligible_formats": ["feature","documentary","animation"],"genre_tags": ["Drama","Thriller","Comedy","Horror","Biopic","Period","Crime","Fantasy","Mystery","Romance","Sci-Fi","War","Action","Adventure","Musical","Western","Sports","Family","Documentary","Animation"],"budget_min_usd": null,"budget_max_usd": null,"amount_usd_approx": 1320000,"grant_type": "public_fund","recurrence": "annual","nationality_required": true,"co_production_required": false},
{"fund_name": "ARTE France Cin\u00e9ma \u2014 Co-production Fund","territory": "France","continent": "Europe","eligible_formats": ["feature","documentary","animation"],"genre_tags": ["Drama","Thriller","Documentary","Biopic","Period","Crime","Fantasy","Mystery","Romance","Sci-Fi","War","Animation"],"budget_min_usd": 500000,"budget_max_usd": null,"amount_usd_approx": 550000,"grant_type": "broadcaster","recurrence": "rolling","nationality_required": false,"co_production_required": true},
{"fund_name": "German Federal Film Fund (DFFF) \u2014 DFFF I","territory": "Germany","continent": "Europe","eligible_formats": ["feature","animation","documentary"],"genre_tags": ["Drama","Thriller","Comedy","Horror","Biopic","Period","Crime","Fantasy","Mystery","Romance","Sci-Fi","War","Action","Adventure","Animation","Family","Musical","Documentary"],"budget_min_usd": 2500000,"budget_max_usd": null,"amount_usd_approx": null,"grant_type": "public_fund","recurrence": "rolling","nationality_required": false,"co_production_required": false},
{"fund_name": "German Federal Film Fund (DFFF) \u2014 DFFF II (Large Budget)","territory": "Germany","continent": "Europe","eligible_formats": ["feature","animation"],"genre_tags": ["Drama","Thriller","Action","Adventure","Sci-Fi","Fantasy","Crime","Horror","Comedy","Biopic","Period","War","Animation","Family"],"budget_min_usd": 20000000,"budget_max_usd": null,"amount_usd_approx": null,"grant_type": "public_fund","recurrence": "rolling","nationality_required": false,"co_production_required": false},
{"fund_name": "Medienboard Berlin-Brandenburg","territory": "Germany","continent": "Europe","eligible_formats": ["feature","documentary","animation","short"],"genre_tags": ["Drama","Thriller","Comedy","Horror","Documentary","Biopic","Period","Crime","Fantasy","Mystery","Animation","Family"],"budget_min_usd": null,"budget_max_usd": null,"amount_usd_approx": 1650000,"grant_type": "public_fund","recurrence": "rolling","nationality_required": false,"co_production_required": false},
{"fund_name": "ICAA \u2014 Subsidios a la Producci\u00f3n de Largometrajes","territory": "Spain","continent": "Europe","eligible_formats": ["feature","documentary","animation"],"genre_tags": ["Drama","Thriller","Comedy","Horror","Documentary","Biopic","Period","Crime","Fantasy","Mystery","Romance","Animation","Family","Musical","Action","Adventure","Sci-Fi","War","Western","Sports"],"budget_min_usd": null,"budget_max_usd": null,"amount_usd_approx": 1100000,"grant_type": "public_fund","recurrence": "annual","nationality_required": true,"co_production_required": false},
{"fund_name": "MiC \u2014 Contributi Selettivi alla Produzione","territory": "Italy","continent": "Europe","eligible_formats": ["feature","documentary","animation"],"genre_tags": ["Drama","Thriller","Comedy","Horror","Documentary","Biopic","Period","Crime","Fantasy","Mystery","Romance","Animation","Family","Musical","Action","Sci-Fi","War","Sports"],"budget_min_usd": null,"budget_max_usd": null,"amount_usd_approx": 880000,"grant_type": "public_fund","recurrence": "annual","nationality_required": true,"co_production_required": false},
{"fund_name": "Netherlands Film Fund \u2014 Feature Film Production","territory": "Netherlands","continent": "Europe","eligible_formats": ["feature","documentary","animation"],"genre_tags": ["Drama","Thriller","Comedy","Horror","Documentary","Biopic","Period","Crime","Fantasy","Mystery","Romance","Animation","Family","Sci-Fi","War","Action","Adventure"],"budget_min_usd": null,"budget_max_usd": null,"amount_usd_approx": 825000,"grant_type": "public_fund","recurrence": "rolling","nationality_required": true,"co_production_required": false},
{"fund_name": "Screen Flanders \u2014 Production Incentive + Grant","territory": "Belgium","continent": "Europe","eligible_formats": ["feature","documentary","animation","short"],"genre_tags": ["Drama","Thriller","Comedy","Horror","Documentary","Biopic","Period","Crime","Fantasy","Mystery","Animation","Family","Sci-Fi","Action"],"budget_min_usd": null,"budget_max_usd": null,"amount_usd_approx": 550000,"grant_type": "public_fund","recurrence": "rolling","nationality_required": false,"co_production_required": false},
{"fund_name": "Czech Film Fund \u2014 Production Support","territory": "Czech Republic","continent": "Europe","eligible_formats": ["feature","documentary","animation"],"genre_tags": ["Drama","Thriller","Comedy","Horror","Documentary","Biopic","Period","Crime","Fantasy","Mystery","Romance","Animation","Family","Sci-Fi","War","Action","Adventure","Musical"],"budget_min_usd": null,"budget_max_usd": null,"amount_usd_approx": 1300000,"grant_type": "public_fund","recurrence": "annual","nationality_required": true,"co_production_required": false},
{"fund_name": "National Film Institute Hungary \u2014 Production Support","territory": "Hungary","continent": "Europe","eligible_formats": ["feature","documentary","animation"],"genre_tags": ["Drama","Thriller","Comedy","Horror","Documentary","Biopic","Period","Crime","Fantasy","Mystery","Romance","Animation","Family","Sci-Fi","War","Action","Adventure"],"budget_min_usd": null,"budget_max_usd": null,"amount_usd_approx": 1400000,"grant_type": "public_fund","recurrence": "annual","nationality_required": true,"co_production_required": false},
{"fund_name": "CNC Romania \u2014 Selective Production Funding","territory": "Romania","continent": "Europe","eligible_formats": ["feature","documentary","animation","short"],"genre_tags": ["Drama","Thriller","Comedy","Horror","Documentary","Biopic","Period","Crime","Fantasy","Mystery","Romance","Animation","Family","Sci-Fi","War"],"budget_min_usd": null,"budget_max_usd": null,"amount_usd_approx": 660000,"grant_type": "public_fund","recurrence": "annual","nationality_required": true,"co_production_required": false},
{"fund_name": "ICA \u2014 Apoio \u00e0 Produ\u00e7\u00e3o de Longas-metragens","territory": "Portugal","continent": "Europe","eligible_formats": ["feature","documentary","animation"],"genre_tags": ["Drama","Thriller","Comedy","Horror","Documentary","Biopic","Period","Crime","Fantasy","Mystery","Romance","Animation","Family","Sci-Fi","War","Action","Musical"],"budget_min_usd": null,"budget_max_usd": null,"amount_usd_approx": 550000,"grant_type": "public_fund","recurrence": "annual","nationality_required": true,"co_production_required": false},
{"fund_name": "Icelandic Film Centre \u2014 Production Grant","territory": "Iceland","continent": "Europe","eligible_formats": ["feature","documentary","animation","short"],"genre_tags": ["Drama","Thriller","Comedy","Horror","Documentary","Biopic","Period","Crime","Fantasy","Mystery","Romance","Animation","Family","Sci-Fi","Adventure","War","Action"],"budget_min_usd": null,"budget_max_usd": null,"amount_usd_approx": 660000,"grant_type": "public_fund","recurrence": "annual","nationality_required": true,"co_production_required": false},
{"fund_name": "Malta Film Fund \u2014 Production Grant","territory": "Malta","continent": "Europe","eligible_formats": ["feature","documentary","animation","short"],"genre_tags": ["Drama","Thriller","Comedy","Horror","Documentary","Biopic","Period","Crime","Fantasy","Mystery","Romance","Animation","Family","Sci-Fi","Action","Adventure","War"],"budget_min_usd": null,"budget_max_usd": null,"amount_usd_approx": 550000,"grant_type": "public_fund","recurrence": "rolling","nationality_required": false,"co_production_required": false},
{"fund_name": "Film Centre Serbia \u2014 Production Support","territory": "Serbia","continent": "Europe","eligible_formats": ["feature","documentary","animation","short"],"genre_tags": ["Drama","Thriller","Comedy","Horror","Documentary","Biopic","Period","Crime","Fantasy","Mystery","Romance","Animation","Family","Sci-Fi","War","Action"],"budget_min_usd": null,"budget_max_usd": null,"amount_usd_approx": 375000,"grant_type": "public_fund","recurrence": "annual","nationality_required": true,"co_production_required": false},
{"fund_name": "Canarias Crea \u2014 Ayudas a la Producci\u00f3n Audiovisual","territory": "Canary Islands","continent": "Europe","eligible_formats": ["feature","documentary","animation","short","tv_series"],"genre_tags": ["Drama","Thriller","Comedy","Horror","Documentary","Biopic","Period","Crime","Fantasy","Mystery","Romance","Animation","Family","Action","Adventure","Sci-Fi"],"budget_min_usd": null,"budget_max_usd": null,"amount_usd_approx": 330000,"grant_type": "public_fund","recurrence": "annual","nationality_required": true,"co_production_required": false},
{"fund_name": "Creative Europe MEDIA \u2014 Development Single Project","territory": "United Kingdom","continent": "Europe","eligible_formats": ["feature","documentary","animation"],"genre_tags": ["Drama","Thriller","Comedy","Horror","Documentary","Biopic","Period","Crime","Fantasy","Mystery","Romance","Animation","Family","Sci-Fi","Action","Adventure","War","Musical","Western","Sports"],"budget_min_usd": null,"budget_max_usd": null,"amount_usd_approx": 66000,"grant_type": "public_fund","recurrence": "annual","nationality_required": true,"co_production_required": false},
{"fund_name": "Creative Europe MEDIA \u2014 Slate Development","territory": "United Kingdom","continent": "Europe","eligible_formats": ["feature","documentary","animation"],"genre_tags": ["Drama","Thriller","Comedy","Horror","Documentary","Biopic","Period","Crime","Fantasy","Mystery","Romance","Animation","Family","Sci-Fi","Action","Adventure","War","Musical","Western","Sports"],"budget_min_usd": null,"budget_max_usd": null,"amount_usd_approx": 220000,"grant_type": "public_fund","recurrence": "annual","nationality_required": true,"co_production_required": false},
{"fund_name": "Eurimages \u2014 Co-Production Fund","territory": "France","continent": "Europe","eligible_formats": ["feature","documentary","animation"],"genre_tags": ["Drama","Thriller","Comedy","Horror","Documentary","Biopic","Period","Crime","Fantasy","Mystery","Romance","Animation","Family","Sci-Fi","War","Action","Adventure","Musical","Western","Sports"],"budget_min_usd": 500000,"budget_max_usd": null,"amount_usd_approx": 1650000,"grant_type": "co_production","recurrence": "rolling","nationality_required": true,"co_production_required": true},
{"fund_name": "Canada Media Fund \u2014 Development \u2014 English Market","territory": "Ontario","continent": "Americas","eligible_formats": ["feature","tv_series","animation","documentary"],"genre_tags": ["Drama","Thriller","Comedy","Horror","Sci-Fi","Fantasy","Crime","Mystery","Romance","Action","Adventure","Family","Animation","Biopic","Period","War","Documentary","Musical","Sports"],"budget_min_usd": null,"budget_max_usd": null,"amount_usd_approx": 258000,"grant_type": "public_fund","recurrence": "annual","nationality_required": true,"co_production_required": false},
{"fund_name": "Telefilm Canada \u2014 Development \u2014 Low Budget Independent","territory": "Ontario","continent": "Americas","eligible_formats": ["feature","documentary"],"genre_tags": ["Drama","Thriller","Comedy","Horror","Sci-Fi","Fantasy","Crime","Mystery","Romance","Action","Adventure","Family","Biopic","Period","War","Documentary"],"budget_min_usd": null,"budget_max_usd": 1500000,"amount_usd_approx": 92000,"grant_type": "public_fund","recurrence": "rolling","nationality_required": true,"co_production_required": false},
{"fund_name": "Ontario Creates \u2014 Film Fund","territory": "Ontario","continent": "Americas","eligible_formats": ["feature","animation","documentary"],"genre_tags": ["Drama","Thriller","Comedy","Horror","Sci-Fi","Fantasy","Crime","Mystery","Romance","Action","Adventure","Family","Animation","Biopic","Period","Documentary","Musical"],"budget_min_usd": null,"budget_max_usd": null,"amount_usd_approx": 370000,"grant_type": "public_fund","recurrence": "annual","nationality_required": true,"co_production_required": false},
{"fund_name": "BC Arts Council \u2014 Creative BC Film Fund","territory": "British Columbia","continent": "Americas","eligible_formats": ["feature","documentary","animation","short"],"genre_tags": ["Drama","Thriller","Comedy","Horror","Sci-Fi","Fantasy","Crime","Mystery","Romance","Action","Adventure","Family","Animation","Biopic","Period","Documentary"],"budget_min_usd": null,"budget_max_usd": null,"amount_usd_approx": 221000,"grant_type": "public_fund","recurrence": "annual","nationality_required": true,"co_production_required": false},
{"fund_name": "Sundance Institute \u2014 Feature Film Program","territory": "New York","continent": "Americas","eligible_formats": ["feature","documentary","animation"],"genre_tags": ["Drama","Thriller","Comedy","Horror","Sci-Fi","Fantasy","Crime","Mystery","Romance","Action","Adventure","Biopic","Period","War","Documentary","Animation","Family","Musical","Sports"],"budget_min_usd": null,"budget_max_usd": 1500000,"amount_usd_approx": 30000,"grant_type": "foundation","recurrence": "annual","nationality_required": false,"co_production_required": false},
{"fund_name": "IDA Enterprise Documentary Fund","territory": "California","continent": "Americas","eligible_formats": ["documentary"],"genre_tags": ["Documentary"],"budget_min_usd": null,"budget_max_usd": null,"amount_usd_approx": 25000,"grant_type": "foundation","recurrence": "rolling","nationality_required": false,"co_production_required": false},
{"fund_name": "Sundance Institute \u2014 Documentary Film Program","territory": "California","continent": "Americas","eligible_formats": ["documentary"],"genre_tags": ["Documentary"],"budget_min_usd": null,"budget_max_usd": null,"amount_usd_approx": 50000,"grant_type": "foundation","recurrence": "annual","nationality_required": false,"co_production_required": false},
{"fund_name": "SFFILM \u2014 Rainin Grant","territory": "California","continent": "Americas","eligible_formats": ["feature","documentary"],"genre_tags": ["Drama","Documentary","Biopic","Crime","Mystery","Thriller"],"budget_min_usd": null,"budget_max_usd": null,"amount_usd_approx": 30000,"grant_type": "foundation","recurrence": "annual","nationality_required": false,"co_production_required": false},
{"fund_name": "ANCINE \u2014 FSA Produ\u00e7\u00e3o Independente","territory": "Brazil","continent": "Americas","eligible_formats": ["feature","documentary","animation","tv_series"],"genre_tags": ["Drama","Thriller","Comedy","Horror","Documentary","Biopic","Period","Crime","Fantasy","Mystery","Romance","Animation","Family","Sci-Fi","War","Action","Adventure","Musical","Sports"],"budget_min_usd": null,"budget_max_usd": null,"amount_usd_approx": 600000,"grant_type": "public_fund","recurrence": "annual","nationality_required": true,"co_production_required": false},
{"fund_name": "IMCINE \u2014 FOPROCINE","territory": "Mexico","continent": "Americas","eligible_formats": ["feature","documentary","animation"],"genre_tags": ["Drama","Thriller","Comedy","Horror","Documentary","Biopic","Period","Crime","Fantasy","Mystery","Romance","Animation","Family","Sci-Fi","War","Action","Adventure","Musical"],"budget_min_usd": null,"budget_max_usd": null,"amount_usd_approx": 580000,"grant_type": "public_fund","recurrence": "annual","nationality_required": true,"co_production_required": false},
{"fund_name": "National Film and Video Foundation \u2014 Production Funding","territory": "Western Cape","continent": "Africa","eligible_formats": ["feature","documentary","animation","short","tv_series"],"genre_tags": ["Drama","Thriller","Comedy","Horror","Documentary","Biopic","Period","Crime","Fantasy","Mystery","Romance","Animation","Family","Sci-Fi","War","Action","Adventure","Musical","Sports"],"budget_min_usd": null,"budget_max_usd": null,"amount_usd_approx": 165000,"grant_type": "public_fund","recurrence": "annual","nationality_required": true,"co_production_required": false},
{"fund_name": "National Film and Video Foundation \u2014 Co-Production Fund","territory": "Gauteng","continent": "Africa","eligible_formats": ["feature","documentary","animation"],"genre_tags": ["Drama","Thriller","Documentary","Biopic","Period","Crime","Mystery","Romance","Animation","Family","Action","Adventure","War"],"budget_min_usd": null,"budget_max_usd": null,"amount_usd_approx": 110000,"grant_type": "co_production","recurrence": "annual","nationality_required": true,"co_production_required": true},
{"fund_name": "Durban FilmMart \u2014 Development Finance Forum","territory": "KwaZulu-Natal","continent": "Africa","eligible_formats": ["feature","documentary","tv_series"],"genre_tags": ["Drama","Thriller","Documentary","Biopic","Crime","Mystery","Romance","Family","Action","Adventure","War","Comedy","Sci-Fi"],"budget_min_usd": null,"budget_max_usd": null,"amount_usd_approx": null,"grant_type": "foundation","recurrence": "annual","nationality_required": false,"co_production_required": false},
{"fund_name": "Africa International Film Festival (AFRIFF) \u2014 Short Film Fund","territory": "Nigeria","continent": "Africa","eligible_formats": ["short","documentary"],"genre_tags": ["Drama","Thriller","Comedy","Horror","Sci-Fi","Fantasy","Crime","Mystery","Romance","Action","Adventure","Documentary","Family","Biopic","Period"],"budget_min_usd": null,"budget_max_usd": 15000,"amount_usd_approx": 10000,"grant_type": "foundation","recurrence": "annual","nationality_required": false,"co_production_required": false},
{"fund_name": "Centre Cin\u00e9matographique Marocain \u2014 Fonds d'Aide","territory": "Morocco","continent": "Africa","eligible_formats": ["feature","documentary","animation","short"],"genre_tags": ["Drama","Thriller","Comedy","Horror","Documentary","Biopic","Period","Crime","Fantasy","Mystery","Romance","Family","Sci-Fi","War","Action","Adventure"],"budget_min_usd": null,"budget_max_usd": null,"amount_usd_approx": 500000,"grant_type": "public_fund","recurrence": "annual","nationality_required": true,"co_production_required": false},
{"fund_name": "Screen Australia \u2014 Story Development","territory": "Australia","continent": "Asia-Pacific","eligible_formats": ["feature","documentary","animation","tv_series"],"genre_tags": ["Drama","Thriller","Comedy","Horror","Sci-Fi","Fantasy","Crime","Mystery","Romance","Action","Adventure","Documentary","Animation","Family","Biopic","Period","War","Musical","Sports"],"budget_min_usd": null,"budget_max_usd": null,"amount_usd_approx": 33000,"grant_type": "public_fund","recurrence": "rolling","nationality_required": true,"co_production_required": false},
{"fund_name": "NZ Film Commission \u2014 Development Funding","territory": "New Zealand","continent": "Asia-Pacific","eligible_formats": ["feature","documentary","animation","short"],"genre_tags": ["Drama","Thriller","Comedy","Horror","Sci-Fi","Fantasy","Crime","Mystery","Romance","Action","Adventure","Documentary","Animation","Family","Biopic","Period","War","Musical","Sports"],"budget_min_usd": null,"budget_max_usd": null,"amount_usd_approx": 30000,"grant_type": "public_fund","recurrence": "rolling","nationality_required": true,"co_production_required": false},
{"fund_name": "Japan \u2014 Agency for Cultural Affairs \u2014 Creative Industries Fund","territory": "Japan","continent": "Asia-Pacific","eligible_formats": ["feature","animation","documentary","short"],"genre_tags": ["Drama","Thriller","Comedy","Horror","Sci-Fi","Fantasy","Crime","Mystery","Romance","Animation","Family","Documentary","Biopic","Period","Musical","Action","Adventure"],"budget_min_usd": null,"budget_max_usd": null,"amount_usd_approx": 340000,"grant_type": "public_fund","recurrence": "annual","nationality_required": true,"co_production_required": false},
{"fund_name": "Korean Film Council (KOFIC) \u2014 International Co-Production Fund","territory": "South Korea","continent": "Asia-Pacific","eligible_formats": ["feature","animation","documentary"],"genre_tags": ["Drama","Thriller","Comedy","Horror","Sci-Fi","Fantasy","Crime","Mystery","Romance","Action","Adventure","Family","Animation","Documentary","Biopic","Period","War"],"budget_min_usd": null,"budget_max_usd": null,"amount_usd_approx": 370000,"grant_type": "co_production","recurrence": "annual","nationality_required": true,"co_production_required": true},
{"fund_name": "IMDA \u2014 Singapore Media Fund","territory": "Singapore","continent": "Asia-Pacific","eligible_formats": ["feature","tv_series","animation","documentary","short"],"genre_tags": ["Drama","Thriller","Comedy","Horror","Sci-Fi","Fantasy","Crime","Mystery","Romance","Action","Adventure","Family","Animation","Documentary","Biopic","Period","Musical"],"budget_min_usd": null,"budget_max_usd": null,"amount_usd_approx": 375000,"grant_type": "public_fund","recurrence": "rolling","nationality_required": false,"co_production_required": false},
{"fund_name": "NFDC \u2014 Film Bazaar Co-Production Market","territory": "India","continent": "Asia-Pacific","eligible_formats": ["feature","documentary","animation"],"genre_tags": ["Drama","Thriller","Comedy","Horror","Sci-Fi","Fantasy","Crime","Mystery","Romance","Action","Adventure","Family","Animation","Documentary","Biopic","Period","Musical","War","Sports"],"budget_min_usd": null,"budget_max_usd": null,"amount_usd_approx": null,"grant_type": "public_fund","recurrence": "annual","nationality_required": false,"co_production_required": false},
{"fund_name": "Ibermedia \u2014 Co-Production and Development Fund","territory": "Global","continent": "Global","eligible_formats": ["feature","documentary","animation","tv_series"],"genre_tags": ["Drama","Thriller","Comedy","Horror","Sci-Fi","Fantasy","Crime","Mystery","Romance","Action","Adventure","Family","Animation","Documentary","Biopic","Period","Musical","War","Western","Sports"],"budget_min_usd": null,"budget_max_usd": null,"amount_usd_approx": 400000,"grant_type": "co_production","recurrence": "annual","nationality_required": true,"co_production_required": true},
{"fund_name": "Catapult Film Fund \u2014 Development","territory": "Global","continent": "Global","eligible_formats": ["documentary"],"genre_tags": ["Documentary"],"budget_min_usd": null,"budget_max_usd": null,"amount_usd_approx": 25000,"grant_type": "foundation","recurrence": "rolling","nationality_required": false,"co_production_required": false},
{"fund_name": "Sundance Institute \u2014 Women at Sundance \u2014 Adobe Fellows","territory": "Global","continent": "Global","eligible_formats": ["feature","documentary","animation"],"genre_tags": ["Drama","Documentary","Thriller","Comedy","Horror","Sci-Fi","Fantasy","Crime","Mystery","Romance","Action","Adventure","Family","Animation","Biopic","Period","Musical","War","Sports"],"budget_min_usd": null,"budget_max_usd": null,"amount_usd_approx": 10000,"grant_type": "foundation","recurrence": "annual","nationality_required": false,"co_production_required": false},
{"fund_name": "Tribeca \u2014 Chanel Through Her Lens","territory": "Global","continent": "Global","eligible_formats": ["feature","documentary","short"],"genre_tags": ["Drama","Documentary","Thriller","Comedy","Biopic","Crime","Mystery","Romance","Family","Period","Musical","Sci-Fi","Horror","Fantasy","War","Action","Sports"],"budget_min_usd": null,"budget_max_usd": null,"amount_usd_approx": 75000,"grant_type": "foundation","recurrence": "annual","nationality_required": false,"co_production_required": false},
{"fund_name": "IDFA Bertha Fund","territory": "Global","continent": "Global","eligible_formats": ["documentary"],"genre_tags": ["Documentary"],"budget_min_usd": null,"budget_max_usd": null,"amount_usd_approx": 55000,"grant_type": "foundation","recurrence": "annual","nationality_required": false,"co_production_required": false},
{"fund_name": "DOC/NYC \u2014 Fund for Inclusion","territory": "Global","continent": "Global","eligible_formats": ["documentary"],"genre_tags": ["Documentary"],"budget_min_usd": null,"budget_max_usd": null,"amount_usd_approx": 25000,"grant_type": "foundation","recurrence": "annual","nationality_required": false,"co_production_required": false},
{"fund_name": "BBC Film \u2014 Development and Co-Production","territory": "United Kingdom","continent": "Europe","eligible_formats": ["feature"],"genre_tags": ["Drama","Thriller","Comedy","Horror","Biopic","Period","Crime","Mystery","Romance","Fantasy","Sci-Fi","War","Action","Adventure","Musical","Family"],"budget_min_usd": 500000,"budget_max_usd": null,"amount_usd_approx": 1900000,"grant_type": "broadcaster","recurrence": "rolling","nationality_required": false,"co_production_required": true},
{"fund_name": "Screen Wales \u2014 Production Funding","territory": "United Kingdom","continent": "Europe","eligible_formats": ["feature","documentary","animation","tv_series"],"genre_tags": ["Drama","Thriller","Comedy","Horror","Documentary","Biopic","Period","Crime","Fantasy","Mystery","Romance","Animation","Family","Sci-Fi","War","Action","Adventure","Musical"],"budget_min_usd": null,"budget_max_usd": null,"amount_usd_approx": 1270000,"grant_type": "public_fund","recurrence": "rolling","nationality_required": true,"co_production_required": false},
{"fund_name": "Northern Ireland Screen \u2014 Development and Production","territory": "United Kingdom","continent": "Europe","eligible_formats": ["feature","documentary","animation","tv_series","short"],"genre_tags": ["Drama","Thriller","Comedy","Horror","Documentary","Biopic","Period","Crime","Fantasy","Mystery","Romance","Animation","Family","Sci-Fi","War","Action","Adventure"],"budget_min_usd": null,"budget_max_usd": null,"amount_usd_approx": 635000,"grant_type": "public_fund","recurrence": "rolling","nationality_required": true,"co_production_required": false},
{"fund_name": "Creative England \u2014 iFeatures","territory": "United Kingdom","continent": "Europe","eligible_formats": ["feature"],"genre_tags": ["Drama","Thriller","Comedy","Horror","Crime","Mystery","Romance","Fantasy","Sci-Fi","Period","Biopic","War","Action","Adventure","Family"],"budget_min_usd": null,"budget_max_usd": 500000,"amount_usd_approx": 318000,"grant_type": "public_fund","recurrence": "annual","nationality_required": true,"co_production_required": false},
{"fund_name": "BFI Doc Society Fund \u2014 Short Documentary","territory": "United Kingdom","continent": "Europe","eligible_formats": ["short","documentary"],"genre_tags": ["Documentary"],"budget_min_usd": null,"budget_max_usd": 20000,"amount_usd_approx": 19000,"grant_type": "public_fund","recurrence": "rolling","nationality_required": true,"co_production_required": false},
{"fund_name": "BAFTA \u2014 Rocliffe New Writing Competition","territory": "United Kingdom","continent": "Europe","eligible_formats": ["feature","tv_series","short"],"genre_tags": ["Drama","Thriller","Comedy","Horror","Crime","Mystery","Romance","Fantasy","Sci-Fi","Period","Biopic","War","Action","Adventure","Family","Animation","Musical"],"budget_min_usd": null,"budget_max_usd": null,"amount_usd_approx": 5000,"grant_type": "foundation","recurrence": "annual","nationality_required": true,"co_production_required": false},
{"fund_name": "Film London \u2014 Production Finance Market","territory": "United Kingdom","continent": "Europe","eligible_formats": ["feature","documentary"],"genre_tags": ["Drama","Thriller","Comedy","Horror","Documentary","Biopic","Period","Crime","Fantasy","Mystery","Romance","Animation","Family","Sci-Fi","War","Action","Adventure"],"budget_min_usd": 500000,"budget_max_usd": null,"amount_usd_approx": null,"grant_type": "public_fund","recurrence": "annual","nationality_required": false,"co_production_required": false},
{"fund_name": "Screen Ireland \u2014 Short Film Scheme","territory": "Ireland","continent": "Europe","eligible_formats": ["short","animation"],"genre_tags": ["Drama","Thriller","Comedy","Horror","Sci-Fi","Fantasy","Crime","Mystery","Romance","Animation","Family","Documentary","Biopic","Period","Musical","Action","Adventure","War"],"budget_min_usd": null,"budget_max_usd": 35000,"amount_usd_approx": 33000,"grant_type": "public_fund","recurrence": "annual","nationality_required": true,"co_production_required": false},
{"fund_name": "RTE \u2014 Documentary on One Development Fund","territory": "Ireland","continent": "Europe","eligible_formats": ["documentary"],"genre_tags": ["Documentary"],"budget_min_usd": null,"budget_max_usd": null,"amount_usd_approx": 11000,"grant_type": "broadcaster","recurrence": "rolling","nationality_required": true,"co_production_required": false},
{"fund_name": "CNC \u2014 Aide au D\u00e9veloppement Documentaire","territory": "France","continent": "Europe","eligible_formats": ["documentary"],"genre_tags": ["Documentary"],"budget_min_usd": null,"budget_max_usd": null,"amount_usd_approx": 66000,"grant_type": "public_fund","recurrence": "rolling","nationality_required": true,"co_production_required": false},
{"fund_name": "CNC \u2014 Aide aux Cin\u00e9mas du Monde","territory": "France","continent": "Europe","eligible_formats": ["feature","documentary","animation"],"genre_tags": ["Drama","Thriller","Comedy","Horror","Documentary","Biopic","Period","Crime","Fantasy","Mystery","Romance","Animation","Family","Sci-Fi","War","Action","Adventure"],"budget_min_usd": null,"budget_max_usd": null,"amount_usd_approx": 198000,"grant_type": "co_production","recurrence": "annual","nationality_required": false,"co_production_required": true},
{"fund_name": "FFA \u2014 Drehbuchf\u00f6rderung (Script Development)","territory": "Germany","continent": "Europe","eligible_formats": ["feature","animation"],"genre_tags": ["Drama","Thriller","Comedy","Horror","Biopic","Period","Crime","Fantasy","Mystery","Romance","Sci-Fi","War","Action","Adventure","Family","Animation","Musical"],"budget_min_usd": null,"budget_max_usd": null,"amount_usd_approx": 55000,"grant_type": "public_fund","recurrence": "rolling","nationality_required": true,"co_production_required": false},
{"fund_name": "ZDF / ARTE \u2014 Documentary Co-Production Fund","territory": "Germany","continent": "Europe","eligible_formats": ["documentary"],"genre_tags": ["Documentary"],"budget_min_usd": null,"budget_max_usd": null,"amount_usd_approx": 250000,"grant_type": "broadcaster","recurrence": "rolling","nationality_required": false,"co_production_required": true},
{"fund_name": "Hamburg Film Fund (HFF / MFG / FFF Bayern)","territory": "Germany","continent": "Europe","eligible_formats": ["feature","documentary","animation","short"],"genre_tags": ["Drama","Thriller","Comedy","Horror","Documentary","Biopic","Period","Crime","Fantasy","Mystery","Animation","Family","Sci-Fi","War","Action","Romance"],"budget_min_usd": null,"budget_max_usd": null,"amount_usd_approx": 550000,"grant_type": "public_fund","recurrence": "rolling","nationality_required": false,"co_production_required": false},
{"fund_name": "ICAA \u2014 Ayudas al Desarrollo de Proyectos","territory": "Spain","continent": "Europe","eligible_formats": ["feature","documentary","animation"],"genre_tags": ["Drama","Thriller","Comedy","Horror","Documentary","Biopic","Period","Crime","Fantasy","Mystery","Romance","Animation","Family","Sci-Fi","War","Action","Adventure","Musical"],"budget_min_usd": null,"budget_max_usd": null,"amount_usd_approx": 88000,"grant_type": "public_fund","recurrence": "annual","nationality_required": true,"co_production_required": false},
{"fund_name": "ICEC \u2014 Ajuts a la Producci\u00f3 Cinematogr\u00e0fica (Catalonia)","territory": "Spain","continent": "Europe","eligible_formats": ["feature","documentary","animation","short"],"genre_tags": ["Drama","Thriller","Comedy","Horror","Documentary","Biopic","Period","Crime","Fantasy","Mystery","Romance","Animation","Family","Sci-Fi","Action","War"],"budget_min_usd": null,"budget_max_usd": null,"amount_usd_approx": 330000,"grant_type": "public_fund","recurrence": "annual","nationality_required": true,"co_production_required": false},
{"fund_name": "MiC \u2014 Contributi allo Sviluppo (Development)","territory": "Italy","continent": "Europe","eligible_formats": ["feature","documentary","animation"],"genre_tags": ["Drama","Thriller","Comedy","Horror","Documentary","Biopic","Period","Crime","Fantasy","Mystery","Romance","Animation","Family","Sci-Fi","War","Action","Musical"],"budget_min_usd": null,"budget_max_usd": null,"amount_usd_approx": 110000,"grant_type": "public_fund","recurrence": "annual","nationality_required": true,"co_production_required": false},
{"fund_name": "RAI Cinema \u2014 Co-Production Fund","territory": "Italy","continent": "Europe","eligible_formats": ["feature"],"genre_tags": ["Drama","Thriller","Comedy","Biopic","Period","Crime","Mystery","Romance","Fantasy","Sci-Fi","War","Action","Adventure","Musical","Family"],"budget_min_usd": 500000,"budget_max_usd": null,"amount_usd_approx": 400000,"grant_type": "broadcaster","recurrence": "rolling","nationality_required": false,"co_production_required": true},
{"fund_name": "Netherlands Film Fund \u2014 International Co-Production","territory": "Netherlands","continent": "Europe","eligible_formats": ["feature","documentary","animation"],"genre_tags": ["Drama","Thriller","Comedy","Horror","Documentary","Biopic","Period","Crime","Fantasy","Mystery","Romance","Animation","Family","Sci-Fi","War","Action","Adventure"],"budget_min_usd": null,"budget_max_usd": null,"amount_usd_approx": 550000,"grant_type": "co_production","recurrence": "rolling","nationality_required": false,"co_production_required": true},
{"fund_name": "Czech Film Fund \u2014 Script Development","territory": "Czech Republic","continent": "Europe","eligible_formats": ["feature","documentary","animation"],"genre_tags": ["Drama","Thriller","Comedy","Horror","Documentary","Biopic","Period","Crime","Fantasy","Mystery","Romance","Animation","Family","Sci-Fi","War","Action"],"budget_min_usd": null,"budget_max_usd": null,"amount_usd_approx": 35000,"grant_type": "public_fund","recurrence": "annual","nationality_required": true,"co_production_required": false},
{"fund_name": "NFI Hungary \u2014 Short Film Fund","territory": "Hungary","continent": "Europe","eligible_formats": ["short","animation"],"genre_tags": ["Drama","Thriller","Comedy","Horror","Sci-Fi","Fantasy","Crime","Mystery","Romance","Animation","Family","Documentary","Biopic","Period","Action","Musical","War"],"budget_min_usd": null,"budget_max_usd": 150000,"amount_usd_approx": 143000,"grant_type": "public_fund","recurrence": "annual","nationality_required": true,"co_production_required": false},
{"fund_name": "CNC Romania \u2014 Development and Short Film","territory": "Romania","continent": "Europe","eligible_formats": ["short","documentary","animation"],"genre_tags": ["Drama","Thriller","Comedy","Horror","Sci-Fi","Fantasy","Crime","Mystery","Romance","Animation","Family","Documentary","Biopic","Period","War","Action"],"budget_min_usd": null,"budget_max_usd": 110000,"amount_usd_approx": 110000,"grant_type": "public_fund","recurrence": "annual","nationality_required": true,"co_production_required": false},
{"fund_name": "Wallimage \u2014 Production Fund (Wallonia)","territory": "Belgium","continent": "Europe","eligible_formats": ["feature","documentary","animation","tv_series"],"genre_tags": ["Drama","Thriller","Comedy","Horror","Documentary","Biopic","Period","Crime","Fantasy","Mystery","Animation","Family","Sci-Fi","War","Action","Romance"],"budget_min_usd": null,"budget_max_usd": null,"amount_usd_approx": 660000,"grant_type": "public_fund","recurrence": "rolling","nationality_required": false,"co_production_required": false},
{"fund_name": "Alberta Foundation for the Arts \u2014 Film and Video Production","territory": "Alberta","continent": "Americas","eligible_formats": ["feature","documentary","animation","short"],"genre_tags": ["Drama","Thriller","Comedy","Horror","Documentary","Biopic","Period","Crime","Fantasy","Mystery","Romance","Animation","Family","Sci-Fi","War","Action","Adventure","Musical","Sports"],"budget_min_usd": null,"budget_max_usd": null,"amount_usd_approx": 22000,"grant_type": "public_fund","recurrence": "annual","nationality_required": true,"co_production_required": false},
{"fund_name": "SODEC \u2014 Programme d'aide \u00e0 la production (Quebec)","territory": "Quebec","continent": "Americas","eligible_formats": ["feature","documentary","animation","tv_series"],"genre_tags": ["Drama","Thriller","Comedy","Horror","Documentary","Biopic","Period","Crime","Fantasy","Mystery","Romance","Animation","Family","Sci-Fi","War","Action","Adventure","Musical","Sports"],"budget_min_usd": null,"budget_max_usd": null,"amount_usd_approx": 295000,"grant_type": "public_fund","recurrence": "rolling","nationality_required": true,"co_production_required": false},
{"fund_name": "SODEC \u2014 Programme d'aide au d\u00e9veloppement (Quebec)","territory": "Quebec","continent": "Americas","eligible_formats": ["feature","documentary","animation"],"genre_tags": ["Drama","Thriller","Comedy","Horror","Documentary","Biopic","Period","Crime","Fantasy","Mystery","Romance","Animation","Family","Sci-Fi","War","Action","Adventure","Musical"],"budget_min_usd": null,"budget_max_usd": null,"amount_usd_approx": 37000,"grant_type": "public_fund","recurrence": "rolling","nationality_required": true,"co_production_required": false},
{"fund_name": "Georgia Film Office \u2014 Film Georgia Fund","territory": "Georgia (USA)","continent": "Americas","eligible_formats": ["feature","documentary","short"],"genre_tags": ["Drama","Thriller","Comedy","Horror","Sci-Fi","Fantasy","Crime","Mystery","Romance","Action","Adventure","Documentary","Family","Biopic","Period","War","Musical","Sports"],"budget_min_usd": null,"budget_max_usd": 500000,"amount_usd_approx": 20000,"grant_type": "public_fund","recurrence": "annual","nationality_required": true,"co_production_required": false},
{"fund_name": "Louisiana Division of the Arts \u2014 Artist Fellowship","territory": "Louisiana","continent": "Americas","eligible_formats": ["feature","documentary","short"],"genre_tags": ["Drama","Thriller","Comedy","Horror","Sci-Fi","Fantasy","Crime","Mystery","Romance","Action","Adventure","Documentary","Family","Biopic","Period","War","Musical"],"budget_min_usd": null,"budget_max_usd": null,"amount_usd_approx": 10000,"grant_type": "public_fund","recurrence": "annual","nationality_required": true,"co_production_required": false},
{"fund_name": "Illinois Arts Council Agency \u2014 Individual Artists Support","territory": "Illinois","continent": "Americas","eligible_formats": ["feature","documentary","short","animation"],"genre_tags": ["Drama","Thriller","Comedy","Horror","Sci-Fi","Fantasy","Crime","Mystery","Romance","Action","Adventure","Documentary","Family","Biopic","Period","War","Musical","Animation"],"budget_min_usd": null,"budget_max_usd": null,"amount_usd_approx": 7000,"grant_type": "public_fund","recurrence": "annual","nationality_required": true,"co_production_required": false},
{"fund_name": "New Mexico Arts \u2014 Film and Arts Funding","territory": "New Mexico","continent": "Americas","eligible_formats": ["feature","documentary","short"],"genre_tags": ["Drama","Thriller","Comedy","Horror","Sci-Fi","Fantasy","Crime","Mystery","Romance","Action","Adventure","Documentary","Family","Biopic","Period","War","Western","Musical"],"budget_min_usd": null,"budget_max_usd": null,"amount_usd_approx": 10000,"grant_type": "public_fund","recurrence": "annual","nationality_required": true,"co_production_required": false},
{"fund_name": "NYSCA \u2014 Film, Media, and New Technology Grants","territory": "New York","continent": "Americas","eligible_formats": ["feature","documentary","short","animation","tv_series"],"genre_tags": ["Drama","Thriller","Comedy","Horror","Sci-Fi","Fantasy","Crime","Mystery","Romance","Action","Adventure","Documentary","Family","Biopic","Period","War","Musical","Animation","Sports"],"budget_min_usd": null,"budget_max_usd": null,"amount_usd_approx": 100000,"grant_type": "public_fund","recurrence": "annual","nationality_required": true,"co_production_required": false},
{"fund_name": "Tribeca Film Institute \u2014 Reframe Grants","territory": "New York","continent": "Americas","eligible_formats": ["feature","documentary"],"genre_tags": ["Drama","Documentary","Thriller","Crime","Biopic","Family","Romance","Period","Sci-Fi","Mystery","Comedy","Horror","War","Action","Adventure","Musical","Sports","Fantasy"],"budget_min_usd": null,"budget_max_usd": 2000000,"amount_usd_approx": 50000,"grant_type": "foundation","recurrence": "annual","nationality_required": false,"co_production_required": false},
{"fund_name": "Chicken & Egg Pictures \u2014 Hatching Fund","territory": "Global","continent": "Global","eligible_formats": ["documentary"],"genre_tags": ["Documentary"],"budget_min_usd": null,"budget_max_usd": null,"amount_usd_approx": 30000,"grant_type": "foundation","recurrence": "annual","nationality_required": false,"co_production_required": false},
{"fund_name": "Points North Institute \u2014 Fellowship","territory": "Global","continent": "Global","eligible_formats": ["documentary"],"genre_tags": ["Documentary"],"budget_min_usd": null,"budget_max_usd": null,"amount_usd_approx": 25000,"grant_type": "foundation","recurrence": "annual","nationality_required": false,"co_production_required": false},
{"fund_name": "California Arts Council \u2014 Artists in Communities","territory": "California","continent": "Americas","eligible_formats": ["feature","documentary","short","animation"],"genre_tags": ["Drama","Documentary","Thriller","Crime","Biopic","Family","Romance","Period","Sci-Fi","Mystery","Comedy","Horror","War","Action","Adventure","Musical","Sports","Fantasy","Animation"],"budget_min_usd": null,"budget_max_usd": null,"amount_usd_approx": 50000,"grant_type": "public_fund","recurrence": "annual","nationality_required": true,"co_production_required": false},
{"fund_name": "Telefilm Canada \u2014 Talent to Watch (Short Film)","territory": "Ontario","continent": "Americas","eligible_formats": ["short","animation"],"genre_tags": ["Drama","Thriller","Comedy","Horror","Sci-Fi","Fantasy","Crime","Mystery","Romance","Action","Adventure","Family","Animation","Documentary","Biopic","Period","War","Musical","Sports","Western"],"budget_min_usd": null,"budget_max_usd": 125000,"amount_usd_approx": 92000,"grant_type": "public_fund","recurrence": "annual","nationality_required": true,"co_production_required": false},
{"fund_name": "Harold Greenberg Fund \u2014 Development","territory": "British Columbia","continent": "Americas","eligible_formats": ["feature","tv_series"],"genre_tags": ["Drama","Thriller","Comedy","Horror","Sci-Fi","Fantasy","Crime","Mystery","Romance","Action","Adventure","Family","Animation","Biopic","Period","War","Musical","Sports"],"budget_min_usd": null,"budget_max_usd": null,"amount_usd_approx": 55000,"grant_type": "foundation","recurrence": "rolling","nationality_required": true,"co_production_required": false},
{"fund_name": "Realness Institute \u2014 African Feature Film Development","territory": "Western Cape","continent": "Africa","eligible_formats": ["feature","documentary"],"genre_tags": ["Drama","Thriller","Comedy","Documentary","Biopic","Crime","Mystery","Romance","Family","Period","Action","Adventure","Sci-Fi","Horror","Fantasy","War","Musical"],"budget_min_usd": null,"budget_max_usd": null,"amount_usd_approx": 20000,"grant_type": "foundation","recurrence": "annual","nationality_required": false,"co_production_required": false},
{"fund_name": "African Development Bank \u2014 Fund for African Private Sector Assistance (FAPA) Cultural Industry","territory": "Nigeria","continent": "Africa","eligible_formats": ["feature","tv_series","documentary","animation"],"genre_tags": ["Drama","Thriller","Comedy","Documentary","Biopic","Crime","Mystery","Romance","Family","Period","Action","Adventure","Sci-Fi","Horror","Fantasy","War","Musical","Animation","Sports"],"budget_min_usd": 500000,"budget_max_usd": null,"amount_usd_approx": null,"grant_type": "public_fund","recurrence": "rolling","nationality_required": false,"co_production_required": false},
{"fund_name": "Fonds Images Afrique \u2014 Institut Fran\u00e7ais","territory": "Morocco","continent": "Africa","eligible_formats": ["feature","documentary","animation","short"],"genre_tags": ["Drama","Thriller","Comedy","Horror","Documentary","Biopic","Period","Crime","Fantasy","Mystery","Romance","Family","Sci-Fi","War","Action","Adventure","Animation"],"budget_min_usd": null,"budget_max_usd": null,"amount_usd_approx": 66000,"grant_type": "co_production","recurrence": "annual","nationality_required": false,"co_production_required": true},
{"fund_name": "Hubert Bals Fund \u2014 IDFAcademy","territory": "Nigeria","continent": "Africa","eligible_formats": ["feature","documentary"],"genre_tags": ["Drama","Thriller","Documentary","Biopic","Crime","Mystery","Romance","Family","Period","Action","Sci-Fi","Horror","Fantasy","War","Comedy","Musical","Animation"],"budget_min_usd": null,"budget_max_usd": null,"amount_usd_approx": 11000,"grant_type": "foundation","recurrence": "annual","nationality_required": false,"co_production_required": false},
{"fund_name": "Hot Docs \u2014 Blue Ice Fund (Africa Focus)","territory": "Western Cape","continent": "Africa","eligible_formats": ["documentary"],"genre_tags": ["Documentary"],"budget_min_usd": null,"budget_max_usd": null,"amount_usd_approx": 11000,"grant_type": "foundation","recurrence": "annual","nationality_required": false,"co_production_required": false},
{"fund_name": "Busan International Film Festival \u2014 Asian Cinema Fund","territory": "South Korea","continent": "Asia-Pacific","eligible_formats": ["feature","documentary"],"genre_tags": ["Drama","Thriller","Comedy","Horror","Sci-Fi","Fantasy","Crime","Mystery","Romance","Action","Adventure","Documentary","Family","Biopic","Period","War","Musical","Animation"],"budget_min_usd": null,"budget_max_usd": null,"amount_usd_approx": 30000,"grant_type": "foundation","recurrence": "annual","nationality_required": false,"co_production_required": false},
{"fund_name": "Singapore International Film Festival \u2014 Southeast Asian Film Fund","territory": "Singapore","continent": "Asia-Pacific","eligible_formats": ["feature","documentary","short"],"genre_tags": ["Drama","Thriller","Comedy","Horror","Sci-Fi","Fantasy","Crime","Mystery","Romance","Action","Adventure","Documentary","Family","Biopic","Period","War","Musical","Animation"],"budget_min_usd": null,"budget_max_usd": null,"amount_usd_approx": 22000,"grant_type": "foundation","recurrence": "annual","nationality_required": false,"co_production_required": false},
{"fund_name": "Australian Film Television and Radio School \u2014 Short Film Fund","territory": "Australia","continent": "Asia-Pacific","eligible_formats": ["short","animation","documentary"],"genre_tags": ["Drama","Thriller","Comedy","Horror","Sci-Fi","Fantasy","Crime","Mystery","Romance","Action","Documentary","Family","Animation","Musical"],"budget_min_usd": null,"budget_max_usd": 35000,"amount_usd_approx": 20000,"grant_type": "public_fund","recurrence": "annual","nationality_required": true,"co_production_required": false},
{"fund_name": "NHK \u2014 Japan Broadcasting Corporation International Co-Production","territory": "Japan","continent": "Asia-Pacific","eligible_formats": ["documentary","feature","tv_series"],"genre_tags": ["Documentary","Drama","Sci-Fi","Biopic","Period","War","Mystery","Family","Adventure","Crime","Thriller"],"budget_min_usd": 200000,"budget_max_usd": null,"amount_usd_approx": 136000,"grant_type": "broadcaster","recurrence": "rolling","nationality_required": false,"co_production_required": true},
{"fund_name": "NFDC \u2014 National Film Development Corporation India \u2014 Production Grant","territory": "India","continent": "Asia-Pacific","eligible_formats": ["feature","documentary","animation"],"genre_tags": ["Drama","Thriller","Comedy","Horror","Sci-Fi","Fantasy","Crime","Mystery","Romance","Action","Adventure","Documentary","Family","Biopic","Period","War","Musical","Sports","Animation"],"budget_min_usd": null,"budget_max_usd": null,"amount_usd_approx": 60000,"grant_type": "public_fund","recurrence": "annual","nationality_required": true,"co_production_required": false},
{"fund_name": "Berlinale World Cinema Fund","territory": "Global","continent": "Global","eligible_formats": ["feature","documentary"],"genre_tags": ["Drama","Thriller","Comedy","Horror","Sci-Fi","Fantasy","Crime","Mystery","Romance","Action","Adventure","Documentary","Family","Biopic","Period","War","Musical","Animation","Sports","Western"],"budget_min_usd": null,"budget_max_usd": null,"amount_usd_approx": 110000,"grant_type": "public_fund","recurrence": "annual","nationality_required": false,"co_production_required": false},
{"fund_name": "Sundance Institute \u2014 Catalyst Forum","territory": "Global","continent": "Global","eligible_formats": ["feature","documentary"],"genre_tags": ["Documentary","Drama","Thriller","Crime","Biopic","Family","Romance","Period","Sci-Fi","Mystery","Comedy","Horror","War","Action","Adventure","Musical","Sports","Fantasy","Animation","Western"],"budget_min_usd": 500000,"budget_max_usd": 5000000,"amount_usd_approx": null,"grant_type": "foundation","recurrence": "annual","nationality_required": false,"co_production_required": false},
{"fund_name": "IFFR \u2014 Hubert Bals Fund \u2014 Production","territory": "Global","continent": "Global","eligible_formats": ["feature","documentary"],"genre_tags": ["Drama","Thriller","Documentary","Biopic","Crime","Mystery","Romance","Family","Period","Action","Sci-Fi","Horror","Fantasy","War","Comedy","Musical","Animation","Adventure","Sports"],"budget_min_usd": null,"budget_max_usd": null,"amount_usd_approx": 33000,"grant_type": "foundation","recurrence": "annual","nationality_required": false,"co_production_required": false},
{"fund_name": "Tribeca \u2014 IF/Then Shorts \u2014 Social Impact Documentary","territory": "Global","continent": "Global","eligible_formats": ["short","documentary"],"genre_tags": ["Documentary"],"budget_min_usd": null,"budget_max_usd": 60000,"amount_usd_approx": 50000,"grant_type": "foundation","recurrence": "annual","nationality_required": false,"co_production_required": false},
{"fund_name": "CNRS Images \u2014 Scientific and Environmental Documentary","territory": "Global","continent": "Global","eligible_formats": ["documentary","short"],"genre_tags": ["Documentary","Sci-Fi","Family","Adventure"],"budget_min_usd": null,"budget_max_usd": null,"amount_usd_approx": 44000,"grant_type": "public_fund","recurrence": "rolling","nationality_required": false,"co_production_required": true},
{"fund_name": "Icelandic Film Centre \u2014 Short Film and New Talent","territory": "Iceland","continent": "Europe","eligible_formats": ["short","animation","documentary"],"genre_tags": ["Drama","Thriller","Comedy","Horror","Sci-Fi","Fantasy","Crime","Mystery","Romance","Animation","Family","Documentary"],"budget_min_usd": null,"budget_max_usd": 75000,"amount_usd_approx": 73000,"grant_type": "public_fund","recurrence": "annual","nationality_required": true,"co_production_required": false},
{"fund_name": "Arts Council Malta \u2014 Creative Fund","territory": "Malta","continent": "Europe","eligible_formats": ["feature","short","documentary","animation"],"genre_tags": ["Drama","Thriller","Comedy","Horror","Sci-Fi","Fantasy","Crime","Mystery","Romance","Animation","Family","Documentary","Biopic","Period","Musical","Action","Adventure","War"],"budget_min_usd": null,"budget_max_usd": null,"amount_usd_approx": 33000,"grant_type": "public_fund","recurrence": "rolling","nationality_required": true,"co_production_required": false},
{"fund_name": "NAC \u2014 National Arts Council Singapore \u2014 Creation Grant","territory": "Singapore","continent": "Asia-Pacific","eligible_formats": ["feature","short","documentary","animation","tv_series"],"genre_tags": ["Drama","Thriller","Comedy","Horror","Sci-Fi","Fantasy","Crime","Mystery","Romance","Animation","Family","Documentary","Biopic","Period","Musical","Action","Adventure","War","Sports"],"budget_min_usd": null,"budget_max_usd": null,"amount_usd_approx": 37000,"grant_type": "public_fund","recurrence": "rolling","nationality_required": true,"co_production_required": false},
{"fund_name": "Film and Television Institute of India \u2014 Short Film","territory": "India","continent": "Asia-Pacific","eligible_formats": ["short","documentary","animation"],"genre_tags": ["Drama","Thriller","Comedy","Horror","Sci-Fi","Fantasy","Crime","Mystery","Romance","Animation","Family","Documentary","Biopic","Period","Musical","Action","War","Sports"],"budget_min_usd": null,"budget_max_usd": 25000,"amount_usd_approx": 24000,"grant_type": "public_fund","recurrence": "annual","nationality_required": true,"co_production_required": false},
{"fund_name": "IMCINE \u2014 FIDECINE (Commercial Cinema Fund)","territory": "Mexico","continent": "Americas","eligible_formats": ["feature","animation"],"genre_tags": ["Drama","Thriller","Comedy","Horror","Sci-Fi","Fantasy","Crime","Mystery","Romance","Action","Adventure","Family","Animation","Biopic","Period","War","Musical","Sports","Western"],"budget_min_usd": 500000,"budget_max_usd": null,"amount_usd_approx": 870000,"grant_type": "public_fund","recurrence": "annual","nationality_required": true,"co_production_required": false},
{"fund_name": "ANCINE \u2014 FSA Desenvolvimento (Development)","territory": "Brazil","continent": "Americas","eligible_formats": ["feature","documentary","animation"],"genre_tags": ["Drama","Thriller","Comedy","Horror","Documentary","Biopic","Period","Crime","Fantasy","Mystery","Romance","Animation","Family","Sci-Fi","War","Action","Adventure","Musical","Sports"],"budget_min_usd": null,"budget_max_usd": null,"amount_usd_approx": 100000,"grant_type": "public_fund","recurrence": "annual","nationality_required": true,"co_production_required": false},
{"fund_name": "EWA Network \u2014 Women in Film and Television","territory": "Global","continent": "Global","eligible_formats": ["feature","tv_series","documentary","animation","short"],"genre_tags": ["Drama","Thriller","Comedy","Horror","Sci-Fi","Fantasy","Crime","Mystery","Romance","Action","Adventure","Documentary","Family","Biopic","Period","War","Musical","Animation","Sports","Western"],"budget_min_usd": null,"budget_max_usd": null,"amount_usd_approx": 11000,"grant_type": "foundation","recurrence": "annual","nationality_required": false,"co_production_required": false},
{"fund_name": "Cine Foundation International \u2014 Production Grant","territory": "Global","continent": "Global","eligible_formats": ["feature","documentary","short"],"genre_tags": ["Documentary","Drama","Thriller","Crime","Biopic","Family","Romance","Period","Sci-Fi","Mystery","Comedy","Horror","War","Action","Adventure","Musical","Sports","Fantasy","Animation","Western"],"budget_min_usd": null,"budget_max_usd": null,"amount_usd_approx": 25000,"grant_type": "foundation","recurrence": "rolling","nationality_required": false,"co_production_required": false}
]
''')
