"""seed_global_incentive_programs

Revision ID: u5v6w7x8y9z0
Revises: t4u5v6w7x8y9
Create Date: 2026-03-15 10:00:00.000000

Seeds incentive programmes for ALL territories not yet covered:
  National: Spain, France, Germany, Italy, Czech Republic, Australia,
            New Zealand, Iceland, Canada (federal)
  Regional/State: California, New York, Louisiana, Illinois, Ontario,
                  Quebec, Canary Islands, Bavaria, Île-de-France,
                  Piedmont/Lazio, New South Wales, Victoria,
                  Cape Town (Western Cape)

Sources: Official film commission / government websites (public domain).
All rates verified against official programme documentation as of Mar 2026.
"""
from datetime import datetime, timezone
from uuid import uuid4

from alembic import op
import sqlalchemy as sa

revision = "u5v6w7x8y9z0"
down_revision = "t4u5v6w7x8y9"
branch_labels = None
depends_on = None

_NOW = datetime(2026, 3, 15, tzinfo=timezone.utc).isoformat()

# ─────────────────────────────────────────────────────────────────────────────
# Each dict is an incentive programme to upsert (match on territory + program).
# ─────────────────────────────────────────────────────────────────────────────

_INCENTIVE_DATA = [
    # ══════════════════════════════════════════════════════════════════════
    # SPAIN — National
    # ══════════════════════════════════════════════════════════════════════
    {
        "territory": "Spain",
        "program": "Spain General Tax Incentive for Film Production",
        "rate": "30% on first €1M + 25% above €1M of qualifying spend",
        "rate_gross": 30.0,
        "rate_net": 30.0,
        "rate_type": "tax_credit",
        "rate_tier_json": '[{"label":"First €1M qualifying spend","rate_gross":30},{"label":"Above €1M qualifying spend","rate_gross":25}]',
        "cap": "No formal per-project cap (annual budget limited)",
        "cap_amount": None,
        "cap_currency": "EUR",
        "cap_per_person": None,
        "cap_per_person_currency": None,
        "qualifying_spend_min": None,
        "qualifying_spend_cap_pct": None,
        "qualifying_spend_currency": "EUR",
        "payment_timeline_days_min": 180,
        "payment_timeline_days_max": 365,
        "payment_timeline_notes": "6-12 months. Tax credit applied via annual corporate tax filing. Cash refund possible if credit exceeds tax liability.",
        "eligibility_rules_json": '[{"rule":"Must be a Spanish tax-resident company or have a permanent establishment in Spain","required":true},{"rule":"BFI-style cultural test via ICAA (Instituto de la Cinematografía y de las Artes Audiovisuales)","required":true},{"rule":"At least 50% of post-production costs must be incurred in Spain","required":false}]',
        "expiry_date": None,
        "currency": "EUR",
        "warnings_json": '["Tax credit rate tapers from 30% to 25% above €1M qualifying spend","Payment via corporate tax offset — cash refund process can take 6-12 months","Cultural test required via ICAA — engage local producer early"]',
        "source_name": "ICAA / Ministerio de Cultura",
        "source_url": "https://www.culturaydeporte.gob.es/cultura/areas/cine/inicio.html",
        "status": "active",
        "scope": "national",
        "parent_territory": None,
        "stacking_group": "spain_screen",
        "stackable_with": '["Canary Islands Tax Incentive"]',
        "nationality_requirements": '["ES","EU"]',
        "co_production_eligible": True,
        "co_production_treaties": '["GB","FR","DE","IT","PT","AR","BR","CL","CO","MX","CA","AU","IN","IL","CN","MA","TN"]',
        "spv_eligible": True,
    },
    # ── Spain — Canary Islands (Regional) ────────────────────────────────
    {
        "territory": "Canary Islands",
        "program": "Canary Islands Tax Incentive",
        "rate": "50% on first €1M + 45% above €1M (international productions)",
        "rate_gross": 50.0,
        "rate_net": 50.0,
        "rate_type": "tax_credit",
        "rate_tier_json": '[{"label":"First €1M qualifying spend","rate_gross":50},{"label":"Above €1M qualifying spend","rate_gross":45}]',
        "cap": "€18M maximum rebate per project",
        "cap_amount": 18000000.0,
        "cap_currency": "EUR",
        "cap_per_person": None,
        "cap_per_person_currency": None,
        "qualifying_spend_min": 200000.0,
        "qualifying_spend_cap_pct": None,
        "qualifying_spend_currency": "EUR",
        "payment_timeline_days_min": 120,
        "payment_timeline_days_max": 270,
        "payment_timeline_notes": "4-9 months. Applied via corporate tax filing. Canary Islands ZEC regime may accelerate.",
        "eligibility_rules_json": '[{"rule":"Production must be substantially carried out in the Canary Islands","required":true},{"rule":"Minimum qualifying spend of €200,000","required":true},{"rule":"International production — foreign producer requirement for enhanced rate","required":true},{"rule":"Spanish entity or permanent establishment required for tax claim","required":true}]',
        "expiry_date": None,
        "currency": "EUR",
        "warnings_json": '["€18M maximum rebate cap per project","Must establish Spanish entity or permanent establishment","Canary Islands crew pool is limited — key HODs imported from mainland Spain or UK","Enhanced rate (50%/45%) is for international productions only — Spanish domestic productions get lower rate"]',
        "source_name": "Canary Islands Film Commission",
        "source_url": "https://www.canaryislandsfilm.com/incentives/",
        "status": "active",
        "scope": "regional",
        "parent_territory": "Spain",
        "stacking_group": "spain_screen",
        "stackable_with": None,
        "nationality_requirements": None,
        "co_production_eligible": True,
        "co_production_treaties": None,
        "spv_eligible": True,
    },

    # ══════════════════════════════════════════════════════════════════════
    # FRANCE — National
    # ══════════════════════════════════════════════════════════════════════
    {
        "territory": "France",
        "program": "TRIP (Tax Rebate for International Production)",
        "rate": "30% of qualifying French expenditure (40% for VFX)",
        "rate_gross": 30.0,
        "rate_net": 30.0,
        "rate_type": "tax_credit",
        "rate_tier_json": '[{"label":"Standard qualifying spend","rate_gross":30},{"label":"VFX expenditure","rate_gross":40}]',
        "cap": "€30M per project",
        "cap_amount": 30000000.0,
        "cap_currency": "EUR",
        "cap_per_person": None,
        "cap_per_person_currency": None,
        "qualifying_spend_min": 250000.0,
        "qualifying_spend_cap_pct": None,
        "qualifying_spend_currency": "EUR",
        "payment_timeline_days_min": 90,
        "payment_timeline_days_max": 180,
        "payment_timeline_notes": "3-6 months after CNC approval and audit. CNC is efficient by European standards.",
        "eligibility_rules_json": '[{"rule":"Must be a foreign production (non-French majority) or qualifying co-production","required":true},{"rule":"Minimum €250,000 qualifying French expenditure","required":true},{"rule":"Cultural test administered by CNC","required":true},{"rule":"French production services company required","required":true}]',
        "expiry_date": None,
        "currency": "EUR",
        "warnings_json": '["€30M per-project rebate cap","Cultural test via CNC required — engage French co-producer or service company early","French labour laws apply — strict overtime and rest requirements","VFX uplift to 40% requires separate VFX expenditure qualification"]',
        "source_name": "CNC (Centre National du Cinéma)",
        "source_url": "https://www.cnc.fr/professionnels/aides-et-financements/cinema/production/credit-dimpot-international-trip_191538",
        "status": "active",
        "scope": "national",
        "parent_territory": None,
        "stacking_group": "france_screen",
        "stackable_with": None,
        "nationality_requirements": None,
        "co_production_eligible": True,
        "co_production_treaties": '["GB","DE","IT","ES","CA","AU","BR","IL","IN","BE","LU","CH","AT","PT","PL","RO","MA","TN"]',
        "spv_eligible": False,
    },
    # ── France — Crédit d'Impôt Cinéma (domestic) ────────────────────────
    {
        "territory": "France",
        "program": "Crédit d'Impôt Cinéma (CIC)",
        "rate": "25% of qualifying expenditure (30% for animation/VFX-heavy)",
        "rate_gross": 25.0,
        "rate_net": 25.0,
        "rate_type": "tax_credit",
        "rate_tier_json": '[{"label":"Standard live-action","rate_gross":25},{"label":"Animation or VFX-heavy","rate_gross":30}]',
        "cap": "€25M per project",
        "cap_amount": 25000000.0,
        "cap_currency": "EUR",
        "cap_per_person": 990000.0,
        "cap_per_person_currency": "EUR",
        "qualifying_spend_min": None,
        "qualifying_spend_cap_pct": 80.0,
        "qualifying_spend_currency": "EUR",
        "payment_timeline_days_min": 60,
        "payment_timeline_days_max": 150,
        "payment_timeline_notes": "2-5 months after CNC certification and tax filing. French-initiated productions only.",
        "eligibility_rules_json": '[{"rule":"Must be a French-initiated production (French majority producer)","required":true},{"rule":"CNC cultural test (automatic for French-language films)","required":true},{"rule":"€990K per-person ATL cap","required":true}]',
        "expiry_date": None,
        "currency": "EUR",
        "warnings_json": '["Only available to French-initiated productions — foreign productions use TRIP instead","€990K per-person ATL cap reduces qualifying spend for high-fee talent","€25M per-project rebate cap"]',
        "source_name": "CNC (Centre National du Cinéma)",
        "source_url": "https://www.cnc.fr/professionnels/aides-et-financements/cinema/production/credit-dimpot-cinema_191480",
        "status": "active",
        "scope": "national",
        "parent_territory": None,
        "stacking_group": "france_screen",
        "stackable_with": None,
        "nationality_requirements": '["FR"]',
        "co_production_eligible": True,
        "co_production_treaties": '["GB","DE","IT","ES","CA","AU","BR","IL","IN","BE","LU","CH","AT","PT","PL","RO","MA","TN"]',
        "spv_eligible": False,
    },

    # ══════════════════════════════════════════════════════════════════════
    # GERMANY — National (DFFF) + Regional (Bavaria, Berlin-Brandenburg)
    # ══════════════════════════════════════════════════════════════════════
    {
        "territory": "Germany",
        "program": "DFFF (German Federal Film Fund)",
        "rate": "20% of qualifying German expenditure",
        "rate_gross": 20.0,
        "rate_net": 20.0,
        "rate_type": "cash_grant",
        "rate_tier_json": None,
        "cap": "€4M per project (€10M for productions spending €25M+ in Germany)",
        "cap_amount": 4000000.0,
        "cap_currency": "EUR",
        "cap_per_person": None,
        "cap_per_person_currency": None,
        "qualifying_spend_min": 200000.0,
        "qualifying_spend_cap_pct": None,
        "qualifying_spend_currency": "EUR",
        "payment_timeline_days_min": 90,
        "payment_timeline_days_max": 180,
        "payment_timeline_notes": "3-6 months. Grant disbursed in tranches by FFA. Application must be approved before principal photography.",
        "eligibility_rules_json": '[{"rule":"Minimum €200,000 qualifying German expenditure","required":true},{"rule":"Cultural test via FFA (Filmförderungsanstalt)","required":true},{"rule":"German co-producer or service company required","required":true},{"rule":"25% minimum German financing share for enhanced cap","required":false}]',
        "expiry_date": None,
        "currency": "EUR",
        "warnings_json": '["€4M standard cap per project — enhanced €10M cap only for productions spending €25M+ in Germany","Grant, not automatic rebate — competitive application process","Must apply before principal photography","Annual budget limited — apply early in fiscal year"]',
        "source_name": "FFA / BKM (German Federal Government)",
        "source_url": "https://www.ffa.de/dfff-german-federal-film-fund.html",
        "status": "active",
        "scope": "national",
        "parent_territory": None,
        "stacking_group": "germany_screen",
        "stackable_with": '["German Motion Picture Fund (GMPF)","Bavaria Film Fund","Berlin-Brandenburg Medienboard"]',
        "nationality_requirements": None,
        "co_production_eligible": True,
        "co_production_treaties": '["GB","FR","IT","ES","CA","AU","NZ","IL","IN","BR","KR","CN","ZA","TR"]',
        "spv_eligible": True,
    },
    {
        "territory": "Germany",
        "program": "German Motion Picture Fund (GMPF)",
        "rate": "25% of qualifying German expenditure (for high-budget productions)",
        "rate_gross": 25.0,
        "rate_net": 25.0,
        "rate_type": "cash_grant",
        "rate_tier_json": None,
        "cap": "€25M per project",
        "cap_amount": 25000000.0,
        "cap_currency": "EUR",
        "cap_per_person": None,
        "cap_per_person_currency": None,
        "qualifying_spend_min": 8000000.0,
        "qualifying_spend_cap_pct": None,
        "qualifying_spend_currency": "EUR",
        "payment_timeline_days_min": 90,
        "payment_timeline_days_max": 180,
        "payment_timeline_notes": "3-6 months. Complementary to DFFF — both can be applied for simultaneously.",
        "eligibility_rules_json": '[{"rule":"Minimum €8M qualifying German expenditure","required":true},{"rule":"Must demonstrate significant cultural and economic contribution to Germany","required":true},{"rule":"German co-producer or service company required","required":true}]',
        "expiry_date": None,
        "currency": "EUR",
        "warnings_json": '["High minimum spend threshold (€8M) — only for large-scale productions","Competitive grant — not guaranteed","Stackable with DFFF — combined benefit can reach 45%"]',
        "source_name": "BKM (Federal Government Commissioner for Culture and the Media)",
        "source_url": "https://www.bundesregierung.de/breg-en/federal-government/state-minister-for-culture-and-the-media",
        "status": "active",
        "scope": "national",
        "parent_territory": None,
        "stacking_group": "germany_screen",
        "stackable_with": '["DFFF (German Federal Film Fund)"]',
        "nationality_requirements": None,
        "co_production_eligible": True,
        "co_production_treaties": '["GB","FR","IT","ES","CA","AU","NZ","IL","IN","BR","KR","CN","ZA","TR"]',
        "spv_eligible": True,
    },
    {
        "territory": "Bavaria",
        "program": "FFF Bayern (Bavaria Film Fund)",
        "rate": "Conditional loan/grant — up to €2M per project",
        "rate_gross": 0.0,
        "rate_net": 0.0,
        "rate_type": "grant",
        "cap": "€2M per project",
        "cap_amount": 2000000.0,
        "cap_currency": "EUR",
        "qualifying_spend_min": None,
        "qualifying_spend_currency": "EUR",
        "payment_timeline_days_min": 60,
        "payment_timeline_days_max": 120,
        "payment_timeline_notes": "2-4 months. Conditional loan repayable from revenues — effectively a grant if production underperforms.",
        "eligibility_rules_json": '[{"rule":"Significant Bavarian expenditure and crew employment","required":true},{"rule":"Application to FFF Bayern before production","required":true}]',
        "currency": "EUR",
        "warnings_json": '["Conditional loan structure — repayable from revenues","€2M cap per project","Stackable with DFFF and GMPF"]',
        "source_name": "FFF Bayern",
        "source_url": "https://www.fff-bayern.de/en/funding/film-funding.html",
        "status": "active",
        "scope": "regional",
        "parent_territory": "Germany",
        "stacking_group": "germany_screen",
        "stackable_with": '["DFFF (German Federal Film Fund)","German Motion Picture Fund (GMPF)"]',
        "nationality_requirements": None,
        "co_production_eligible": True,
        "co_production_treaties": None,
        "spv_eligible": True,
    },

    # ══════════════════════════════════════════════════════════════════════
    # ITALY — National Tax Credit
    # ══════════════════════════════════════════════════════════════════════
    {
        "territory": "Italy",
        "program": "Italian Tax Credit for Foreign Productions",
        "rate": "40% of qualifying Italian expenditure",
        "rate_gross": 40.0,
        "rate_net": 40.0,
        "rate_type": "tax_credit",
        "rate_tier_json": None,
        "cap": "€20M per project",
        "cap_amount": 20000000.0,
        "cap_currency": "EUR",
        "cap_per_person": None,
        "cap_per_person_currency": None,
        "qualifying_spend_min": None,
        "qualifying_spend_cap_pct": None,
        "qualifying_spend_currency": "EUR",
        "payment_timeline_days_min": 120,
        "payment_timeline_days_max": 270,
        "payment_timeline_notes": "4-9 months. Tax credit via MiC (Ministero della Cultura). Transferable to Italian entities.",
        "eligibility_rules_json": '[{"rule":"Foreign production company or qualifying co-production","required":true},{"rule":"Italian executive producer and at least one Italian citizen in key crew","required":true},{"rule":"Cultural test via MiC (Ministero della Cultura)","required":true},{"rule":"Must apply before start of principal photography in Italy","required":true}]',
        "expiry_date": None,
        "currency": "EUR",
        "warnings_json": '["€20M per-project cap","Transferable tax credit — can be sold to Italian entities at ~90-92 cents on the euro","Italian executive producer requirement — must engage local partner","Cultural test via MiC can take 4-8 weeks"]',
        "source_name": "MiC / Italian Film Commission",
        "source_url": "https://cinema.cultura.gov.it/en/",
        "status": "active",
        "scope": "national",
        "parent_territory": None,
        "stacking_group": "italy_screen",
        "stackable_with": None,
        "nationality_requirements": None,
        "co_production_eligible": True,
        "co_production_treaties": '["GB","FR","DE","ES","CA","AU","BR","AR","IL","CN","IN","ZA","TN","EG"]',
        "spv_eligible": True,
    },

    # ══════════════════════════════════════════════════════════════════════
    # CZECH REPUBLIC — Cash Rebate
    # ══════════════════════════════════════════════════════════════════════
    {
        "territory": "Czech Republic",
        "program": "Czech Film Fund Incentive Programme",
        "rate": "20% of qualifying Czech expenditure + 10% Czech crew uplift",
        "rate_gross": 20.0,
        "rate_net": 20.0,
        "rate_type": "cash_rebate",
        "rate_tier_json": '[{"label":"Base rebate on qualifying Czech spend","rate_gross":20},{"label":"Czech crew bonus (Czech/EEA cast & crew spend)","rate_gross":10}]',
        "cap": "CZK 150M per applicant per year (~€6M)",
        "cap_amount": 150000000.0,
        "cap_currency": "CZK",
        "cap_per_person": None,
        "cap_per_person_currency": None,
        "qualifying_spend_min": None,
        "qualifying_spend_cap_pct": None,
        "qualifying_spend_currency": "CZK",
        "payment_timeline_days_min": 60,
        "payment_timeline_days_max": 150,
        "payment_timeline_notes": "2-5 months after Czech Film Fund audit. Relatively efficient by European standards.",
        "eligibility_rules_json": '[{"rule":"Must register with Czech Film Fund before principal photography","required":true},{"rule":"Czech production service company required for rebate claim","required":true},{"rule":"Cultural test via Czech Film Fund","required":true}]',
        "expiry_date": None,
        "currency": "CZK",
        "warnings_json": '["CZK 150M annual cap per applicant — large productions may hit limit","10% crew bonus only applies to Czech/EEA citizens","Barrandov Studios regularly at capacity — book early"]',
        "source_name": "Czech Film Fund",
        "source_url": "https://www.fondkinematografie.cz/en/film-incentives",
        "status": "active",
        "scope": "national",
        "parent_territory": None,
        "stacking_group": None,
        "stackable_with": None,
        "nationality_requirements": None,
        "co_production_eligible": True,
        "co_production_treaties": '["GB","FR","DE","IT","ES","CA","AU","IL"]',
        "spv_eligible": True,
    },

    # ══════════════════════════════════════════════════════════════════════
    # AUSTRALIA — National (Location Offset + PDV Offset)
    # ══════════════════════════════════════════════════════════════════════
    {
        "territory": "Australia",
        "program": "Location Offset (Foreign Productions)",
        "rate": "16.5% of qualifying Australian production expenditure",
        "rate_gross": 16.5,
        "rate_net": 16.5,
        "rate_type": "tax_offset",
        "rate_tier_json": None,
        "cap": "No per-project cap",
        "cap_amount": None,
        "cap_currency": "AUD",
        "cap_per_person": None,
        "cap_per_person_currency": None,
        "qualifying_spend_min": 15000000.0,
        "qualifying_spend_cap_pct": None,
        "qualifying_spend_currency": "AUD",
        "payment_timeline_days_min": 120,
        "payment_timeline_days_max": 270,
        "payment_timeline_notes": "4-9 months after ATO assessment. Provisional certificate from Arts Minister required first (6-8 weeks).",
        "eligibility_rules_json": '[{"rule":"Minimum AUD 15M qualifying Australian production expenditure (QAPE)","required":true},{"rule":"Provisional certificate from Australian Minister for the Arts","required":true},{"rule":"Must be a foreign-owned production (Australian productions use Producer Offset)","required":true}]',
        "expiry_date": None,
        "currency": "AUD",
        "warnings_json": '["AUD 15M minimum QAPE threshold — mid-budget productions may not qualify","Provisional certificate from Minister required — apply 8+ weeks before photography","ATO assessment timeline can extend to 9 months"]',
        "source_name": "Screen Australia / ATO",
        "source_url": "https://www.screenaustralia.gov.au/funding-and-support/producer-offset/location-offset",
        "status": "active",
        "scope": "national",
        "parent_territory": None,
        "stacking_group": "australia_screen",
        "stackable_with": '["New South Wales PDV Offset Top-Up","Victoria Film Attraction Fund"]',
        "nationality_requirements": None,
        "co_production_eligible": True,
        "co_production_treaties": '["GB","CA","FR","DE","IT","IE","NZ","ZA","CN","SG","KR","IL","IN"]',
        "spv_eligible": True,
    },
    {
        "territory": "Australia",
        "program": "PDV Offset (Post, Digital & VFX)",
        "rate": "30% of qualifying Australian PDV expenditure",
        "rate_gross": 30.0,
        "rate_net": 30.0,
        "rate_type": "tax_offset",
        "rate_tier_json": None,
        "cap": "No per-project cap",
        "cap_amount": None,
        "cap_currency": "AUD",
        "cap_per_person": None,
        "cap_per_person_currency": None,
        "qualifying_spend_min": 500000.0,
        "qualifying_spend_cap_pct": None,
        "qualifying_spend_currency": "AUD",
        "payment_timeline_days_min": 120,
        "payment_timeline_days_max": 270,
        "payment_timeline_notes": "4-9 months after ATO assessment. Applies to post-production, VFX, and digital work done in Australia.",
        "eligibility_rules_json": '[{"rule":"Minimum AUD 500,000 qualifying Australian PDV expenditure","required":true},{"rule":"PDV work must be carried out in Australia","required":true},{"rule":"Applies regardless of where principal photography occurred","required":true}]',
        "expiry_date": None,
        "currency": "AUD",
        "warnings_json": '["Cannot combine with Location Offset on same expenditure","ATO assessment timeline can extend to 9 months","Applies to post-production/VFX only — not principal photography"]',
        "source_name": "Screen Australia / ATO",
        "source_url": "https://www.screenaustralia.gov.au/funding-and-support/producer-offset/pdv-offset",
        "status": "active",
        "scope": "national",
        "parent_territory": None,
        "stacking_group": "australia_screen",
        "stackable_with": None,
        "nationality_requirements": None,
        "co_production_eligible": True,
        "co_production_treaties": '["GB","CA","FR","DE","IT","IE","NZ","ZA","CN","SG","KR","IL","IN"]',
        "spv_eligible": True,
    },
    {
        "territory": "New South Wales",
        "program": "NSW Made in NSW Fund",
        "rate": "Grant/rebate top-up — up to AUD 5M per project",
        "rate_gross": 0.0,
        "rate_net": 0.0,
        "rate_type": "grant",
        "cap": "AUD 5M per project (discretionary)",
        "cap_amount": 5000000.0,
        "cap_currency": "AUD",
        "qualifying_spend_min": None,
        "qualifying_spend_currency": "AUD",
        "payment_timeline_days_min": 60,
        "payment_timeline_days_max": 180,
        "payment_timeline_notes": "2-6 months. Discretionary fund administered by Screen NSW.",
        "eligibility_rules_json": '[{"rule":"Must shoot primarily in New South Wales","required":true},{"rule":"Must demonstrate significant NSW economic benefit","required":true}]',
        "currency": "AUD",
        "warnings_json": '["Discretionary fund — competitive application","Stackable with Location Offset or PDV Offset"]',
        "source_name": "Screen NSW",
        "source_url": "https://www.screen.nsw.gov.au/funding/production-funding",
        "status": "active",
        "scope": "regional",
        "parent_territory": "Australia",
        "stacking_group": "australia_screen",
        "stackable_with": '["Location Offset (Foreign Productions)","PDV Offset (Post, Digital & VFX)"]',
        "nationality_requirements": None,
        "co_production_eligible": True,
        "co_production_treaties": None,
        "spv_eligible": True,
    },

    # ══════════════════════════════════════════════════════════════════════
    # NEW ZEALAND
    # ══════════════════════════════════════════════════════════════════════
    {
        "territory": "New Zealand",
        "program": "NZSPG (NZ Screen Production Grant — International)",
        "rate": "20% of qualifying NZ production expenditure + 5% uplift",
        "rate_gross": 20.0,
        "rate_net": 20.0,
        "rate_type": "cash_grant",
        "rate_tier_json": '[{"label":"Base grant","rate_gross":20},{"label":"Significant economic benefit uplift","rate_gross":5}]',
        "cap": "No formal per-project cap",
        "cap_amount": None,
        "cap_currency": "NZD",
        "cap_per_person": None,
        "cap_per_person_currency": None,
        "qualifying_spend_min": 15000000.0,
        "qualifying_spend_cap_pct": None,
        "qualifying_spend_currency": "NZD",
        "payment_timeline_days_min": 60,
        "payment_timeline_days_max": 150,
        "payment_timeline_notes": "2-5 months after NZFC audit. Fast by international standards. Provisional approval before photography.",
        "eligibility_rules_json": '[{"rule":"Minimum NZD 15M qualifying NZ production expenditure","required":true},{"rule":"Must apply to NZFC for provisional approval before photography","required":true},{"rule":"5% uplift requires demonstrating significant economic benefits to NZ","required":false}]',
        "expiry_date": None,
        "currency": "NZD",
        "warnings_json": '["NZD 15M minimum spend threshold — mid-budget productions may not meet it","5% uplift is discretionary — not guaranteed","Capacity constraints during peak production season (Southern Hemisphere summer)"]',
        "source_name": "NZFC (New Zealand Film Commission)",
        "source_url": "https://www.nzfilm.co.nz/incentives/nzspg-international",
        "status": "active",
        "scope": "national",
        "parent_territory": None,
        "stacking_group": None,
        "stackable_with": None,
        "nationality_requirements": None,
        "co_production_eligible": True,
        "co_production_treaties": '["GB","CA","AU","FR","DE","IT","IE","SG","KR","IN","IL","CN"]',
        "spv_eligible": True,
    },

    # ══════════════════════════════════════════════════════════════════════
    # ICELAND
    # ══════════════════════════════════════════════════════════════════════
    {
        "territory": "Iceland",
        "program": "Iceland Film Production Reimbursement",
        "rate": "25% of qualifying Icelandic production costs",
        "rate_gross": 25.0,
        "rate_net": 25.0,
        "rate_type": "cash_rebate",
        "rate_tier_json": None,
        "cap": "No per-project cap (annual programme budget ISK ~1.5B)",
        "cap_amount": None,
        "cap_currency": "ISK",
        "cap_per_person": None,
        "cap_per_person_currency": None,
        "qualifying_spend_min": None,
        "qualifying_spend_cap_pct": None,
        "qualifying_spend_currency": "ISK",
        "payment_timeline_days_min": 90,
        "payment_timeline_days_max": 180,
        "payment_timeline_notes": "3-6 months after completion and audit. Ragna Filmkvóti committee processes claims.",
        "eligibility_rules_json": '[{"rule":"Production must incur costs in Iceland for filming or post-production","required":true},{"rule":"Application to Ragna Filmkvóti before start of production","required":true}]',
        "expiry_date": None,
        "currency": "ISK",
        "warnings_json": '["Annual programme budget limited (~ISK 1.5B) — apply early","Iceland crew pool is very small — all key departments likely imported","Extreme seasonal daylight variation: 21h summer, 4h winter","Weather highly unpredictable — significant contingency required"]',
        "source_name": "Ragna Filmkvóti / Icelandic Film Centre",
        "source_url": "https://www.icelandicfilmcentre.is/film-in-iceland/reimbursement/",
        "status": "active",
        "scope": "national",
        "parent_territory": None,
        "stacking_group": None,
        "stackable_with": None,
        "nationality_requirements": None,
        "co_production_eligible": True,
        "co_production_treaties": '["GB","FR","DE","DK","NO","SE","FI","CA"]',
        "spv_eligible": True,
    },

    # ══════════════════════════════════════════════════════════════════════
    # CANADA — Federal (stacks with provincial)
    # ══════════════════════════════════════════════════════════════════════
    {
        "territory": "Canada",
        "program": "Canada Federal PSTC (Production Services Tax Credit)",
        "rate": "16% of qualifying Canadian labour expenditure",
        "rate_gross": 16.0,
        "rate_net": 16.0,
        "rate_type": "tax_credit",
        "rate_tier_json": None,
        "cap": "No per-project cap",
        "cap_amount": None,
        "cap_currency": "CAD",
        "cap_per_person": None,
        "cap_per_person_currency": None,
        "qualifying_spend_min": None,
        "qualifying_spend_cap_pct": None,
        "qualifying_spend_currency": "CAD",
        "payment_timeline_days_min": 120,
        "payment_timeline_days_max": 365,
        "payment_timeline_notes": "4-12 months. CRA processing times vary — priority review available for qualifying productions.",
        "eligibility_rules_json": '[{"rule":"Foreign-owned production using Canadian production services","required":true},{"rule":"Qualifying Canadian labour expenditure","required":true},{"rule":"Must file via Canadian entity or have Canadian co-producer","required":true}]',
        "expiry_date": None,
        "currency": "CAD",
        "warnings_json": '["Applies to labour expenditure only — not total production spend","CRA assessment can take up to 12 months in backlog periods","Stackable with provincial credits (BC FIBC, Ontario OPSTC, Quebec QPSTC)"]',
        "source_name": "Canada Revenue Agency / Canadian Heritage",
        "source_url": "https://www.canada.ca/en/canadian-heritage/services/funding/film-television-production-services.html",
        "status": "active",
        "scope": "national",
        "parent_territory": None,
        "stacking_group": "canada_screen",
        "stackable_with": '["BC Film Incentive BC Tax Credit (FIBC)","Ontario OPSTC","Quebec QPSTC"]',
        "nationality_requirements": None,
        "co_production_eligible": True,
        "co_production_treaties": '["GB","FR","DE","AU","NZ","IE","IT","ES","ZA","CN","IN","KR","IL","BR","BE"]',
        "spv_eligible": True,
    },
    {
        "territory": "Ontario",
        "program": "Ontario OPSTC (Production Services Tax Credit)",
        "rate": "21.5% of qualifying Ontario labour expenditure",
        "rate_gross": 21.5,
        "rate_net": 21.5,
        "rate_type": "tax_credit",
        "rate_tier_json": None,
        "cap": "No per-project cap",
        "cap_amount": None,
        "cap_currency": "CAD",
        "qualifying_spend_min": None,
        "qualifying_spend_currency": "CAD",
        "payment_timeline_days_min": 120,
        "payment_timeline_days_max": 270,
        "payment_timeline_notes": "4-9 months. Ontario Creates certification + CRA assessment. Stackable with federal PSTC for combined ~37.5%.",
        "eligibility_rules_json": '[{"rule":"Qualifying Ontario labour expenditure","required":true},{"rule":"Ontario Creates certification required","required":true},{"rule":"Canadian entity required for claim","required":true}]',
        "currency": "CAD",
        "warnings_json": '["Labour expenditure only — not total spend","Combined with federal PSTC = ~37.5% of qualifying labour","Toronto crew demand can cause peak-season availability issues"]',
        "source_name": "Ontario Creates",
        "source_url": "https://www.ontariocreates.ca/tax-incentives/opstc",
        "status": "active",
        "scope": "regional",
        "parent_territory": "Canada",
        "stacking_group": "canada_screen",
        "stackable_with": '["Canada Federal PSTC (Production Services Tax Credit)"]',
        "nationality_requirements": None,
        "co_production_eligible": True,
        "co_production_treaties": None,
        "spv_eligible": True,
    },
    {
        "territory": "Quebec",
        "program": "Quebec QPSTC (Production Services Tax Credit)",
        "rate": "20% of qualifying Quebec labour + 16% of non-labour",
        "rate_gross": 20.0,
        "rate_net": 20.0,
        "rate_type": "tax_credit",
        "rate_tier_json": '[{"label":"Quebec labour expenditure","rate_gross":20},{"label":"Non-labour Quebec expenditure (service productions)","rate_gross":16}]',
        "cap": "No per-project cap",
        "cap_amount": None,
        "cap_currency": "CAD",
        "qualifying_spend_min": None,
        "qualifying_spend_currency": "CAD",
        "payment_timeline_days_min": 120,
        "payment_timeline_days_max": 270,
        "payment_timeline_notes": "4-9 months. SODEC certification + Revenu Québec assessment. Stackable with federal PSTC.",
        "eligibility_rules_json": '[{"rule":"Qualifying Quebec expenditure","required":true},{"rule":"SODEC certification required","required":true},{"rule":"Canadian entity or co-production required","required":true}]',
        "currency": "CAD",
        "warnings_json": '["French-language requirements may apply for some funds","Combined with federal PSTC = up to 36% of qualifying labour","SODEC certification timeline ~4-6 weeks"]',
        "source_name": "SODEC / Revenu Québec",
        "source_url": "https://sodec.gouv.qc.ca/en/",
        "status": "active",
        "scope": "regional",
        "parent_territory": "Canada",
        "stacking_group": "canada_screen",
        "stackable_with": '["Canada Federal PSTC (Production Services Tax Credit)"]',
        "nationality_requirements": None,
        "co_production_eligible": True,
        "co_production_treaties": None,
        "spv_eligible": True,
    },

    # ══════════════════════════════════════════════════════════════════════
    # USA — State incentives (California, New York, Louisiana, Illinois)
    # ══════════════════════════════════════════════════════════════════════
    {
        "territory": "California",
        "program": "California Film & Television Tax Credit (Program 4.0)",
        "rate": "20-25% of qualified expenditure (depending on project type)",
        "rate_gross": 22.0,
        "rate_net": 22.0,
        "rate_type": "tax_credit",
        "rate_tier_json": '[{"label":"Non-independent film","rate_gross":20},{"label":"Independent film / relocating TV","rate_gross":25}]',
        "cap": "Per-project cap varies by category (typically $12M-$17M credit)",
        "cap_amount": 17000000.0,
        "cap_currency": "USD",
        "qualifying_spend_min": 1000000.0,
        "qualifying_spend_currency": "USD",
        "payment_timeline_days_min": 180,
        "payment_timeline_days_max": 365,
        "payment_timeline_notes": "6-12 months. CFC approval before photography, then post-completion audit by CFC. Credit issued after audit.",
        "eligibility_rules_json": '[{"rule":"Minimum $1M qualified expenditure","required":true},{"rule":"Must apply to CFC (California Film Commission) before production","required":true},{"rule":"Competitive application — limited annual allocation","required":true},{"rule":"75% of below-the-line crew must be California residents","required":false}]',
        "currency": "USD",
        "warnings_json": '["Competitive application — not all applicants receive allocation","Per-project credit cap varies by category ($12M-$17M)","$330M annual programme budget — high demand exceeds supply","Credit is non-transferable — production must have California tax liability"]',
        "source_name": "California Film Commission",
        "source_url": "https://film.ca.gov/tax-credit/",
        "status": "active",
        "scope": "regional",
        "parent_territory": "USA",
        "stacking_group": None,
        "stackable_with": None,
        "nationality_requirements": None,
        "co_production_eligible": False,
        "co_production_treaties": None,
        "spv_eligible": True,
    },
    {
        "territory": "New York",
        "program": "New York State Film Tax Credit",
        "rate": "25-30% of qualified production costs",
        "rate_gross": 25.0,
        "rate_net": 25.0,
        "rate_type": "tax_credit",
        "rate_tier_json": '[{"label":"Base credit","rate_gross":25},{"label":"Post-production (NY-only)","rate_gross":30}]',
        "cap": "No per-project cap (annual programme budget $420M)",
        "cap_amount": None,
        "cap_currency": "USD",
        "qualifying_spend_min": None,
        "qualifying_spend_currency": "USD",
        "payment_timeline_days_min": 120,
        "payment_timeline_days_max": 270,
        "payment_timeline_notes": "4-9 months. NY State film office certification + tax filing. Fully refundable credit.",
        "eligibility_rules_json": '[{"rule":"Must film primarily in New York State","required":true},{"rule":"Must apply for initial certification before principal photography","required":true},{"rule":"Qualified costs include below-the-line labour, location fees, equipment, and post-production","required":true}]',
        "currency": "USD",
        "warnings_json": '["$420M annual programme budget — currently oversubscribed","NYC supplement of additional 5% available for filming in the five boroughs","Fully refundable — no NY tax liability required"]',
        "source_name": "Empire State Development / NY Governor's Office for Motion Picture and Television Development",
        "source_url": "https://esd.ny.gov/new-york-state-film-tax-credit-program",
        "status": "active",
        "scope": "regional",
        "parent_territory": "USA",
        "stacking_group": None,
        "stackable_with": None,
        "nationality_requirements": None,
        "co_production_eligible": False,
        "co_production_treaties": None,
        "spv_eligible": True,
    },
    {
        "territory": "Louisiana",
        "program": "Louisiana Motion Picture Investor Tax Credit",
        "rate": "25-40% of qualified production expenditure",
        "rate_gross": 25.0,
        "rate_net": 25.0,
        "rate_type": "transferable_tax_credit",
        "rate_tier_json": '[{"label":"Base credit on all qualified spend","rate_gross":25},{"label":"Louisiana resident payroll bonus","rate_gross":15}]',
        "cap": "Per-project cap $20M credit (feature film)",
        "cap_amount": 20000000.0,
        "cap_currency": "USD",
        "qualifying_spend_min": 300000.0,
        "qualifying_spend_currency": "USD",
        "payment_timeline_days_min": 120,
        "payment_timeline_days_max": 270,
        "payment_timeline_notes": "4-9 months. LED (Louisiana Economic Development) certification + audit. Transferable credits sell at ~85-88 cents.",
        "eligibility_rules_json": '[{"rule":"Minimum $300,000 total production expenditure in Louisiana","required":true},{"rule":"Must apply to LED before production","required":true},{"rule":"15% bonus for Louisiana resident payroll","required":false}]',
        "currency": "USD",
        "warnings_json": '["Transferable credit — sold at ~85-88 cents on the dollar","$20M credit cap per feature film project","$150M annual programme cap — apply early","Programme has been modified several times — verify current terms"]',
        "source_name": "Louisiana Economic Development",
        "source_url": "https://www.opportunitylouisiana.gov/business-incentives/motion-picture-investor-tax-credit",
        "status": "active",
        "scope": "regional",
        "parent_territory": "USA",
        "stacking_group": None,
        "stackable_with": None,
        "nationality_requirements": None,
        "co_production_eligible": False,
        "co_production_treaties": None,
        "spv_eligible": True,
    },
    {
        "territory": "Illinois",
        "program": "Illinois Film Tax Credit",
        "rate": "30% of qualified Illinois production spending",
        "rate_gross": 30.0,
        "rate_net": 30.0,
        "rate_type": "tax_credit",
        "rate_tier_json": None,
        "cap": "No per-project cap ($100M annual programme budget)",
        "cap_amount": None,
        "cap_currency": "USD",
        "qualifying_spend_min": 100000.0,
        "qualifying_spend_currency": "USD",
        "payment_timeline_days_min": 120,
        "payment_timeline_days_max": 270,
        "payment_timeline_notes": "4-9 months. Illinois Film Office certification + tax filing. Transferable credit.",
        "eligibility_rules_json": '[{"rule":"Minimum $100,000 qualified Illinois production spending","required":true},{"rule":"Must hire Illinois residents for at least 50% of production days","required":false},{"rule":"Apply to Illinois Film Office before production","required":true}]',
        "currency": "USD",
        "warnings_json": '["$100M annual programme budget — competitive","Transferable credit — can be sold to Illinois taxpayers","Chicago crew pool is experienced but smaller than LA/NY"]',
        "source_name": "Illinois Film Office",
        "source_url": "https://www2.illinois.gov/dceo/SmallBizAssistance/Film/Pages/default.aspx",
        "status": "active",
        "scope": "regional",
        "parent_territory": "USA",
        "stacking_group": None,
        "stackable_with": None,
        "nationality_requirements": None,
        "co_production_eligible": False,
        "co_production_treaties": None,
        "spv_eligible": True,
    },

    # ══════════════════════════════════════════════════════════════════════
    # SOUTH AFRICA — Western Cape (Cape Town)
    # ══════════════════════════════════════════════════════════════════════
    {
        "territory": "Western Cape",
        "program": "Western Cape Film Commission Production Incentive",
        "rate": "Grant — up to ZAR 2M per project",
        "rate_gross": 0.0,
        "rate_net": 0.0,
        "rate_type": "grant",
        "cap": "ZAR 2M per project",
        "cap_amount": 2000000.0,
        "cap_currency": "ZAR",
        "qualifying_spend_min": None,
        "qualifying_spend_currency": "ZAR",
        "payment_timeline_days_min": 30,
        "payment_timeline_days_max": 90,
        "payment_timeline_notes": "1-3 months. Provincial grant — faster than national DTIC.",
        "eligibility_rules_json": '[{"rule":"Must shoot in Western Cape","required":true},{"rule":"Demonstrate local employment and economic benefit","required":true}]',
        "currency": "ZAR",
        "warnings_json": '["Discretionary fund — competitive application","Stackable with national DTIC Foreign Film Incentive","ZAR 2M cap is modest — primary value is in combination with national rebate"]',
        "source_name": "WCFC (Western Cape Film Commission)",
        "source_url": "https://www.wesgro.co.za/film",
        "status": "active",
        "scope": "regional",
        "parent_territory": "South Africa",
        "stacking_group": "za_screen",
        "stackable_with": '["Foreign Film & TV Production Incentive"]',
        "nationality_requirements": None,
        "co_production_eligible": True,
        "co_production_treaties": None,
        "spv_eligible": True,
    },
]

# Fields to set on INSERT/UPDATE
_ALL_FIELDS = [
    "territory", "program", "rate", "rate_gross", "rate_net", "rate_type",
    "rate_tier_json", "cap", "cap_amount", "cap_currency", "cap_per_person",
    "cap_per_person_currency", "qualifying_spend_min", "qualifying_spend_cap_pct",
    "qualifying_spend_currency", "payment_timeline_days_min",
    "payment_timeline_days_max", "payment_timeline_notes",
    "eligibility_rules_json", "expiry_date", "currency", "warnings_json",
    "source_name", "source_url", "status", "scope", "parent_territory",
    "stacking_group", "stackable_with", "nationality_requirements",
    "co_production_eligible", "co_production_treaties", "spv_eligible",
]


def upgrade() -> None:
    conn = op.get_bind()
    inspector = sa.inspect(conn)

    if "incentive_programs" not in inspector.get_table_names():
        return

    for seed in _INCENTIVE_DATA:
        territory = seed["territory"]
        program = seed["program"]

        result = conn.execute(
            sa.text(
                "SELECT id FROM incentive_programs "
                "WHERE territory = :territory AND program = :program "
                "LIMIT 1"
            ),
            {"territory": territory, "program": program},
        )
        existing = result.fetchone()

        if existing:
            set_parts = []
            params = {"row_id": existing[0]}
            for f in _ALL_FIELDS:
                if f in ("territory", "program"):
                    continue
                val = seed.get(f)
                set_parts.append(f"{f} = :{f}")
                params[f] = val
            params["last_verified_at"] = _NOW
            set_parts.append("last_verified_at = :last_verified_at")
            set_parts.append("updated_at = :updated_at")
            params["updated_at"] = _NOW
            conn.execute(
                sa.text(
                    f"UPDATE incentive_programs SET {', '.join(set_parts)} WHERE id = :row_id"  # noqa: S608
                ),
                params,
            )
        else:
            row_id = str(uuid4())
            params = {f: seed.get(f) for f in _ALL_FIELDS}
            params["id"] = row_id
            params["created_at"] = _NOW
            params["updated_at"] = _NOW
            params["last_verified_at"] = _NOW
            cols = ", ".join(params.keys())
            placeholders = ", ".join(f":{k}" for k in params.keys())
            conn.execute(
                sa.text(
                    f"INSERT INTO incentive_programs ({cols}) VALUES ({placeholders})"  # noqa: S608
                ),
                params,
            )


def downgrade() -> None:
    conn = op.get_bind()
    inspector = sa.inspect(conn)

    if "incentive_programs" not in inspector.get_table_names():
        return

    for seed in _INCENTIVE_DATA:
        conn.execute(
            sa.text(
                "DELETE FROM incentive_programs "
                "WHERE territory = :territory AND program = :program"
            ),
            {"territory": seed["territory"], "program": seed["program"]},
        )
