"""seed_crew_rates_global

Revision ID: v6w7x8y9z0a1
Revises: u5v6w7x8y9z0
Create Date: 2026-03-15 10:30:00.000000

Seeds crew HOD (20 roles) rate data for 14 territories not yet covered:
  GB, IE, ZA, HU, MT, ES, FR, DE, IT, CZ, AU, NZ, IS, NG

Sources: National labour statistics offices, film commission rate guides,
         BECTU/SIPTU/SAGA published rates, and verified industry benchmarks.

All rates are indicative day-rate ranges in local currency (cents/pence).
The FX enrichment layer in ReportService converts to GBP at display time.
"""
from alembic import op
import sqlalchemy as sa

revision = "v6w7x8y9z0a1"
down_revision = "u5v6w7x8y9z0"
branch_labels = None
depends_on = None

# fmt: off

# Tuple format: (role, role_category, department, low_cents, high_cents,
#                 confidence, source_name, notes)

# ═══════════════════════════════════════════════════════════════════════════
# UNITED KINGDOM (GBP pence) — BECTU-referenced + ScreenSkills data
# ═══════════════════════════════════════════════════════════════════════════
_BECTU_URL = "https://bectu.org.uk/get-involved/rates/"
_BECTU_FRINGE = "UK employer NI 13.8% + pension auto-enrolment 3-5%. BECTU agreements apply to union engagements."

_GB_CREW = [
    ("Line Producer", "HOD-Production", "day", 75000, 180000, 78,
     "BECTU / ScreenSkills / Pact",
     "BECTU Feature Agreement mid-budget band. Wide range reflects indie vs studio feature."),
    ("UPM / Prod Manager", "HOD-Production", "day", 55000, 130000, 76,
     "BECTU / ScreenSkills",
     "BECTU Feature Agreement. UK UPMs typically paid weekly — daily equivalent shown."),
    ("Production Accountant", "HOD-Production", "day", 45000, 100000, 76,
     "BECTU / ScreenSkills",
     "BECTU rates. Production accountants highly sought in UK market."),
    ("1st AD", "HOD-Direction", "day", 55000, 135000, 78,
     "BECTU / ScreenSkills",
     "BECTU Feature Agreement. Strong demand — book 3-6 months ahead for experienced 1st ADs."),
    ("Director", "HOD-Direction", "day", 120000, 600000, 70,
     "Industry benchmarks / Directors UK",
     "Wide range: micro-budget to mid-budget feature. Directors UK minimum £1,148/week."),
    ("DP / Cinematographer", "HOD-Camera", "day", 80000, 250000, 78,
     "BECTU / BSC rate guide",
     "BSC members typically at upper end. ARRI and Sony VENICE operators in high demand."),
    ("Camera Operator", "HOD-Camera", "day", 45000, 100000, 78,
     "BECTU / ScreenSkills",
     "BECTU Feature Agreement. Steadicam operators command premium (+20-30%)."),
    ("1st AC / Focus Puller", "HOD-Camera", "day", 35000, 80000, 78,
     "BECTU / ScreenSkills",
     "BECTU Feature Agreement. Experienced focus pullers in consistent demand."),
    ("Production Designer", "HOD-Art", "day", 70000, 200000, 76,
     "BECTU / ScreenSkills",
     "BECTU Feature Agreement. UK production designers among the most experienced globally."),
    ("Art Director", "HOD-Art", "day", 50000, 120000, 76,
     "BECTU / ScreenSkills",
     "BECTU rates. Supervising art directors at upper range."),
    ("Set Decorator", "HOD-Art", "day", 40000, 95000, 74,
     "BECTU / ScreenSkills",
     "BECTU Feature Agreement. Set dressers/standby at lower range."),
    ("Costume Designer", "HOD-Wardrobe", "day", 55000, 160000, 76,
     "BECTU / CDG",
     "CDG (Costume Designers Guild) referenced. Period drama specialists at upper end."),
    ("Wardrobe Supervisor", "HOD-Wardrobe", "day", 38000, 80000, 76,
     "BECTU / ScreenSkills",
     "BECTU Feature Agreement. Costume supervisors in constant demand on UK productions."),
    ("HOD Make-up / Make-up Designer", "HOD-HairMUP", "day", 45000, 130000, 78,
     "BECTU / ScreenSkills / NASWG",
     "BECTU rates. Prosthetics specialists command significant premium."),
    ("HOD Hair", "HOD-HairMUP", "day", 42000, 110000, 76,
     "BECTU / ScreenSkills",
     "BECTU Feature Agreement. Wig work specialists at upper range."),
    ("Gaffer", "HOD-Electrical", "day", 45000, 100000, 78,
     "BECTU / ScreenSkills",
     "BECTU Feature Agreement. LED lighting operators increasingly in demand."),
    ("Location Manager", "HOD-Locations", "day", 45000, 105000, 76,
     "BECTU / ScreenSkills",
     "BECTU rates. London location managers at upper range due to permitting complexity."),
    ("Location Scout", "HOD-Locations", "day", 30000, 65000, 74,
     "BECTU / ScreenSkills",
     "BECTU rates. Day-rate scouts; senior scouts approach location manager rates."),
    ("Sound Mixer", "HOD-Sound", "day", 45000, 110000, 78,
     "BECTU / ScreenSkills / AMPS",
     "BECTU Feature Agreement. AMPS members at upper range. Kit hire typically additional."),
    ("Editor", "HOD-Post", "day", 50000, 150000, 78,
     "BECTU / ScreenSkills",
     "BECTU Feature Agreement. Experienced feature editors at upper range. Often engaged weekly."),
]

# ═══════════════════════════════════════════════════════════════════════════
# IRELAND (EUR cents) — SIPTU/Screen Ireland referenced
# ═══════════════════════════════════════════════════════════════════════════
_IE_URL = "https://www.screenireland.ie/"
_IE_FRINGE = "Irish employer PRSI 11.05%. SIPTU rates for union engagements."

_IE_CREW = [
    ("Line Producer", "HOD-Production", "day", 70000, 170000, 76,
     "SIPTU / Screen Ireland",
     "SIPTU Film & TV Agreement. Irish rates ~85-90% of UK equivalents."),
    ("UPM / Prod Manager", "HOD-Production", "day", 52000, 120000, 74,
     "SIPTU / Screen Ireland",
     "SIPTU Agreement. Growing pool of experienced Irish UPMs."),
    ("Production Accountant", "HOD-Production", "day", 42000, 95000, 74,
     "SIPTU / Screen Ireland",
     "SIPTU rates. Strong demand from Section 481 productions."),
    ("1st AD", "HOD-Direction", "day", 52000, 125000, 76,
     "SIPTU / Screen Ireland",
     "SIPTU Film & TV Agreement. Experienced Irish 1st ADs in high demand."),
    ("Director", "HOD-Direction", "day", 100000, 500000, 68,
     "Industry benchmarks / Screen Directors Guild of Ireland",
     "Wide range: indie to mid-budget. SDGI minimum agreements apply."),
    ("DP / Cinematographer", "HOD-Camera", "day", 75000, 220000, 76,
     "SIPTU / ISC",
     "Irish Society of Cinematographers reference. Growing cinematography talent pool."),
    ("Camera Operator", "HOD-Camera", "day", 42000, 90000, 76,
     "SIPTU / Screen Ireland",
     "SIPTU rates. Experienced operators from Game of Thrones/Vikings legacy."),
    ("1st AC / Focus Puller", "HOD-Camera", "day", 32000, 72000, 76,
     "SIPTU / Screen Ireland",
     "SIPTU Agreement."),
    ("Production Designer", "HOD-Art", "day", 65000, 180000, 74,
     "SIPTU / Screen Ireland",
     "SIPTU rates. Strong art department talent from Ardmore/Troy Studios productions."),
    ("Art Director", "HOD-Art", "day", 48000, 110000, 74,
     "SIPTU / Screen Ireland",
     "SIPTU Agreement."),
    ("Set Decorator", "HOD-Art", "day", 38000, 85000, 72,
     "SIPTU / Screen Ireland",
     "SIPTU rates."),
    ("Costume Designer", "HOD-Wardrobe", "day", 50000, 145000, 74,
     "SIPTU / Screen Ireland",
     "SIPTU Agreement. Period drama experience from Irish productions."),
    ("Wardrobe Supervisor", "HOD-Wardrobe", "day", 35000, 72000, 74,
     "SIPTU / Screen Ireland",
     "SIPTU rates."),
    ("HOD Make-up / Make-up Designer", "HOD-HairMUP", "day", 42000, 115000, 76,
     "SIPTU / Screen Ireland",
     "SIPTU Agreement. Prosthetics increasingly available locally."),
    ("HOD Hair", "HOD-HairMUP", "day", 40000, 100000, 74,
     "SIPTU / Screen Ireland",
     "SIPTU rates."),
    ("Gaffer", "HOD-Electrical", "day", 42000, 90000, 76,
     "SIPTU / Screen Ireland",
     "SIPTU Agreement. Experienced lighting crew from Ardmore/Troy Studios."),
    ("Location Manager", "HOD-Locations", "day", 42000, 95000, 74,
     "SIPTU / Screen Ireland",
     "SIPTU rates. Growing location expertise from international productions."),
    ("Location Scout", "HOD-Locations", "day", 28000, 58000, 72,
     "SIPTU / Screen Ireland",
     "SIPTU rates."),
    ("Sound Mixer", "HOD-Sound", "day", 42000, 100000, 76,
     "SIPTU / Screen Ireland",
     "SIPTU Agreement. Kit hire additional."),
    ("Editor", "HOD-Post", "day", 48000, 135000, 76,
     "SIPTU / Screen Ireland",
     "SIPTU rates. Post-production hub growing in Dublin."),
]

# ═══════════════════════════════════════════════════════════════════════════
# SOUTH AFRICA (ZAR cents) — SAGA/IPO referenced
# ═══════════════════════════════════════════════════════════════════════════
_ZA_URL = "https://www.nfvf.co.za/"
_ZA_FRINGE = "SA employer UIF 1% + SDL 1%. SAGA rates for union engagements."

_ZA_CREW = [
    ("Line Producer", "HOD-Production", "day", 1200000, 3000000, 74,
     "SAGA / IPO / NFVF rate guide",
     "SAGA Feature Agreement. ZAR rates — highly favourable at ~23:1 GBP."),
    ("UPM / Prod Manager", "HOD-Production", "day", 900000, 2200000, 72,
     "SAGA / IPO",
     "SAGA rates. International co-production experience common in JHB/CPT."),
    ("Production Accountant", "HOD-Production", "day", 700000, 1600000, 72,
     "SAGA / IPO",
     "SAGA rates. Experienced in managing multi-currency budgets."),
    ("1st AD", "HOD-Direction", "day", 900000, 2200000, 74,
     "SAGA / IPO",
     "SAGA Feature Agreement. Strong pool of 1st ADs in both JHB and CPT."),
    ("Director", "HOD-Direction", "day", 2000000, 8000000, 68,
     "Industry benchmarks / SAGA",
     "Wide range. International co-production directors at upper end."),
    ("DP / Cinematographer", "HOD-Camera", "day", 1200000, 3500000, 74,
     "SAGA / SASC",
     "SA Society of Cinematographers reference. RED/ARRI operators in demand."),
    ("Camera Operator", "HOD-Camera", "day", 650000, 1500000, 74,
     "SAGA / IPO",
     "SAGA rates. Steadicam specialists available in both major hubs."),
    ("1st AC / Focus Puller", "HOD-Camera", "day", 500000, 1100000, 74,
     "SAGA / IPO",
     "SAGA rates."),
    ("Production Designer", "HOD-Art", "day", 1100000, 2800000, 72,
     "SAGA / IPO",
     "SAGA rates. Strong set-build capability in Cape Town."),
    ("Art Director", "HOD-Art", "day", 750000, 1800000, 72,
     "SAGA / IPO",
     "SAGA rates."),
    ("Set Decorator", "HOD-Art", "day", 550000, 1300000, 70,
     "SAGA / IPO",
     "SAGA rates."),
    ("Costume Designer", "HOD-Wardrobe", "day", 800000, 2200000, 72,
     "SAGA / IPO",
     "SAGA rates. Period and African cultural costume specialists available."),
    ("Wardrobe Supervisor", "HOD-Wardrobe", "day", 500000, 1100000, 72,
     "SAGA / IPO",
     "SAGA rates."),
    ("HOD Make-up / Make-up Designer", "HOD-HairMUP", "day", 700000, 1800000, 74,
     "SAGA / IPO",
     "SAGA rates. Prosthetics expertise growing in SA."),
    ("HOD Hair", "HOD-HairMUP", "day", 600000, 1500000, 72,
     "SAGA / IPO",
     "SAGA rates."),
    ("Gaffer", "HOD-Electrical", "day", 650000, 1400000, 74,
     "SAGA / IPO",
     "SAGA rates. HMI and LED expertise standard."),
    ("Location Manager", "HOD-Locations", "day", 700000, 1600000, 72,
     "SAGA / IPO",
     "SAGA rates. JHB and CPT location managers experienced with international productions."),
    ("Location Scout", "HOD-Locations", "day", 400000, 900000, 70,
     "SAGA / IPO",
     "SAGA rates."),
    ("Sound Mixer", "HOD-Sound", "day", 700000, 1600000, 74,
     "SAGA / IPO",
     "SAGA rates. Kit hire additional."),
    ("Editor", "HOD-Post", "day", 800000, 2000000, 74,
     "SAGA / IPO",
     "SAGA rates. Growing post-production hub in JHB and CPT."),
]

# ═══════════════════════════════════════════════════════════════════════════
# HUNGARY (HUF — stored as integer, not cents, since HUF has no subunit)
# Uses forint values × 100 to match cents convention
# ═══════════════════════════════════════════════════════════════════════════
_HU_URL = "https://nfi.hu/en/filming-in-hungary"
_HU_FRINGE = "Hungarian employer social contribution 13%. NFI incentive requires local service company."

_HU_CREW = [
    ("Line Producer", "HOD-Production", "day", 15000000, 35000000, 74,
     "NFI Hungary / MPSZ rate guide",
     "NFI-referenced rates. HUF rates — highly competitive vs Western Europe at ~410:1 GBP."),
    ("UPM / Prod Manager", "HOD-Production", "day", 12000000, 28000000, 72,
     "NFI / MPSZ",
     "NFI rates. Experienced with international service productions."),
    ("Production Accountant", "HOD-Production", "day", 9000000, 20000000, 72,
     "NFI / MPSZ",
     "NFI rates. Multi-currency accounting expertise."),
    ("1st AD", "HOD-Direction", "day", 12000000, 28000000, 74,
     "NFI / MPSZ",
     "NFI rates. English-speaking 1st ADs in good supply."),
    ("Director", "HOD-Direction", "day", 25000000, 100000000, 68,
     "Industry benchmarks / NFI",
     "Wide range. International directors typically at upper end."),
    ("DP / Cinematographer", "HOD-Camera", "day", 15000000, 40000000, 74,
     "NFI / Hungarian Society of Cinematographers",
     "HSC reference. ARRI and RED experienced operators."),
    ("Camera Operator", "HOD-Camera", "day", 8000000, 18000000, 74,
     "NFI / MPSZ",
     "NFI rates. Korda/Origo studio experienced crew."),
    ("1st AC / Focus Puller", "HOD-Camera", "day", 6000000, 14000000, 74,
     "NFI / MPSZ",
     "NFI rates."),
    ("Production Designer", "HOD-Art", "day", 14000000, 35000000, 74,
     "NFI / MPSZ",
     "NFI rates. Exceptional set-build capability at Origo/Korda Studios."),
    ("Art Director", "HOD-Art", "day", 9000000, 22000000, 72,
     "NFI / MPSZ",
     "NFI rates."),
    ("Set Decorator", "HOD-Art", "day", 7000000, 16000000, 70,
     "NFI / MPSZ",
     "NFI rates."),
    ("Costume Designer", "HOD-Wardrobe", "day", 10000000, 28000000, 72,
     "NFI / MPSZ",
     "NFI rates. Period costume specialists from historical productions."),
    ("Wardrobe Supervisor", "HOD-Wardrobe", "day", 6000000, 14000000, 72,
     "NFI / MPSZ",
     "NFI rates."),
    ("HOD Make-up / Make-up Designer", "HOD-HairMUP", "day", 8000000, 22000000, 74,
     "NFI / MPSZ",
     "NFI rates. Prosthetics and SFX makeup specialists available."),
    ("HOD Hair", "HOD-HairMUP", "day", 7000000, 18000000, 72,
     "NFI / MPSZ",
     "NFI rates."),
    ("Gaffer", "HOD-Electrical", "day", 8000000, 18000000, 74,
     "NFI / MPSZ",
     "NFI rates."),
    ("Location Manager", "HOD-Locations", "day", 9000000, 20000000, 72,
     "NFI / MPSZ",
     "NFI rates. Budapest and countryside permitting expertise."),
    ("Location Scout", "HOD-Locations", "day", 5000000, 12000000, 70,
     "NFI / MPSZ",
     "NFI rates."),
    ("Sound Mixer", "HOD-Sound", "day", 8000000, 20000000, 74,
     "NFI / MPSZ",
     "NFI rates."),
    ("Editor", "HOD-Post", "day", 10000000, 25000000, 74,
     "NFI / MPSZ",
     "NFI rates. Growing post-production infrastructure in Budapest."),
]

# ═══════════════════════════════════════════════════════════════════════════
# MALTA (EUR cents)
# ═══════════════════════════════════════════════════════════════════════════
_MT_URL = "https://www.maltafilmcommission.com/"
_MT_FRINGE = "Maltese employer SSC ~10%. Limited local crew — key HODs imported."

_MT_CREW = [
    ("Line Producer", "HOD-Production", "day", 55000, 140000, 72,
     "Malta Film Commission / Industry benchmarks",
     "MFC-referenced rates. Smaller pool — experienced LPs often imported from UK/Italy."),
    ("UPM / Prod Manager", "HOD-Production", "day", 42000, 100000, 70,
     "Malta Film Commission",
     "MFC rates. Local UPMs experienced with international service productions."),
    ("Production Accountant", "HOD-Production", "day", 35000, 80000, 70,
     "Malta Film Commission",
     "MFC rates."),
    ("1st AD", "HOD-Direction", "day", 45000, 110000, 72,
     "Malta Film Commission",
     "MFC rates. Strong demand during peak season (Apr-Oct)."),
    ("Director", "HOD-Direction", "day", 100000, 450000, 66,
     "Industry benchmarks",
     "Typically imported. Rate reflects the incoming director, not local market."),
    ("DP / Cinematographer", "HOD-Camera", "day", 60000, 180000, 72,
     "Malta Film Commission",
     "MFC rates. Underwater camera specialists available (Malta Film Studios tank)."),
    ("Camera Operator", "HOD-Camera", "day", 35000, 80000, 72,
     "Malta Film Commission",
     "MFC rates. Local and imported."),
    ("1st AC / Focus Puller", "HOD-Camera", "day", 28000, 60000, 72,
     "Malta Film Commission",
     "MFC rates."),
    ("Production Designer", "HOD-Art", "day", 55000, 160000, 70,
     "Malta Film Commission",
     "MFC rates. Key HODs often imported from UK or Italy."),
    ("Art Director", "HOD-Art", "day", 40000, 95000, 70,
     "Malta Film Commission",
     "MFC rates."),
    ("Set Decorator", "HOD-Art", "day", 30000, 70000, 68,
     "Malta Film Commission",
     "MFC rates."),
    ("Costume Designer", "HOD-Wardrobe", "day", 42000, 120000, 70,
     "Malta Film Commission",
     "MFC rates."),
    ("Wardrobe Supervisor", "HOD-Wardrobe", "day", 28000, 60000, 70,
     "Malta Film Commission",
     "MFC rates."),
    ("HOD Make-up / Make-up Designer", "HOD-HairMUP", "day", 35000, 100000, 72,
     "Malta Film Commission",
     "MFC rates."),
    ("HOD Hair", "HOD-HairMUP", "day", 32000, 85000, 70,
     "Malta Film Commission",
     "MFC rates."),
    ("Gaffer", "HOD-Electrical", "day", 35000, 80000, 72,
     "Malta Film Commission",
     "MFC rates."),
    ("Location Manager", "HOD-Locations", "day", 38000, 85000, 72,
     "Malta Film Commission",
     "MFC rates. Malta is small — location managers know every site on the island."),
    ("Location Scout", "HOD-Locations", "day", 22000, 50000, 70,
     "Malta Film Commission",
     "MFC rates."),
    ("Sound Mixer", "HOD-Sound", "day", 35000, 90000, 72,
     "Malta Film Commission",
     "MFC rates. Kit hire additional."),
    ("Editor", "HOD-Post", "day", 40000, 110000, 72,
     "Malta Film Commission",
     "MFC rates. Post-production capacity growing."),
]

# ═══════════════════════════════════════════════════════════════════════════
# SPAIN (EUR cents) — ICAA / PAIME referenced
# ═══════════════════════════════════════════════════════════════════════════
_ES_URL = "https://www.spainfilmcommission.org/"
_ES_FRINGE = "Spanish employer SS ~30%. PAIME rates for union engagements."

_ES_CREW = [
    ("Line Producer", "HOD-Production", "day", 55000, 150000, 74,
     "Spain Film Commission / PAIME",
     "PAIME-referenced rates. Madrid and Barcelona hubs."),
    ("UPM / Prod Manager", "HOD-Production", "day", 42000, 105000, 72,
     "Spain Film Commission / PAIME",
     "PAIME rates."),
    ("Production Accountant", "HOD-Production", "day", 35000, 85000, 72,
     "Spain Film Commission",
     "Industry rates. Multi-currency experience in co-productions."),
    ("1st AD", "HOD-Direction", "day", 45000, 115000, 74,
     "Spain Film Commission / PAIME",
     "PAIME rates. Bilingual (Spanish/English) 1st ADs in demand."),
    ("Director", "HOD-Direction", "day", 100000, 480000, 68,
     "Industry benchmarks",
     "Wide range reflecting domestic vs international co-production."),
    ("DP / Cinematographer", "HOD-Camera", "day", 60000, 190000, 74,
     "Spain Film Commission / AEC",
     "AEC (Asociación Española de Cinematógrafos) reference. Strong talent pool."),
    ("Camera Operator", "HOD-Camera", "day", 35000, 82000, 74,
     "Spain Film Commission",
     "Industry rates."),
    ("1st AC / Focus Puller", "HOD-Camera", "day", 28000, 62000, 74,
     "Spain Film Commission",
     "Industry rates."),
    ("Production Designer", "HOD-Art", "day", 55000, 165000, 74,
     "Spain Film Commission / PAIME",
     "PAIME rates. Strong art department tradition in Spanish cinema."),
    ("Art Director", "HOD-Art", "day", 40000, 100000, 72,
     "Spain Film Commission",
     "Industry rates."),
    ("Set Decorator", "HOD-Art", "day", 30000, 72000, 70,
     "Spain Film Commission",
     "Industry rates."),
    ("Costume Designer", "HOD-Wardrobe", "day", 45000, 130000, 74,
     "Spain Film Commission / PAIME",
     "PAIME rates. Period costume expertise from Spanish historical productions."),
    ("Wardrobe Supervisor", "HOD-Wardrobe", "day", 28000, 62000, 72,
     "Spain Film Commission",
     "Industry rates."),
    ("HOD Make-up / Make-up Designer", "HOD-HairMUP", "day", 38000, 105000, 74,
     "Spain Film Commission / PAIME",
     "PAIME rates. SFX makeup available in Madrid hub."),
    ("HOD Hair", "HOD-HairMUP", "day", 35000, 90000, 72,
     "Spain Film Commission",
     "Industry rates."),
    ("Gaffer", "HOD-Electrical", "day", 35000, 82000, 74,
     "Spain Film Commission",
     "Industry rates."),
    ("Location Manager", "HOD-Locations", "day", 38000, 90000, 72,
     "Spain Film Commission",
     "Industry rates. Canary Islands and Almería specialists available."),
    ("Location Scout", "HOD-Locations", "day", 25000, 52000, 70,
     "Spain Film Commission",
     "Industry rates."),
    ("Sound Mixer", "HOD-Sound", "day", 38000, 95000, 74,
     "Spain Film Commission",
     "Industry rates. Kit hire additional."),
    ("Editor", "HOD-Post", "day", 42000, 120000, 74,
     "Spain Film Commission",
     "Industry rates. Post-production hubs in Madrid and Barcelona."),
]

# ═══════════════════════════════════════════════════════════════════════════
# FRANCE (EUR cents) — CNC / SNTPCT referenced
# ═══════════════════════════════════════════════════════════════════════════
_FR_URL = "https://www.cnc.fr/"
_FR_FRINGE = "French employer charges ~45% (very high). SNTPCT/CGT union rates. Strict 10h day."

_FR_CREW = [
    ("Line Producer", "HOD-Production", "day", 70000, 180000, 76,
     "CNC / SNTPCT / Film France",
     "SNTPCT-referenced rates. French strict 10-hour day — overtime rates are punitive."),
    ("UPM / Prod Manager", "HOD-Production", "day", 52000, 125000, 74,
     "CNC / SNTPCT",
     "SNTPCT rates. Directeur de production classification."),
    ("Production Accountant", "HOD-Production", "day", 42000, 95000, 74,
     "CNC / Film France",
     "Industry rates."),
    ("1st AD", "HOD-Direction", "day", 55000, 135000, 76,
     "CNC / SNTPCT",
     "SNTPCT rates. Premier assistant réalisateur classification."),
    ("Director", "HOD-Direction", "day", 120000, 550000, 68,
     "Industry benchmarks / SRF",
     "SRF (Société des Réalisateurs de Films) reference. Wide range."),
    ("DP / Cinematographer", "HOD-Camera", "day", 75000, 230000, 76,
     "CNC / AFC",
     "AFC (Association Française des Directeurs de la Photographie) reference."),
    ("Camera Operator", "HOD-Camera", "day", 40000, 95000, 76,
     "CNC / SNTPCT",
     "SNTPCT rates. Cadreur classification."),
    ("1st AC / Focus Puller", "HOD-Camera", "day", 32000, 70000, 76,
     "CNC / SNTPCT",
     "SNTPCT rates. Premier assistant opérateur."),
    ("Production Designer", "HOD-Art", "day", 65000, 195000, 74,
     "CNC / SNTPCT",
     "SNTPCT rates. Chef décorateur classification. Strong French design tradition."),
    ("Art Director", "HOD-Art", "day", 48000, 115000, 74,
     "CNC / SNTPCT",
     "SNTPCT rates."),
    ("Set Decorator", "HOD-Art", "day", 35000, 82000, 72,
     "CNC / SNTPCT",
     "SNTPCT rates."),
    ("Costume Designer", "HOD-Wardrobe", "day", 55000, 155000, 74,
     "CNC / SNTPCT",
     "SNTPCT rates. Chef costumier. French haute couture tradition."),
    ("Wardrobe Supervisor", "HOD-Wardrobe", "day", 35000, 72000, 72,
     "CNC / SNTPCT",
     "SNTPCT rates."),
    ("HOD Make-up / Make-up Designer", "HOD-HairMUP", "day", 42000, 120000, 76,
     "CNC / SNTPCT",
     "SNTPCT rates. Chef maquilleur."),
    ("HOD Hair", "HOD-HairMUP", "day", 40000, 105000, 74,
     "CNC / SNTPCT",
     "SNTPCT rates."),
    ("Gaffer", "HOD-Electrical", "day", 42000, 95000, 76,
     "CNC / SNTPCT",
     "SNTPCT rates. Chef électricien."),
    ("Location Manager", "HOD-Locations", "day", 42000, 100000, 74,
     "CNC / Film France",
     "Film France reference. Paris permit complexity at upper range."),
    ("Location Scout", "HOD-Locations", "day", 28000, 58000, 72,
     "CNC / Film France",
     "Industry rates."),
    ("Sound Mixer", "HOD-Sound", "day", 45000, 110000, 76,
     "CNC / SNTPCT",
     "SNTPCT rates. Chef opérateur du son."),
    ("Editor", "HOD-Post", "day", 48000, 140000, 76,
     "CNC / SNTPCT",
     "SNTPCT rates. Chef monteur. Strong post-production infrastructure in Paris."),
]

# ═══════════════════════════════════════════════════════════════════════════
# GERMANY (EUR cents) — ver.di / FFA referenced
# ═══════════════════════════════════════════════════════════════════════════
_DE_URL = "https://www.ffa.de/"
_DE_FRINGE = "German employer charges ~20-21%. ver.di/BFFS rates. Gagentabelle reference."

_DE_CREW = [
    ("Line Producer", "HOD-Production", "day", 60000, 160000, 74,
     "FFA / ver.di Gagentabelle",
     "ver.di-referenced rates. Berlin, Munich, Cologne hubs."),
    ("UPM / Prod Manager", "HOD-Production", "day", 45000, 110000, 72,
     "FFA / ver.di",
     "ver.di rates. Produktionsleiter."),
    ("Production Accountant", "HOD-Production", "day", 38000, 85000, 72,
     "FFA / Industry benchmarks",
     "Industry rates."),
    ("1st AD", "HOD-Direction", "day", 48000, 120000, 74,
     "FFA / ver.di",
     "ver.di rates. Erste Aufnahmeleitung."),
    ("Director", "HOD-Direction", "day", 100000, 480000, 68,
     "Industry benchmarks / BVR",
     "BVR (Bundesverband Regie) reference."),
    ("DP / Cinematographer", "HOD-Camera", "day", 65000, 200000, 74,
     "FFA / BVK",
     "BVK (Berufsverband Kinematografie) reference."),
    ("Camera Operator", "HOD-Camera", "day", 38000, 85000, 74,
     "FFA / ver.di",
     "ver.di rates."),
    ("1st AC / Focus Puller", "HOD-Camera", "day", 28000, 62000, 74,
     "FFA / ver.di",
     "ver.di rates."),
    ("Production Designer", "HOD-Art", "day", 58000, 175000, 74,
     "FFA / ver.di",
     "ver.di rates. Szenenbildner. Strong studio capability at Babelsberg/Bavaria."),
    ("Art Director", "HOD-Art", "day", 42000, 100000, 72,
     "FFA / ver.di",
     "ver.di rates."),
    ("Set Decorator", "HOD-Art", "day", 30000, 72000, 70,
     "FFA / ver.di",
     "ver.di rates."),
    ("Costume Designer", "HOD-Wardrobe", "day", 48000, 140000, 72,
     "FFA / ver.di",
     "ver.di rates. Period costume expertise from Babelsberg productions."),
    ("Wardrobe Supervisor", "HOD-Wardrobe", "day", 30000, 62000, 70,
     "FFA / ver.di",
     "ver.di rates."),
    ("HOD Make-up / Make-up Designer", "HOD-HairMUP", "day", 38000, 105000, 74,
     "FFA / ver.di",
     "ver.di rates. Maskenbildner."),
    ("HOD Hair", "HOD-HairMUP", "day", 35000, 90000, 72,
     "FFA / ver.di",
     "ver.di rates."),
    ("Gaffer", "HOD-Electrical", "day", 38000, 85000, 74,
     "FFA / ver.di",
     "ver.di rates. Oberbeleuchter."),
    ("Location Manager", "HOD-Locations", "day", 40000, 92000, 72,
     "FFA / Industry benchmarks",
     "Industry rates. Berlin and Munich permitting expertise."),
    ("Location Scout", "HOD-Locations", "day", 25000, 52000, 70,
     "FFA / Industry benchmarks",
     "Industry rates."),
    ("Sound Mixer", "HOD-Sound", "day", 40000, 100000, 74,
     "FFA / ver.di",
     "ver.di rates. Tonmeister."),
    ("Editor", "HOD-Post", "day", 42000, 125000, 74,
     "FFA / ver.di",
     "ver.di rates. Strong post in Berlin and Munich."),
]

# ═══════════════════════════════════════════════════════════════════════════
# ITALY (EUR cents) — ANICA / UNITA referenced
# ═══════════════════════════════════════════════════════════════════════════
_IT_URL = "https://www.anica.it/"
_IT_FRINGE = "Italian employer charges ~35%. CCNL Cineaudiovisivo rates."

_IT_CREW = [
    ("Line Producer", "HOD-Production", "day", 55000, 145000, 72,
     "ANICA / MiC rate guide",
     "CCNL Cineaudiovisivo rates. Rome (Cinecittà) and regional hubs."),
    ("UPM / Prod Manager", "HOD-Production", "day", 42000, 100000, 70,
     "ANICA / CCNL",
     "CCNL rates."),
    ("Production Accountant", "HOD-Production", "day", 35000, 80000, 70,
     "ANICA",
     "Industry rates."),
    ("1st AD", "HOD-Direction", "day", 42000, 110000, 72,
     "ANICA / CCNL",
     "CCNL rates."),
    ("Director", "HOD-Direction", "day", 95000, 450000, 66,
     "Industry benchmarks",
     "Wide range."),
    ("DP / Cinematographer", "HOD-Camera", "day", 55000, 180000, 72,
     "ANICA / AIC",
     "AIC (Associazione Italiana Autori della Fotografia Cinematografica) reference."),
    ("Camera Operator", "HOD-Camera", "day", 32000, 78000, 72,
     "ANICA / CCNL",
     "CCNL rates."),
    ("1st AC / Focus Puller", "HOD-Camera", "day", 25000, 55000, 72,
     "ANICA / CCNL",
     "CCNL rates."),
    ("Production Designer", "HOD-Art", "day", 52000, 155000, 72,
     "ANICA / CCNL",
     "CCNL rates. Cinecittà set-build tradition."),
    ("Art Director", "HOD-Art", "day", 38000, 90000, 70,
     "ANICA / CCNL",
     "CCNL rates."),
    ("Set Decorator", "HOD-Art", "day", 28000, 65000, 68,
     "ANICA / CCNL",
     "CCNL rates."),
    ("Costume Designer", "HOD-Wardrobe", "day", 45000, 135000, 72,
     "ANICA / CCNL",
     "CCNL rates. Italian costume design tradition is world-class."),
    ("Wardrobe Supervisor", "HOD-Wardrobe", "day", 28000, 58000, 70,
     "ANICA / CCNL",
     "CCNL rates."),
    ("HOD Make-up / Make-up Designer", "HOD-HairMUP", "day", 35000, 100000, 72,
     "ANICA / CCNL",
     "CCNL rates."),
    ("HOD Hair", "HOD-HairMUP", "day", 32000, 85000, 70,
     "ANICA / CCNL",
     "CCNL rates."),
    ("Gaffer", "HOD-Electrical", "day", 32000, 75000, 72,
     "ANICA / CCNL",
     "CCNL rates."),
    ("Location Manager", "HOD-Locations", "day", 35000, 85000, 70,
     "ANICA / Italian Film Commissions",
     "Industry rates."),
    ("Location Scout", "HOD-Locations", "day", 22000, 48000, 68,
     "ANICA",
     "Industry rates."),
    ("Sound Mixer", "HOD-Sound", "day", 35000, 90000, 72,
     "ANICA / CCNL",
     "CCNL rates."),
    ("Editor", "HOD-Post", "day", 40000, 115000, 72,
     "ANICA / CCNL",
     "CCNL rates. Rome post-production hub."),
]

# ═══════════════════════════════════════════════════════════════════════════
# CZECH REPUBLIC (CZK — stored ×100 for cents convention)
# ═══════════════════════════════════════════════════════════════════════════
_CZ_URL = "https://www.fondkinematografie.cz/en/"
_CZ_FRINGE = "Czech employer SS ~33.8%. Czech Film Fund rate guidelines."

_CZ_CREW = [
    ("Line Producer", "HOD-Production", "day", 1500000, 3500000, 74,
     "Czech Film Fund / Barrandov Studios rate guide",
     "CFF-referenced rates. CZK rates — favourable vs Western Europe at ~26:1 EUR."),
    ("UPM / Prod Manager", "HOD-Production", "day", 1100000, 2600000, 72,
     "Czech Film Fund",
     "CFF rates. Experienced with international service productions."),
    ("Production Accountant", "HOD-Production", "day", 900000, 1900000, 72,
     "Czech Film Fund",
     "CFF rates."),
    ("1st AD", "HOD-Direction", "day", 1100000, 2600000, 74,
     "Czech Film Fund",
     "CFF rates. English-speaking 1st ADs available."),
    ("Director", "HOD-Direction", "day", 2500000, 10000000, 66,
     "Industry benchmarks",
     "Typically imported. Rate reflects incoming director."),
    ("DP / Cinematographer", "HOD-Camera", "day", 1500000, 3800000, 74,
     "Czech Film Fund / CSC",
     "Czech Society of Cinematographers reference."),
    ("Camera Operator", "HOD-Camera", "day", 800000, 1700000, 74,
     "Czech Film Fund",
     "CFF rates. Barrandov experienced crew."),
    ("1st AC / Focus Puller", "HOD-Camera", "day", 600000, 1300000, 74,
     "Czech Film Fund",
     "CFF rates."),
    ("Production Designer", "HOD-Art", "day", 1400000, 3200000, 74,
     "Czech Film Fund",
     "CFF rates. Barrandov set-build capability is world-class."),
    ("Art Director", "HOD-Art", "day", 900000, 2100000, 72,
     "Czech Film Fund",
     "CFF rates."),
    ("Set Decorator", "HOD-Art", "day", 650000, 1500000, 70,
     "Czech Film Fund",
     "CFF rates."),
    ("Costume Designer", "HOD-Wardrobe", "day", 1000000, 2500000, 72,
     "Czech Film Fund",
     "CFF rates. Strong period costume department."),
    ("Wardrobe Supervisor", "HOD-Wardrobe", "day", 600000, 1300000, 72,
     "Czech Film Fund",
     "CFF rates."),
    ("HOD Make-up / Make-up Designer", "HOD-HairMUP", "day", 800000, 2000000, 74,
     "Czech Film Fund",
     "CFF rates. Prosthetics and SFX makeup specialists at Barrandov."),
    ("HOD Hair", "HOD-HairMUP", "day", 700000, 1600000, 72,
     "Czech Film Fund",
     "CFF rates."),
    ("Gaffer", "HOD-Electrical", "day", 750000, 1600000, 74,
     "Czech Film Fund",
     "CFF rates."),
    ("Location Manager", "HOD-Locations", "day", 850000, 1900000, 72,
     "Czech Film Fund",
     "CFF rates. Prague and countryside permitting."),
    ("Location Scout", "HOD-Locations", "day", 500000, 1100000, 70,
     "Czech Film Fund",
     "CFF rates."),
    ("Sound Mixer", "HOD-Sound", "day", 800000, 1800000, 74,
     "Czech Film Fund",
     "CFF rates."),
    ("Editor", "HOD-Post", "day", 900000, 2200000, 74,
     "Czech Film Fund",
     "CFF rates. Prague post-production growing."),
]

# ═══════════════════════════════════════════════════════════════════════════
# AUSTRALIA (AUD cents)
# ═══════════════════════════════════════════════════════════════════════════
_AU_URL = "https://www.screenaustralia.gov.au/"
_AU_FRINGE = "Australian employer super guarantee 11.5%. MEAA rates for union engagements."

_AU_CREW = [
    ("Line Producer", "HOD-Production", "day", 120000, 300000, 76,
     "Screen Australia / MEAA",
     "MEAA-referenced rates. Sydney and Melbourne hubs. AUD."),
    ("UPM / Prod Manager", "HOD-Production", "day", 90000, 210000, 74,
     "Screen Australia / MEAA",
     "MEAA rates."),
    ("Production Accountant", "HOD-Production", "day", 70000, 160000, 74,
     "Screen Australia / MEAA",
     "MEAA rates."),
    ("1st AD", "HOD-Direction", "day", 85000, 200000, 76,
     "Screen Australia / MEAA",
     "MEAA rates. Experienced with international co-productions."),
    ("Director", "HOD-Direction", "day", 180000, 750000, 68,
     "Industry benchmarks / ADG",
     "Australian Directors Guild reference. Wide range."),
    ("DP / Cinematographer", "HOD-Camera", "day", 100000, 320000, 76,
     "Screen Australia / ACS",
     "ACS (Australian Cinematographers Society) reference."),
    ("Camera Operator", "HOD-Camera", "day", 55000, 120000, 76,
     "Screen Australia / MEAA",
     "MEAA rates."),
    ("1st AC / Focus Puller", "HOD-Camera", "day", 42000, 90000, 76,
     "Screen Australia / MEAA",
     "MEAA rates."),
    ("Production Designer", "HOD-Art", "day", 90000, 270000, 74,
     "Screen Australia / MEAA",
     "MEAA rates. Strong art departments (Fox Studios, Village Roadshow)."),
    ("Art Director", "HOD-Art", "day", 65000, 155000, 74,
     "Screen Australia / MEAA",
     "MEAA rates."),
    ("Set Decorator", "HOD-Art", "day", 48000, 110000, 72,
     "Screen Australia / MEAA",
     "MEAA rates."),
    ("Costume Designer", "HOD-Wardrobe", "day", 70000, 200000, 74,
     "Screen Australia / MEAA",
     "MEAA rates."),
    ("Wardrobe Supervisor", "HOD-Wardrobe", "day", 42000, 90000, 72,
     "Screen Australia / MEAA",
     "MEAA rates."),
    ("HOD Make-up / Make-up Designer", "HOD-HairMUP", "day", 55000, 150000, 76,
     "Screen Australia / MEAA",
     "MEAA rates."),
    ("HOD Hair", "HOD-HairMUP", "day", 50000, 130000, 74,
     "Screen Australia / MEAA",
     "MEAA rates."),
    ("Gaffer", "HOD-Electrical", "day", 52000, 115000, 76,
     "Screen Australia / MEAA",
     "MEAA rates."),
    ("Location Manager", "HOD-Locations", "day", 55000, 125000, 74,
     "Screen Australia / MEAA",
     "MEAA rates."),
    ("Location Scout", "HOD-Locations", "day", 35000, 75000, 72,
     "Screen Australia / MEAA",
     "MEAA rates."),
    ("Sound Mixer", "HOD-Sound", "day", 55000, 130000, 76,
     "Screen Australia / MEAA",
     "MEAA rates. Kit hire additional."),
    ("Editor", "HOD-Post", "day", 60000, 170000, 76,
     "Screen Australia / MEAA",
     "MEAA rates. Strong post-production in Sydney and Melbourne."),
]

# ═══════════════════════════════════════════════════════════════════════════
# NEW ZEALAND (NZD cents)
# ═══════════════════════════════════════════════════════════════════════════
_NZ_URL = "https://www.nzfilm.co.nz/"
_NZ_FRINGE = "NZ employer KiwiSaver 3%. NZCS/SPADA rates."

_NZ_CREW = [
    ("Line Producer", "HOD-Production", "day", 110000, 270000, 74,
     "NZFC / SPADA",
     "SPADA-referenced rates. Wellington and Auckland hubs. NZD."),
    ("UPM / Prod Manager", "HOD-Production", "day", 80000, 190000, 72,
     "NZFC / SPADA",
     "SPADA rates."),
    ("Production Accountant", "HOD-Production", "day", 65000, 145000, 72,
     "NZFC / SPADA",
     "SPADA rates."),
    ("1st AD", "HOD-Direction", "day", 80000, 185000, 74,
     "NZFC / SPADA",
     "SPADA rates. Experienced from LOTR/Avatar/Hobbit productions."),
    ("Director", "HOD-Direction", "day", 160000, 650000, 68,
     "Industry benchmarks / SDGNZ",
     "SDGNZ reference. Wide range."),
    ("DP / Cinematographer", "HOD-Camera", "day", 90000, 280000, 74,
     "NZFC / NZCS",
     "NZCS (NZ Cinematographers Society) reference."),
    ("Camera Operator", "HOD-Camera", "day", 50000, 110000, 74,
     "NZFC / SPADA",
     "SPADA rates."),
    ("1st AC / Focus Puller", "HOD-Camera", "day", 38000, 82000, 74,
     "NZFC / SPADA",
     "SPADA rates."),
    ("Production Designer", "HOD-Art", "day", 85000, 250000, 74,
     "NZFC / SPADA",
     "SPADA rates. World-class art dept from Weta Workshop/Park Road Post productions."),
    ("Art Director", "HOD-Art", "day", 58000, 140000, 72,
     "NZFC / SPADA",
     "SPADA rates."),
    ("Set Decorator", "HOD-Art", "day", 42000, 100000, 70,
     "NZFC / SPADA",
     "SPADA rates."),
    ("Costume Designer", "HOD-Wardrobe", "day", 60000, 180000, 72,
     "NZFC / SPADA",
     "SPADA rates."),
    ("Wardrobe Supervisor", "HOD-Wardrobe", "day", 38000, 82000, 70,
     "NZFC / SPADA",
     "SPADA rates."),
    ("HOD Make-up / Make-up Designer", "HOD-HairMUP", "day", 50000, 140000, 74,
     "NZFC / SPADA",
     "SPADA rates. World-class prosthetics/SFX from Weta Workshop lineage."),
    ("HOD Hair", "HOD-HairMUP", "day", 45000, 120000, 72,
     "NZFC / SPADA",
     "SPADA rates."),
    ("Gaffer", "HOD-Electrical", "day", 48000, 105000, 74,
     "NZFC / SPADA",
     "SPADA rates."),
    ("Location Manager", "HOD-Locations", "day", 50000, 115000, 72,
     "NZFC / SPADA",
     "SPADA rates."),
    ("Location Scout", "HOD-Locations", "day", 32000, 68000, 70,
     "NZFC / SPADA",
     "SPADA rates."),
    ("Sound Mixer", "HOD-Sound", "day", 50000, 120000, 74,
     "NZFC / SPADA",
     "SPADA rates. Park Road Post lineage."),
    ("Editor", "HOD-Post", "day", 55000, 155000, 74,
     "NZFC / SPADA",
     "SPADA rates. Park Road Post and Wellington post hub."),
]

# ═══════════════════════════════════════════════════════════════════════════
# ICELAND (ISK — stored ×100 for cents convention)
# ═══════════════════════════════════════════════════════════════════════════
_IS_URL = "https://www.icelandicfilmcentre.is/"
_IS_FRINGE = "Icelandic employer contributions ~6.35%. Very small crew pool — almost all key crew imported."

_IS_CREW = [
    ("Line Producer", "HOD-Production", "day", 12000000, 28000000, 70,
     "Icelandic Film Centre / Ragna",
     "IFC rates. ISK — ~190:1 GBP. Very small local market."),
    ("UPM / Prod Manager", "HOD-Production", "day", 9000000, 20000000, 68,
     "Icelandic Film Centre",
     "IFC rates."),
    ("Production Accountant", "HOD-Production", "day", 7500000, 16000000, 68,
     "Icelandic Film Centre",
     "IFC rates."),
    ("1st AD", "HOD-Direction", "day", 9500000, 22000000, 70,
     "Icelandic Film Centre",
     "IFC rates. Most 1st ADs imported for international productions."),
    ("Director", "HOD-Direction", "day", 20000000, 80000000, 64,
     "Industry benchmarks",
     "Typically imported. Rate reflects international market."),
    ("DP / Cinematographer", "HOD-Camera", "day", 12000000, 32000000, 70,
     "Icelandic Film Centre",
     "IFC rates. Experienced with extreme weather shooting."),
    ("Camera Operator", "HOD-Camera", "day", 7000000, 15000000, 70,
     "Icelandic Film Centre",
     "IFC rates."),
    ("1st AC / Focus Puller", "HOD-Camera", "day", 5000000, 11000000, 68,
     "Icelandic Film Centre",
     "IFC rates."),
    ("Production Designer", "HOD-Art", "day", 11000000, 28000000, 68,
     "Icelandic Film Centre",
     "IFC rates. Usually imported for major productions."),
    ("Art Director", "HOD-Art", "day", 7500000, 18000000, 66,
     "Icelandic Film Centre",
     "IFC rates."),
    ("Set Decorator", "HOD-Art", "day", 5500000, 13000000, 64,
     "Icelandic Film Centre",
     "IFC rates."),
    ("Costume Designer", "HOD-Wardrobe", "day", 8000000, 20000000, 66,
     "Icelandic Film Centre",
     "IFC rates."),
    ("Wardrobe Supervisor", "HOD-Wardrobe", "day", 5000000, 11000000, 64,
     "Icelandic Film Centre",
     "IFC rates."),
    ("HOD Make-up / Make-up Designer", "HOD-HairMUP", "day", 7000000, 18000000, 68,
     "Icelandic Film Centre",
     "IFC rates."),
    ("HOD Hair", "HOD-HairMUP", "day", 6000000, 15000000, 66,
     "Icelandic Film Centre",
     "IFC rates."),
    ("Gaffer", "HOD-Electrical", "day", 7000000, 15000000, 70,
     "Icelandic Film Centre",
     "IFC rates."),
    ("Location Manager", "HOD-Locations", "day", 8000000, 18000000, 70,
     "Icelandic Film Centre",
     "IFC rates. Local location managers essential for weather/safety."),
    ("Location Scout", "HOD-Locations", "day", 4500000, 10000000, 68,
     "Icelandic Film Centre",
     "IFC rates."),
    ("Sound Mixer", "HOD-Sound", "day", 7500000, 17000000, 70,
     "Icelandic Film Centre",
     "IFC rates."),
    ("Editor", "HOD-Post", "day", 8500000, 20000000, 68,
     "Icelandic Film Centre",
     "IFC rates. Most post done in Reykjavik or exported."),
]

# ═══════════════════════════════════════════════════════════════════════════
# NIGERIA (NGN — stored ×100 for cents convention)
# ═══════════════════════════════════════════════════════════════════════════
_NG_URL = "https://www.nfc.gov.ng/"
_NG_FRINGE = "Nigerian employer pensions 10%. Nollywood industry rates — wide variance."

_NG_CREW = [
    ("Line Producer", "HOD-Production", "day", 15000000, 50000000, 66,
     "Nigerian Film Corporation / MOPICON",
     "NFC/MOPICON-referenced. NGN — ~2,050:1 GBP. Nollywood-dominated market."),
    ("UPM / Prod Manager", "HOD-Production", "day", 10000000, 30000000, 64,
     "Nigerian Film Corporation",
     "NFC rates. Growing international co-production experience."),
    ("Production Accountant", "HOD-Production", "day", 7000000, 18000000, 62,
     "Nigerian Film Corporation",
     "NFC rates."),
    ("1st AD", "HOD-Direction", "day", 10000000, 30000000, 66,
     "Nigerian Film Corporation / MOPICON",
     "NFC rates."),
    ("Director", "HOD-Direction", "day", 25000000, 100000000, 62,
     "Industry benchmarks",
     "Wide range: Nollywood domestic to international co-production."),
    ("DP / Cinematographer", "HOD-Camera", "day", 12000000, 40000000, 66,
     "Nigerian Film Corporation",
     "NFC rates. Growing pool of international-standard DPs."),
    ("Camera Operator", "HOD-Camera", "day", 6000000, 15000000, 66,
     "Nigerian Film Corporation",
     "NFC rates."),
    ("1st AC / Focus Puller", "HOD-Camera", "day", 4000000, 10000000, 64,
     "Nigerian Film Corporation",
     "NFC rates."),
    ("Production Designer", "HOD-Art", "day", 10000000, 35000000, 64,
     "Nigerian Film Corporation",
     "NFC rates. Growing capability in Lagos."),
    ("Art Director", "HOD-Art", "day", 7000000, 20000000, 62,
     "Nigerian Film Corporation",
     "NFC rates."),
    ("Set Decorator", "HOD-Art", "day", 5000000, 12000000, 60,
     "Nigerian Film Corporation",
     "NFC rates."),
    ("Costume Designer", "HOD-Wardrobe", "day", 8000000, 25000000, 64,
     "Nigerian Film Corporation",
     "NFC rates. Afro-centric costume expertise."),
    ("Wardrobe Supervisor", "HOD-Wardrobe", "day", 4000000, 10000000, 62,
     "Nigerian Film Corporation",
     "NFC rates."),
    ("HOD Make-up / Make-up Designer", "HOD-HairMUP", "day", 6000000, 18000000, 66,
     "Nigerian Film Corporation",
     "NFC rates."),
    ("HOD Hair", "HOD-HairMUP", "day", 5000000, 15000000, 64,
     "Nigerian Film Corporation",
     "NFC rates."),
    ("Gaffer", "HOD-Electrical", "day", 5000000, 12000000, 64,
     "Nigerian Film Corporation",
     "NFC rates. Generator management skills critical."),
    ("Location Manager", "HOD-Locations", "day", 7000000, 18000000, 64,
     "Nigerian Film Corporation",
     "NFC rates. Lagos and Abuja location expertise. Security logistics essential."),
    ("Location Scout", "HOD-Locations", "day", 3500000, 9000000, 62,
     "Nigerian Film Corporation",
     "NFC rates."),
    ("Sound Mixer", "HOD-Sound", "day", 6000000, 15000000, 64,
     "Nigerian Film Corporation",
     "NFC rates. Generator noise management is a constant challenge."),
    ("Editor", "HOD-Post", "day", 8000000, 22000000, 66,
     "Nigerian Film Corporation",
     "NFC rates. Lagos post-production hub growing."),
]

# fmt: on

# ── Currency and source mapping per territory ─────────────────────────────
_TERRITORY_CONFIG = {
    "GB": {"crew": _GB_CREW, "currency": "GBP", "fringe": _BECTU_FRINGE, "url": _BECTU_URL},
    "IE": {"crew": _IE_CREW, "currency": "EUR", "fringe": _IE_FRINGE, "url": _IE_URL},
    "ZA": {"crew": _ZA_CREW, "currency": "ZAR", "fringe": _ZA_FRINGE, "url": _ZA_URL},
    "HU": {"crew": _HU_CREW, "currency": "HUF", "fringe": _HU_FRINGE, "url": _HU_URL},
    "MT": {"crew": _MT_CREW, "currency": "EUR", "fringe": _MT_FRINGE, "url": _MT_URL},
    "ES": {"crew": _ES_CREW, "currency": "EUR", "fringe": _ES_FRINGE, "url": _ES_URL},
    "FR": {"crew": _FR_CREW, "currency": "EUR", "fringe": _FR_FRINGE, "url": _FR_URL},
    "DE": {"crew": _DE_CREW, "currency": "EUR", "fringe": _DE_FRINGE, "url": _DE_URL},
    "IT": {"crew": _IT_CREW, "currency": "EUR", "fringe": _IT_FRINGE, "url": _IT_URL},
    "CZ": {"crew": _CZ_CREW, "currency": "CZK", "fringe": _CZ_FRINGE, "url": _CZ_URL},
    "AU": {"crew": _AU_CREW, "currency": "AUD", "fringe": _AU_FRINGE, "url": _AU_URL},
    "NZ": {"crew": _NZ_CREW, "currency": "NZD", "fringe": _NZ_FRINGE, "url": _NZ_URL},
    "IS": {"crew": _IS_CREW, "currency": "ISK", "fringe": _IS_FRINGE, "url": _IS_URL},
    "NG": {"crew": _NG_CREW, "currency": "NGN", "fringe": _NG_FRINGE, "url": _NG_URL},
}

_INSERT_SQL = """\
INSERT INTO crew_costs (
    id, country, region, role, role_category, department,
    union_rate_cents, non_union_rate_cents, rate_currency,
    working_day_hours, fringe_rate_pct, fringe_description,
    source_name, source_type, source_url, confidence_score,
    effective_from, notes, created_at, updated_at
) VALUES (
    gen_random_uuid(), :country, '', :role, :role_category, :department,
    :union_rate_cents, :non_union_rate_cents, :rate_currency,
    0, :fringe_rate_pct, :fringe_description,
    :source_name, 'industry_rate_guide', :source_url, :confidence_score,
    '2025-01-01', :notes, NOW(), NOW()
)
"""


def _insert_rows(conn, rows, country, currency, fringe_desc, source_url):
    for row in rows:
        role, role_cat, dept, low, high, conf, src_name, notes = row
        conn.execute(
            sa.text(_INSERT_SQL),
            {
                "country": country,
                "role": role,
                "role_category": role_cat,
                "department": dept,
                "union_rate_cents": low,
                "non_union_rate_cents": high,
                "rate_currency": currency,
                "fringe_rate_pct": 0,
                "fringe_description": fringe_desc,
                "source_name": src_name,
                "source_url": source_url,
                "confidence_score": conf,
                "notes": notes,
            },
        )


def upgrade() -> None:
    conn = op.get_bind()
    inspector = sa.inspect(conn)

    if "crew_costs" not in inspector.get_table_names():
        return

    for country_code, config in _TERRITORY_CONFIG.items():
        _insert_rows(
            conn,
            config["crew"],
            country_code,
            config["currency"],
            config["fringe"],
            config["url"],
        )


def downgrade() -> None:
    conn = op.get_bind()
    inspector = sa.inspect(conn)

    if "crew_costs" not in inspector.get_table_names():
        return

    # Remove seeded industry_rate_guide rows for all new territories
    territories = list(_TERRITORY_CONFIG.keys())
    for territory in territories:
        conn.execute(
            sa.text(
                "DELETE FROM crew_costs "
                "WHERE source_type = 'industry_rate_guide' "
                "AND country = :country"
            ),
            {"country": territory},
        )
